var searchData=
[
  ['gearly16550uartbaseaddressguid',['gEarly16550UartBaseAddressGuid',['../_early16550_uart_base_address_8h.html#a9ee7b2d7521e1bf4a303f8e3f41add30',1,'Early16550UartBaseAddress.h']]],
  ['gearlypl011baseaddressguid',['gEarlyPL011BaseAddressGuid',['../_early_p_l011_base_address_8h.html#a0a8abf4ea92f0760bcae114ebc8a3090',1,'EarlyPL011BaseAddress.h']]],
  ['garmvirttokenspaceguid',['gArmVirtTokenSpaceGuid',['../guid_common_g_arm_virt_token_space_guid.html',1,'guid_arch_root_common']]],
  ['garmvirtvariableguid',['gArmVirtVariableGuid',['../guid_common_g_arm_virt_variable_guid.html',1,'guid_arch_root_common']]],
  ['gearly16550uartbaseaddressguid',['gEarly16550UartBaseAddressGuid',['../guid_common_g_early16550_uart_base_address_guid.html',1,'guid_arch_root_common']]],
  ['gearlypl011baseaddressguid',['gEarlyPL011BaseAddressGuid',['../guid_common_g_early_p_l011_base_address_guid.html',1,'guid_arch_root_common']]],
  ['guid',['GUID',['../guid_root_page.html',1,'index']]],
  ['garmvirttokenspaceguid_2epcdforcenoacpi',['gArmVirtTokenSpaceGuid.PcdForceNoAcpi',['../pcd__pcds_dynamic_common__pcd_force_no_acpi.html',1,'pcd_PcdsDynamic_common_root_page']]],
  ['garmvirttokenspaceguid_2epcdtpm2supportenabled',['gArmVirtTokenSpaceGuid.PcdTpm2SupportEnabled',['../pcd__pcds_feature_flag_common__pcd_tpm2_support_enabled.html',1,'pcd_PcdsFeatureFlag_common_root_page']]],
  ['garmvirttokenspaceguid_2epcdcloudhvacpirsdpbaseaddress',['gArmVirtTokenSpaceGuid.PcdCloudHvAcpiRsdpBaseAddress',['../pcd__pcds_fixed_at_build_common__pcd_cloud_hv_acpi_rsdp_base_address.html',1,'pcd_PcdsFixedAtBuild_common_root_page']]],
  ['garmvirttokenspaceguid_2epcddevicetreeallocationpadding',['gArmVirtTokenSpaceGuid.PcdDeviceTreeAllocationPadding',['../pcd__pcds_fixed_at_build_common__pcd_device_tree_allocation_padding.html',1,'pcd_PcdsFixedAtBuild_common_root_page']]],
  ['garmvirttokenspaceguid_2epcddevicetreeinitialbaseaddress',['gArmVirtTokenSpaceGuid.PcdDeviceTreeInitialBaseAddress',['../pcd__pcds_fixed_at_build_common__pcd_device_tree_initial_base_address.html',1,'pcd_PcdsFixedAtBuild_common_root_page']]],
  ['garmvirttokenspaceguid_2epcdterminaltypeguidbuffer',['gArmVirtTokenSpaceGuid.PcdTerminalTypeGuidBuffer',['../pcd__pcds_fixed_at_build_common__pcd_terminal_type_guid_buffer.html',1,'pcd_PcdsFixedAtBuild_common_root_page']]],
  ['garmvirttokenspaceguid_2epcdcloudhvacpirsdpbaseaddress',['gArmVirtTokenSpaceGuid.PcdCloudHvAcpiRsdpBaseAddress',['../pcd__pcds_patchable_in_module_common__pcd_cloud_hv_acpi_rsdp_base_address.html',1,'pcd_PcdsPatchableInModule_common_root_page']]],
  ['garmvirttokenspaceguid_2epcddevicetreeallocationpadding',['gArmVirtTokenSpaceGuid.PcdDeviceTreeAllocationPadding',['../pcd__pcds_patchable_in_module_common__pcd_device_tree_allocation_padding.html',1,'pcd_PcdsPatchableInModule_common_root_page']]],
  ['garmvirttokenspaceguid_2epcddevicetreeinitialbaseaddress',['gArmVirtTokenSpaceGuid.PcdDeviceTreeInitialBaseAddress',['../pcd__pcds_patchable_in_module_common__pcd_device_tree_initial_base_address.html',1,'pcd_PcdsPatchableInModule_common_root_page']]],
  ['garmvirttokenspaceguid_2epcdterminaltypeguidbuffer',['gArmVirtTokenSpaceGuid.PcdTerminalTypeGuidBuffer',['../pcd__pcds_patchable_in_module_common__pcd_terminal_type_guid_buffer.html',1,'pcd_PcdsPatchableInModule_common_root_page']]]
];
