var annotated =
[
    [ "_ANDROID_BOOTIMG_PROTOCOL", "struct___a_n_d_r_o_i_d___b_o_o_t_i_m_g___p_r_o_t_o_c_o_l.html", "struct___a_n_d_r_o_i_d___b_o_o_t_i_m_g___p_r_o_t_o_c_o_l" ],
    [ "_EFI_HARDWARE_INTERRUPT2_PROTOCOL", "struct___e_f_i___h_a_r_d_w_a_r_e___i_n_t_e_r_r_u_p_t2___p_r_o_t_o_c_o_l.html", "struct___e_f_i___h_a_r_d_w_a_r_e___i_n_t_e_r_r_u_p_t2___p_r_o_t_o_c_o_l" ],
    [ "_EFI_HARDWARE_INTERRUPT_PROTOCOL", "struct___e_f_i___h_a_r_d_w_a_r_e___i_n_t_e_r_r_u_p_t___p_r_o_t_o_c_o_l.html", "struct___e_f_i___h_a_r_d_w_a_r_e___i_n_t_e_r_r_u_p_t___p_r_o_t_o_c_o_l" ],
    [ "_EFI_MMC_HOST_PROTOCOL", "struct___e_f_i___m_m_c___h_o_s_t___p_r_o_t_o_c_o_l.html", "struct___e_f_i___m_m_c___h_o_s_t___p_r_o_t_o_c_o_l" ],
    [ "_EMBEDDED_EXTERNAL_DEVICE", "struct___e_m_b_e_d_d_e_d___e_x_t_e_r_n_a_l___d_e_v_i_c_e.html", "struct___e_m_b_e_d_d_e_d___e_x_t_e_r_n_a_l___d_e_v_i_c_e" ],
    [ "_EMBEDDED_GPIO", "struct___e_m_b_e_d_d_e_d___g_p_i_o.html", "struct___e_m_b_e_d_d_e_d___g_p_i_o" ],
    [ "_EMBEDDED_GPIO_PPI", "struct___e_m_b_e_d_d_e_d___g_p_i_o___p_p_i.html", "struct___e_m_b_e_d_d_e_d___g_p_i_o___p_p_i" ],
    [ "_FASTBOOT_PLATFORM_PROTOCOL", "struct___f_a_s_t_b_o_o_t___p_l_a_t_f_o_r_m___p_r_o_t_o_c_o_l.html", "struct___f_a_s_t_b_o_o_t___p_l_a_t_f_o_r_m___p_r_o_t_o_c_o_l" ],
    [ "_FASTBOOT_TRANSPORT_PROTOCOL", "struct___f_a_s_t_b_o_o_t___t_r_a_n_s_p_o_r_t___p_r_o_t_o_c_o_l.html", "struct___f_a_s_t_b_o_o_t___t_r_a_n_s_p_o_r_t___p_r_o_t_o_c_o_l" ],
    [ "_FDT_CLIENT_PROTOCOL", "struct___f_d_t___c_l_i_e_n_t___p_r_o_t_o_c_o_l.html", "struct___f_d_t___c_l_i_e_n_t___p_r_o_t_o_c_o_l" ],
    [ "_GPIO_CONTROLLER", "struct___g_p_i_o___c_o_n_t_r_o_l_l_e_r.html", "struct___g_p_i_o___c_o_n_t_r_o_l_l_e_r" ],
    [ "_PE_COFF_LOADER_PROTOCOL", "struct___p_e___c_o_f_f___l_o_a_d_e_r___p_r_o_t_o_c_o_l.html", "struct___p_e___c_o_f_f___l_o_a_d_e_r___p_r_o_t_o_c_o_l" ],
    [ "_PLATFORM_BOOT_MANAGER_PROTOCOL", "struct___p_l_a_t_f_o_r_m___b_o_o_t___m_a_n_a_g_e_r___p_r_o_t_o_c_o_l.html", "struct___p_l_a_t_f_o_r_m___b_o_o_t___m_a_n_a_g_e_r___p_r_o_t_o_c_o_l" ],
    [ "_PLATFORM_GPIO_CONTROLLER", "struct___p_l_a_t_f_o_r_m___g_p_i_o___c_o_n_t_r_o_l_l_e_r.html", "struct___p_l_a_t_f_o_r_m___g_p_i_o___c_o_n_t_r_o_l_l_e_r" ],
    [ "_PLATFORM_VIRTUAL_KBD_PROTOCOL", "struct___p_l_a_t_f_o_r_m___v_i_r_t_u_a_l___k_b_d___p_r_o_t_o_c_o_l.html", "struct___p_l_a_t_f_o_r_m___v_i_r_t_u_a_l___k_b_d___p_r_o_t_o_c_o_l" ],
    [ "_USB_DEVICE_PROTOCOL", "struct___u_s_b___d_e_v_i_c_e___p_r_o_t_o_c_o_l.html", "struct___u_s_b___d_e_v_i_c_e___p_r_o_t_o_c_o_l" ],
    [ "_VIRTUAL_KBD_KEY", "struct___v_i_r_t_u_a_l___k_b_d___k_e_y.html", "struct___v_i_r_t_u_a_l___k_b_d___k_e_y" ],
    [ "ANDROID_BOOTIMG_HEADER", "struct_a_n_d_r_o_i_d___b_o_o_t_i_m_g___h_e_a_d_e_r.html", "struct_a_n_d_r_o_i_d___b_o_o_t_i_m_g___h_e_a_d_e_r" ],
    [ "EFI_OPEN_FILE", "struct_e_f_i___o_p_e_n___f_i_l_e.html", "struct_e_f_i___o_p_e_n___f_i_l_e" ],
    [ "EMBEDDED_DEVICE_PROTOCOL", "struct_e_m_b_e_d_d_e_d___d_e_v_i_c_e___p_r_o_t_o_c_o_l.html", "struct_e_m_b_e_d_d_e_d___d_e_v_i_c_e___p_r_o_t_o_c_o_l" ],
    [ "EXTRACT_SECTION_DATA", "struct_e_x_t_r_a_c_t___s_e_c_t_i_o_n___d_a_t_a.html", "struct_e_x_t_r_a_c_t___s_e_c_t_i_o_n___d_a_t_a" ],
    [ "EXTRACT_SECTION_HOB", "struct_e_x_t_r_a_c_t___s_e_c_t_i_o_n___h_o_b.html", "struct_e_x_t_r_a_c_t___s_e_c_t_i_o_n___h_o_b" ],
    [ "fdt_header", "structfdt__header.html", "structfdt__header" ],
    [ "fdt_node_header", "structfdt__node__header.html", "structfdt__node__header" ],
    [ "fdt_property", "structfdt__property.html", "structfdt__property" ],
    [ "fdt_reserve_entry", "structfdt__reserve__entry.html", "structfdt__reserve__entry" ],
    [ "NOR_FLASH_INFO", "struct_n_o_r___f_l_a_s_h___i_n_f_o.html", "struct_n_o_r___f_l_a_s_h___i_n_f_o" ]
];