var annotated =
[
    [ "ACPI_BOARD_INFO", "struct_a_c_p_i___b_o_a_r_d___i_n_f_o.html", "struct_a_c_p_i___b_o_a_r_d___i_n_f_o" ],
    [ "cb_cbmem_tab", "structcb__cbmem__tab.html", "structcb__cbmem__tab" ],
    [ "cb_console", "structcb__console.html", "structcb__console" ],
    [ "cb_forward", "structcb__forward.html", "structcb__forward" ],
    [ "cb_framebuffer", "structcb__framebuffer.html", "structcb__framebuffer" ],
    [ "cb_header", "structcb__header.html", "structcb__header" ],
    [ "cb_mainboard", "structcb__mainboard.html", "structcb__mainboard" ],
    [ "cb_memory", "structcb__memory.html", "structcb__memory" ],
    [ "cb_memory_range", "structcb__memory__range.html", "structcb__memory__range" ],
    [ "cb_record", "structcb__record.html", "structcb__record" ],
    [ "cb_serial", "structcb__serial.html", "structcb__serial" ],
    [ "cb_string", "structcb__string.html", "structcb__string" ],
    [ "cb_vdat", "structcb__vdat.html", "structcb__vdat" ],
    [ "cbmem_entry", "structcbmem__entry.html", "structcbmem__entry" ],
    [ "cbmem_root", "structcbmem__root.html", "structcbmem__root" ],
    [ "cbuint64", "structcbuint64.html", "structcbuint64" ],
    [ "CPU_SMMBASE", "struct_c_p_u___s_m_m_b_a_s_e.html", "struct_c_p_u___s_m_m_b_a_s_e" ],
    [ "imd_entry", "structimd__entry.html", "structimd__entry" ],
    [ "imd_root", "structimd__root.html", "structimd__root" ],
    [ "MEMORY_MAP_ENTRY", "struct_m_e_m_o_r_y___m_a_p___e_n_t_r_y.html", "struct_m_e_m_o_r_y___m_a_p___e_n_t_r_y" ],
    [ "MEMORY_MAP_INFO", "struct_m_e_m_o_r_y___m_a_p___i_n_f_o.html", "struct_m_e_m_o_r_y___m_a_p___i_n_f_o" ],
    [ "NV_VARIABLE_INFO", "struct_n_v___v_a_r_i_a_b_l_e___i_n_f_o.html", "struct_n_v___v_a_r_i_a_b_l_e___i_n_f_o" ],
    [ "PLD_GENERIC_REGISTER", "struct_p_l_d___g_e_n_e_r_i_c___r_e_g_i_s_t_e_r.html", "struct_p_l_d___g_e_n_e_r_i_c___r_e_g_i_s_t_e_r" ],
    [ "PLD_S3_COMMUNICATION", "struct_p_l_d___s3___c_o_m_m_u_n_i_c_a_t_i_o_n.html", "struct_p_l_d___s3___c_o_m_m_u_n_i_c_a_t_i_o_n" ],
    [ "PLD_SMM_REGISTERS", "struct_p_l_d___s_m_m___r_e_g_i_s_t_e_r_s.html", "struct_p_l_d___s_m_m___r_e_g_i_s_t_e_r_s" ],
    [ "PLD_TO_BL_SMM_INFO", "struct_p_l_d___t_o___b_l___s_m_m___i_n_f_o.html", "struct_p_l_d___t_o___b_l___s_m_m___i_n_f_o" ],
    [ "SERIAL_PORT_INFO", "struct_s_e_r_i_a_l___p_o_r_t___i_n_f_o.html", "struct_s_e_r_i_a_l___p_o_r_t___i_n_f_o" ],
    [ "SMM_S3_INFO", "struct_s_m_m___s3___i_n_f_o.html", "struct_s_m_m___s3___i_n_f_o" ],
    [ "SPI_FLASH_INFO", "struct_s_p_i___f_l_a_s_h___i_n_f_o.html", "struct_s_p_i___f_l_a_s_h___i_n_f_o" ],
    [ "UNIVERSAL_PAYLOAD_BOOT_MANAGER_MENU", "struct_u_n_i_v_e_r_s_a_l___p_a_y_l_o_a_d___b_o_o_t___m_a_n_a_g_e_r___m_e_n_u.html", "struct_u_n_i_v_e_r_s_a_l___p_a_y_l_o_a_d___b_o_o_t___m_a_n_a_g_e_r___m_e_n_u" ],
    [ "UNIVERSAL_PAYLOAD_PLATFORM_BOOT_MANAGER_OVERRIDE_PROTOCOL", "struct_u_n_i_v_e_r_s_a_l___p_a_y_l_o_a_d___p_l_a_t_f_o_r_m___b_o_o_t___m_a_n_a_g_e_r___o_v_e_r_r_i_d_e___p_r_o_t_o_c_o_l.html", "struct_u_n_i_v_e_r_s_a_l___p_a_y_l_o_a_d___p_l_a_t_f_o_r_m___b_o_o_t___m_a_n_a_g_e_r___o_v_e_r_r_i_d_e___p_r_o_t_o_c_o_l" ]
];