var annotated =
[
    [ "_SCMI_BASE_PROTOCOL", "struct___s_c_m_i___b_a_s_e___p_r_o_t_o_c_o_l.html", "struct___s_c_m_i___b_a_s_e___p_r_o_t_o_c_o_l" ],
    [ "_SCMI_CLOCK2_PROTOCOL", "struct___s_c_m_i___c_l_o_c_k2___p_r_o_t_o_c_o_l.html", "struct___s_c_m_i___c_l_o_c_k2___p_r_o_t_o_c_o_l" ],
    [ "_SCMI_CLOCK_PROTOCOL", "struct___s_c_m_i___c_l_o_c_k___p_r_o_t_o_c_o_l.html", "struct___s_c_m_i___c_l_o_c_k___p_r_o_t_o_c_o_l" ],
    [ "_SCMI_PERFORMANCE_PROTOCOL", "struct___s_c_m_i___p_e_r_f_o_r_m_a_n_c_e___p_r_o_t_o_c_o_l.html", "struct___s_c_m_i___p_e_r_f_o_r_m_a_n_c_e___p_r_o_t_o_c_o_l" ],
    [ "ARM_CORE_INFO", "struct_a_r_m___c_o_r_e___i_n_f_o.html", "struct_a_r_m___c_o_r_e___i_n_f_o" ],
    [ "ARM_HVC_ARGS", "struct_a_r_m___h_v_c___a_r_g_s.html", "struct_a_r_m___h_v_c___a_r_g_s" ],
    [ "ARM_MEMORY_REGION_DESCRIPTOR", "struct_a_r_m___m_e_m_o_r_y___r_e_g_i_o_n___d_e_s_c_r_i_p_t_o_r.html", "struct_a_r_m___m_e_m_o_r_y___r_e_g_i_o_n___d_e_s_c_r_i_p_t_o_r" ],
    [ "ARM_MP_CORE_INFO_PPI", "struct_a_r_m___m_p___c_o_r_e___i_n_f_o___p_p_i.html", "struct_a_r_m___m_p___c_o_r_e___i_n_f_o___p_p_i" ],
    [ "ARM_PROCESSOR_TABLE", "struct_a_r_m___p_r_o_c_e_s_s_o_r___t_a_b_l_e.html", "struct_a_r_m___p_r_o_c_e_s_s_o_r___t_a_b_l_e" ],
    [ "ARM_PROCESSOR_TABLE_HEADER", "struct_a_r_m___p_r_o_c_e_s_s_o_r___t_a_b_l_e___h_e_a_d_e_r.html", "struct_a_r_m___p_r_o_c_e_s_s_o_r___t_a_b_l_e___h_e_a_d_e_r" ],
    [ "ARM_SMC_ARGS", "struct_a_r_m___s_m_c___a_r_g_s.html", "struct_a_r_m___s_m_c___a_r_g_s" ],
    [ "ARM_SVC_ARGS", "struct_a_r_m___s_v_c___a_r_g_s.html", "struct_a_r_m___s_v_c___a_r_g_s" ],
    [ "CCSIDR2_DATA", "union_c_c_s_i_d_r2___d_a_t_a.html", "union_c_c_s_i_d_r2___d_a_t_a" ],
    [ "CCSIDR_DATA", "union_c_c_s_i_d_r___d_a_t_a.html", "union_c_c_s_i_d_r___d_a_t_a" ],
    [ "CLIDR_DATA", "union_c_l_i_d_r___d_a_t_a.html", "union_c_l_i_d_r___d_a_t_a" ],
    [ "CSSELR_DATA", "union_c_s_s_e_l_r___d_a_t_a.html", "union_c_s_s_e_l_r___d_a_t_a" ],
    [ "MTL_CHANNEL", "struct_m_t_l___c_h_a_n_n_e_l.html", "struct_m_t_l___c_h_a_n_n_e_l" ],
    [ "MTL_DOORBELL", "struct_m_t_l___d_o_o_r_b_e_l_l.html", "struct_m_t_l___d_o_o_r_b_e_l_l" ],
    [ "MTL_MAILBOX", "struct_m_t_l___m_a_i_l_b_o_x.html", "struct_m_t_l___m_a_i_l_b_o_x" ],
    [ "OEM_MISC_PROCESSOR_DATA", "struct_o_e_m___m_i_s_c___p_r_o_c_e_s_s_o_r___d_a_t_a.html", "struct_o_e_m___m_i_s_c___p_r_o_c_e_s_s_o_r___d_a_t_a" ],
    [ "OPTEE_INVOKE_FUNCTION_ARG", "struct_o_p_t_e_e___i_n_v_o_k_e___f_u_n_c_t_i_o_n___a_r_g.html", "struct_o_p_t_e_e___i_n_v_o_k_e___f_u_n_c_t_i_o_n___a_r_g" ],
    [ "OPTEE_MESSAGE_ARG", "struct_o_p_t_e_e___m_e_s_s_a_g_e___a_r_g.html", "struct_o_p_t_e_e___m_e_s_s_a_g_e___a_r_g" ],
    [ "OPTEE_MESSAGE_PARAM", "struct_o_p_t_e_e___m_e_s_s_a_g_e___p_a_r_a_m.html", "struct_o_p_t_e_e___m_e_s_s_a_g_e___p_a_r_a_m" ],
    [ "OPTEE_MESSAGE_PARAM_MEMORY", "struct_o_p_t_e_e___m_e_s_s_a_g_e___p_a_r_a_m___m_e_m_o_r_y.html", "struct_o_p_t_e_e___m_e_s_s_a_g_e___p_a_r_a_m___m_e_m_o_r_y" ],
    [ "OPTEE_MESSAGE_PARAM_UNION", "union_o_p_t_e_e___m_e_s_s_a_g_e___p_a_r_a_m___u_n_i_o_n.html", "union_o_p_t_e_e___m_e_s_s_a_g_e___p_a_r_a_m___u_n_i_o_n" ],
    [ "OPTEE_MESSAGE_PARAM_VALUE", "struct_o_p_t_e_e___m_e_s_s_a_g_e___p_a_r_a_m___v_a_l_u_e.html", "struct_o_p_t_e_e___m_e_s_s_a_g_e___p_a_r_a_m___v_a_l_u_e" ],
    [ "OPTEE_OPEN_SESSION_ARG", "struct_o_p_t_e_e___o_p_e_n___s_e_s_s_i_o_n___a_r_g.html", "struct_o_p_t_e_e___o_p_e_n___s_e_s_s_i_o_n___a_r_g" ],
    [ "SCMI_CLOCK_RATE", "union_s_c_m_i___c_l_o_c_k___r_a_t_e.html", "union_s_c_m_i___c_l_o_c_k___r_a_t_e" ],
    [ "SCMI_CLOCK_RATE_CONTINUOUS", "struct_s_c_m_i___c_l_o_c_k___r_a_t_e___c_o_n_t_i_n_u_o_u_s.html", "struct_s_c_m_i___c_l_o_c_k___r_a_t_e___c_o_n_t_i_n_u_o_u_s" ],
    [ "SCMI_CLOCK_RATE_DISCRETE", "struct_s_c_m_i___c_l_o_c_k___r_a_t_e___d_i_s_c_r_e_t_e.html", "struct_s_c_m_i___c_l_o_c_k___r_a_t_e___d_i_s_c_r_e_t_e" ],
    [ "SCMI_PERFORMANCE_DOMAIN_ATTRIBUTES", "struct_s_c_m_i___p_e_r_f_o_r_m_a_n_c_e___d_o_m_a_i_n___a_t_t_r_i_b_u_t_e_s.html", "struct_s_c_m_i___p_e_r_f_o_r_m_a_n_c_e___d_o_m_a_i_n___a_t_t_r_i_b_u_t_e_s" ],
    [ "SCMI_PERFORMANCE_LEVEL", "struct_s_c_m_i___p_e_r_f_o_r_m_a_n_c_e___l_e_v_e_l.html", "struct_s_c_m_i___p_e_r_f_o_r_m_a_n_c_e___l_e_v_e_l" ],
    [ "SCMI_PERFORMANCE_LIMITS", "struct_s_c_m_i___p_e_r_f_o_r_m_a_n_c_e___l_i_m_i_t_s.html", "struct_s_c_m_i___p_e_r_f_o_r_m_a_n_c_e___l_i_m_i_t_s" ],
    [ "SCMI_PERFORMANCE_PROTOCOL_ATTRIBUTES", "struct_s_c_m_i___p_e_r_f_o_r_m_a_n_c_e___p_r_o_t_o_c_o_l___a_t_t_r_i_b_u_t_e_s.html", "struct_s_c_m_i___p_e_r_f_o_r_m_a_n_c_e___p_r_o_t_o_c_o_l___a_t_t_r_i_b_u_t_e_s" ]
];