var _bluetooth_attribute_8h =
[
    [ "EFI_BLUETOOTH_UUID", "struct_e_f_i___b_l_u_e_t_o_o_t_h___u_u_i_d.html", "struct_e_f_i___b_l_u_e_t_o_o_t_h___u_u_i_d" ],
    [ "EFI_BLUETOOTH_ATTRIBUTE_PERMISSION", "union_e_f_i___b_l_u_e_t_o_o_t_h___a_t_t_r_i_b_u_t_e___p_e_r_m_i_s_s_i_o_n.html", "union_e_f_i___b_l_u_e_t_o_o_t_h___a_t_t_r_i_b_u_t_e___p_e_r_m_i_s_s_i_o_n" ],
    [ "EFI_BLUETOOTH_ATTRIBUTE_HEADER", "struct_e_f_i___b_l_u_e_t_o_o_t_h___a_t_t_r_i_b_u_t_e___h_e_a_d_e_r.html", "struct_e_f_i___b_l_u_e_t_o_o_t_h___a_t_t_r_i_b_u_t_e___h_e_a_d_e_r" ],
    [ "EFI_BLUETOOTH_GATT_PRIMARY_SERVICE_INFO", "struct_e_f_i___b_l_u_e_t_o_o_t_h___g_a_t_t___p_r_i_m_a_r_y___s_e_r_v_i_c_e___i_n_f_o.html", "struct_e_f_i___b_l_u_e_t_o_o_t_h___g_a_t_t___p_r_i_m_a_r_y___s_e_r_v_i_c_e___i_n_f_o" ],
    [ "EFI_BLUETOOTH_GATT_INCLUDE_SERVICE_INFO", "struct_e_f_i___b_l_u_e_t_o_o_t_h___g_a_t_t___i_n_c_l_u_d_e___s_e_r_v_i_c_e___i_n_f_o.html", "struct_e_f_i___b_l_u_e_t_o_o_t_h___g_a_t_t___i_n_c_l_u_d_e___s_e_r_v_i_c_e___i_n_f_o" ],
    [ "EFI_BLUETOOTH_GATT_CHARACTERISTIC_INFO", "struct_e_f_i___b_l_u_e_t_o_o_t_h___g_a_t_t___c_h_a_r_a_c_t_e_r_i_s_t_i_c___i_n_f_o.html", "struct_e_f_i___b_l_u_e_t_o_o_t_h___g_a_t_t___c_h_a_r_a_c_t_e_r_i_s_t_i_c___i_n_f_o" ],
    [ "EFI_BLUETOOTH_GATT_CHARACTERISTIC_DESCRIPTOR_INFO", "struct_e_f_i___b_l_u_e_t_o_o_t_h___g_a_t_t___c_h_a_r_a_c_t_e_r_i_s_t_i_c___d_e_s_c_r_i_p_t_o_r___i_n_f_o.html", "struct_e_f_i___b_l_u_e_t_o_o_t_h___g_a_t_t___c_h_a_r_a_c_t_e_r_i_s_t_i_c___d_e_s_c_r_i_p_t_o_r___i_n_f_o" ],
    [ "EFI_BLUETOOTH_ATTRIBUTE_CALLBACK_PARAMETER_NOTIFICATION", "struct_e_f_i___b_l_u_e_t_o_o_t_h___a_t_t_r_i_b_u_t_e___c_a_l_l_b_a_c_k___p_a_r_a_m_e_t_e_r___n_o_t_i_f_i_c_a_t_i_o_n.html", "struct_e_f_i___b_l_u_e_t_o_o_t_h___a_t_t_r_i_b_u_t_e___c_a_l_l_b_a_c_k___p_a_r_a_m_e_t_e_r___n_o_t_i_f_i_c_a_t_i_o_n" ],
    [ "EFI_BLUETOOTH_ATTRIBUTE_CALLBACK_PARAMETER_INDICATION", "struct_e_f_i___b_l_u_e_t_o_o_t_h___a_t_t_r_i_b_u_t_e___c_a_l_l_b_a_c_k___p_a_r_a_m_e_t_e_r___i_n_d_i_c_a_t_i_o_n.html", "struct_e_f_i___b_l_u_e_t_o_o_t_h___a_t_t_r_i_b_u_t_e___c_a_l_l_b_a_c_k___p_a_r_a_m_e_t_e_r___i_n_d_i_c_a_t_i_o_n" ],
    [ "EFI_BLUETOOTH_ATTRIBUTE_CALLBACK_PARAMETER", "struct_e_f_i___b_l_u_e_t_o_o_t_h___a_t_t_r_i_b_u_t_e___c_a_l_l_b_a_c_k___p_a_r_a_m_e_t_e_r.html", "struct_e_f_i___b_l_u_e_t_o_o_t_h___a_t_t_r_i_b_u_t_e___c_a_l_l_b_a_c_k___p_a_r_a_m_e_t_e_r" ],
    [ "EFI_BLUETOOTH_LE_DEVICE_INFO", "struct_e_f_i___b_l_u_e_t_o_o_t_h___l_e___d_e_v_i_c_e___i_n_f_o.html", "struct_e_f_i___b_l_u_e_t_o_o_t_h___l_e___d_e_v_i_c_e___i_n_f_o" ],
    [ "_EFI_BLUETOOTH_ATTRIBUTE_PROTOCOL", "struct___e_f_i___b_l_u_e_t_o_o_t_h___a_t_t_r_i_b_u_t_e___p_r_o_t_o_c_o_l.html", "struct___e_f_i___b_l_u_e_t_o_o_t_h___a_t_t_r_i_b_u_t_e___p_r_o_t_o_c_o_l" ],
    [ "BLUETOOTH_IS_ATTRIBUTE_OF_TYPE", "_bluetooth_attribute_8h.html#ae32370ebe27088319f231f2e8abdb3b6", null ],
    [ "EFI_BLUETOOTH_ATTRIBUTE_PROTOCOL_GUID", "_bluetooth_attribute_8h.html#a62bd7d31ee104a84762a0e159e83cb27", null ],
    [ "EFI_BLUETOOTH_ATTRIBUTE_SERVICE_BINDING_PROTOCOL_GUID", "_bluetooth_attribute_8h.html#ae5e7a333e5ff8a71f54632de4d1e036b", null ],
    [ "UUID_128BIT_TYPE_LEN", "_bluetooth_attribute_8h.html#a1bfbc4dc52da34ff0ba78d2807bb9ccd", null ],
    [ "UUID_16BIT_TYPE_LEN", "_bluetooth_attribute_8h.html#a01755027ef76af7c14636b9c907f74c8", null ],
    [ "UUID_32BIT_TYPE_LEN", "_bluetooth_attribute_8h.html#ae2656a17fb417c304abf46cf64f30e26", null ],
    [ "Callback", "_bluetooth_attribute_8h.html#afa8e78340005a64bef065c3594703008", null ],
    [ "Context", "_bluetooth_attribute_8h.html#a07b3b9677edaa71524b96a937303a76e", null ],
    [ "Data", "_bluetooth_attribute_8h.html#a631f90ab849a9595f244467e1598aca0", null ],
    [ "DataLength", "_bluetooth_attribute_8h.html#acb51d175d6f6302150f796dac07a5325", null ],
    [ "EFI_BLUETOOTH_ATTRIBUTE_GET_DEVICE_INFO", "_bluetooth_attribute_8h.html#af88845ccae0f21260a9d3a40e13e2d3f", null ],
    [ "EFI_BLUETOOTH_ATTRIBUTE_GET_SERVICE_INFO", "_bluetooth_attribute_8h.html#ac4c3bdb556f3baf599e88210821130a4", null ],
    [ "EFI_BLUETOOTH_ATTRIBUTE_PROTOCOL", "_bluetooth_attribute_8h.html#a826678289ed81e9cc43c8e74d8903c33", null ],
    [ "EFI_BLUETOOTH_ATTRIBUTE_REGISTER_FOR_SERVER_NOTIFICATION", "_bluetooth_attribute_8h.html#a1903e7df3c230de3b6e1dfbd33b65647", null ],
    [ "EFI_STATUS", "_bluetooth_attribute_8h.html#a8bbba6cd4f2ed6ecc8b4e09b4e6f84a1", null ],
    [ "gEfiBluetoothAttributeProtocolGuid", "_bluetooth_attribute_8h.html#ad6ed4875a89f1ad22bb73ad4f76a2907", null ],
    [ "gEfiBluetoothAttributeServiceBindingProtocolGuid", "_bluetooth_attribute_8h.html#a5eb72cbdd48316070388bad574695044", null ]
];