var _dma_remapping_reporting_table_8h =
[
    [ "EFI_ACPI_DMAR_STRUCTURE_HEADER", "struct_e_f_i___a_c_p_i___d_m_a_r___s_t_r_u_c_t_u_r_e___h_e_a_d_e_r.html", "struct_e_f_i___a_c_p_i___d_m_a_r___s_t_r_u_c_t_u_r_e___h_e_a_d_e_r" ],
    [ "EFI_ACPI_DMAR_PCI_PATH", "struct_e_f_i___a_c_p_i___d_m_a_r___p_c_i___p_a_t_h.html", "struct_e_f_i___a_c_p_i___d_m_a_r___p_c_i___p_a_t_h" ],
    [ "EFI_ACPI_DMAR_DEVICE_SCOPE_STRUCTURE_HEADER", "struct_e_f_i___a_c_p_i___d_m_a_r___d_e_v_i_c_e___s_c_o_p_e___s_t_r_u_c_t_u_r_e___h_e_a_d_e_r.html", "struct_e_f_i___a_c_p_i___d_m_a_r___d_e_v_i_c_e___s_c_o_p_e___s_t_r_u_c_t_u_r_e___h_e_a_d_e_r" ],
    [ "EFI_ACPI_DMAR_DRHD_HEADER", "struct_e_f_i___a_c_p_i___d_m_a_r___d_r_h_d___h_e_a_d_e_r.html", "struct_e_f_i___a_c_p_i___d_m_a_r___d_r_h_d___h_e_a_d_e_r" ],
    [ "EFI_ACPI_DMAR_RMRR_HEADER", "struct_e_f_i___a_c_p_i___d_m_a_r___r_m_r_r___h_e_a_d_e_r.html", "struct_e_f_i___a_c_p_i___d_m_a_r___r_m_r_r___h_e_a_d_e_r" ],
    [ "EFI_ACPI_DMAR_ATSR_HEADER", "struct_e_f_i___a_c_p_i___d_m_a_r___a_t_s_r___h_e_a_d_e_r.html", "struct_e_f_i___a_c_p_i___d_m_a_r___a_t_s_r___h_e_a_d_e_r" ],
    [ "EFI_ACPI_DMAR_RHSA_HEADER", "struct_e_f_i___a_c_p_i___d_m_a_r___r_h_s_a___h_e_a_d_e_r.html", "struct_e_f_i___a_c_p_i___d_m_a_r___r_h_s_a___h_e_a_d_e_r" ],
    [ "EFI_ACPI_DMAR_ANDD_HEADER", "struct_e_f_i___a_c_p_i___d_m_a_r___a_n_d_d___h_e_a_d_e_r.html", "struct_e_f_i___a_c_p_i___d_m_a_r___a_n_d_d___h_e_a_d_e_r" ],
    [ "EFI_ACPI_DMAR_SATC_HEADER", "struct_e_f_i___a_c_p_i___d_m_a_r___s_a_t_c___h_e_a_d_e_r.html", "struct_e_f_i___a_c_p_i___d_m_a_r___s_a_t_c___h_e_a_d_e_r" ],
    [ "EFI_ACPI_DMAR_HEADER", "struct_e_f_i___a_c_p_i___d_m_a_r___h_e_a_d_e_r.html", "struct_e_f_i___a_c_p_i___d_m_a_r___h_e_a_d_e_r" ],
    [ "EFI_ACPI_DEVICE_SCOPE_ENTRY_TYPE_ACPI_NAMESPACE_DEVICE", "_dma_remapping_reporting_table_8h.html#a0ab5893a160c4ec4489c900c03493d1f", null ],
    [ "EFI_ACPI_DEVICE_SCOPE_ENTRY_TYPE_IOAPIC", "_dma_remapping_reporting_table_8h.html#aa9d91d804501f5933fd488ac7c1480c9", null ],
    [ "EFI_ACPI_DEVICE_SCOPE_ENTRY_TYPE_MSI_CAPABLE_HPET", "_dma_remapping_reporting_table_8h.html#a24639503909b45bb683562c1c7861d97", null ],
    [ "EFI_ACPI_DEVICE_SCOPE_ENTRY_TYPE_PCI_BRIDGE", "_dma_remapping_reporting_table_8h.html#afb9a05f30803e2e83e28b35e9f50ad23", null ],
    [ "EFI_ACPI_DEVICE_SCOPE_ENTRY_TYPE_PCI_ENDPOINT", "_dma_remapping_reporting_table_8h.html#aff857982e8fa20cf56cec58518776048", null ],
    [ "EFI_ACPI_DMAR_ATSR_FLAGS_ALL_PORTS", "_dma_remapping_reporting_table_8h.html#a4a33c92e5423b35418526f2562c14e6e", null ],
    [ "EFI_ACPI_DMAR_DRHD_FLAGS_INCLUDE_PCI_ALL", "_dma_remapping_reporting_table_8h.html#ab18f27c404848c9a3bbfc073883e5da2", null ],
    [ "EFI_ACPI_DMAR_FLAGS_DMA_CTRL_PLATFORM_OPT_IN_FLAG", "_dma_remapping_reporting_table_8h.html#a7abfafcdbcae46e02f3e51bb30650573", null ],
    [ "EFI_ACPI_DMAR_FLAGS_INTR_REMAP", "_dma_remapping_reporting_table_8h.html#a8a667bd8a70885f41635c415c6132dcf", null ],
    [ "EFI_ACPI_DMAR_FLAGS_X2APIC_OPT_OUT", "_dma_remapping_reporting_table_8h.html#a44724e23a4cc3c78afe26afddce59b3d", null ],
    [ "EFI_ACPI_DMAR_REVISION", "_dma_remapping_reporting_table_8h.html#a0a6fa36e9647d8bd41d32edcd4737d29", null ],
    [ "EFI_ACPI_DMAR_TYPE_ANDD", "_dma_remapping_reporting_table_8h.html#a119cebf3677638ed503adf2e47d7d722", null ],
    [ "EFI_ACPI_DMAR_TYPE_ATSR", "_dma_remapping_reporting_table_8h.html#ab081b8c8a02b3b944144d45e8635c82a", null ],
    [ "EFI_ACPI_DMAR_TYPE_DRHD", "_dma_remapping_reporting_table_8h.html#ad341c0f5dfa3702c989c8ab219d71adf", null ],
    [ "EFI_ACPI_DMAR_TYPE_RHSA", "_dma_remapping_reporting_table_8h.html#a3a5fdbb763c9f14b53d89646d4e020d4", null ],
    [ "EFI_ACPI_DMAR_TYPE_RMRR", "_dma_remapping_reporting_table_8h.html#a06c0ecf02dc2c8ea86d237bb91cdfff7", null ],
    [ "EFI_ACPI_DMAR_TYPE_SATC", "_dma_remapping_reporting_table_8h.html#ad44f4d4c22f06049001e8b84de5ee2b7", null ]
];