var _pci_express50_8h =
[
    [ "PCI_EXPRESS_REG_PHYSICAL_LAYER_32_0_CAPABILITIES", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___c_a_p_a_b_i_l_i_t_i_e_s.html", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___c_a_p_a_b_i_l_i_t_i_e_s" ],
    [ "PCI_EXPRESS_REG_PHYSICAL_LAYER_32_0_CONTROL", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___c_o_n_t_r_o_l.html", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___c_o_n_t_r_o_l" ],
    [ "PCI_EXPRESS_REG_PHYSICAL_LAYER_32_0_STATUS", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___s_t_a_t_u_s.html", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___s_t_a_t_u_s" ],
    [ "PCI_EXPRESS_REG_PHYSICAL_LAYER_32_0_RCVD_MODIFIED_TS_DATA1", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___r_c_v_d___m_o_d_i_f_i_e_d___t_s___d_a_t_a1.html", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___r_c_v_d___m_o_d_i_f_i_e_d___t_s___d_a_t_a1" ],
    [ "PCI_EXPRESS_REG_PHYSICAL_LAYER_32_0_RCVD_MODIFIED_TS_DATA2", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___r_c_v_d___m_o_d_i_f_i_e_d___t_s___d_a_t_a2.html", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___r_c_v_d___m_o_d_i_f_i_e_d___t_s___d_a_t_a2" ],
    [ "PCI_EXPRESS_REG_PHYSICAL_LAYER_32_0_TRANS_MODIFIED_TS_DATA1", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___t_r_a_n_s___m_o_d_i_f_i_e_d___t_s___d_a_t_a1.html", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___t_r_a_n_s___m_o_d_i_f_i_e_d___t_s___d_a_t_a1" ],
    [ "PCI_EXPRESS_REG_PHYSICAL_LAYER_32_0_TRANS_MODIFIED_TS_DATA2", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___t_r_a_n_s___m_o_d_i_f_i_e_d___t_s___d_a_t_a2.html", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___t_r_a_n_s___m_o_d_i_f_i_e_d___t_s___d_a_t_a2" ],
    [ "PCI_EXPRESS_REG_PHYSICAL_LAYER_32_0_LANE_EQUALIZATION_CONTROL", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___l_a_n_e___e_q_u_a_l_i_z_a_t_i_o_n___c_o_n_t_r_o_l.html", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___l_a_n_e___e_q_u_a_l_i_z_a_t_i_o_n___c_o_n_t_r_o_l" ],
    [ "PCI_EXPRESS_EXTENDED_CAPABILITIES_PHYSICAL_LAYER_32_0", "struct_p_c_i___e_x_p_r_e_s_s___e_x_t_e_n_d_e_d___c_a_p_a_b_i_l_i_t_i_e_s___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0.html", "struct_p_c_i___e_x_p_r_e_s_s___e_x_t_e_n_d_e_d___c_a_p_a_b_i_l_i_t_i_e_s___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0" ],
    [ "PCI_EXPRESS_EXTENDED_CAPABILITY_PHYSICAL_LAYER_32_0_ID", "_pci_express50_8h.html#a412d9979709e9d4d350190bb10dc334c", null ],
    [ "PCI_EXPRESS_EXTENDED_CAPABILITY_PHYSICAL_LAYER_32_0_VER1", "_pci_express50_8h.html#a95ac01625e2d2dd93372a6374c171e0b", null ],
    [ "PCI_EXPRESS_REG_PHYSICAL_LAYER_32_0_CAPABILITIES_OFFSET", "_pci_express50_8h.html#a9e02040fc6579357e80305357c21368a", null ],
    [ "PCI_EXPRESS_REG_PHYSICAL_LAYER_32_0_CONTROL_OFFSET", "_pci_express50_8h.html#a35966b199d73b4c81e666054663d3c05", null ],
    [ "PCI_EXPRESS_REG_PHYSICAL_LAYER_32_0_LANE_EQUALIZATION_CONTROL_OFFSET", "_pci_express50_8h.html#a6d9a4170b098313af1d91010e9d15b7b", null ],
    [ "PCI_EXPRESS_REG_PHYSICAL_LAYER_32_0_RCVD_MODIFIED_TS_DATA1_OFFSET", "_pci_express50_8h.html#a2b8ed9747751cec8518872d32592393f", null ],
    [ "PCI_EXPRESS_REG_PHYSICAL_LAYER_32_0_RCVD_MODIFIED_TS_DATA2_OFFSET", "_pci_express50_8h.html#add53df970e1c3446a2a0e5a5e2cc7e53", null ],
    [ "PCI_EXPRESS_REG_PHYSICAL_LAYER_32_0_STATUS_OFFSET", "_pci_express50_8h.html#a1bd198ced94b02912beb11054199fb91", null ],
    [ "PCI_EXPRESS_REG_PHYSICAL_LAYER_32_0_TRANS_MODIFIED_TS_DATA1_OFFSET", "_pci_express50_8h.html#abdd7017a678ff609b12a89933687ad5d", null ],
    [ "PCI_EXPRESS_REG_PHYSICAL_LAYER_32_0_TRANS_MODIFIED_TS_DATA2_OFFSET", "_pci_express50_8h.html#a80dad6e03da68dc59fd5893402c34cd4", null ]
];