var struct_e_f_i___a_c_p_i__6__2___h_e_t_e_r_o_g_e_n_e_o_u_s___m_e_m_o_r_y___a_t_t_r_i_b_u_t_e___t_a_b_l_e___h_e_a_d_e_r =
[
    [ "Header", "struct_e_f_i___a_c_p_i__6__2___h_e_t_e_r_o_g_e_n_e_o_u_s___m_e_m_o_r_y___a_t_t_r_i_b_u_t_e___t_a_b_l_e___h_e_a_d_e_r.html#ac858b6604d27739ecdd757d15deff724", null ],
    [ "Reserved", "struct_e_f_i___a_c_p_i__6__2___h_e_t_e_r_o_g_e_n_e_o_u_s___m_e_m_o_r_y___a_t_t_r_i_b_u_t_e___t_a_b_l_e___h_e_a_d_e_r.html#aac545b8705e15d7a4c05f03c1c17eda8", null ]
];