var struct_e_f_i___a_c_p_i__6__1___p_m_m_t___s_o_c_k_e_t___m_e_m_o_r_y___a_g_g_r_e_g_a_t_o_r___d_e_v_i_c_e___s_t_r_u_c_t_u_r_e =
[
    [ "Header", "struct_e_f_i___a_c_p_i__6__1___p_m_m_t___s_o_c_k_e_t___m_e_m_o_r_y___a_g_g_r_e_g_a_t_o_r___d_e_v_i_c_e___s_t_r_u_c_t_u_r_e.html#a85b91dd7c4b8747b60eea45795699beb", null ],
    [ "Reserved", "struct_e_f_i___a_c_p_i__6__1___p_m_m_t___s_o_c_k_e_t___m_e_m_o_r_y___a_g_g_r_e_g_a_t_o_r___d_e_v_i_c_e___s_t_r_u_c_t_u_r_e.html#a45d5fdf9f38b0e57badc60d2c572178d", null ],
    [ "SocketIdentifier", "struct_e_f_i___a_c_p_i__6__1___p_m_m_t___s_o_c_k_e_t___m_e_m_o_r_y___a_g_g_r_e_g_a_t_o_r___d_e_v_i_c_e___s_t_r_u_c_t_u_r_e.html#abfa6025e77d691a4d2b37cab3d6ddbf0", null ]
];