var struct_e_f_i___a_c_p_i__6__2___p_m_m_t___s_o_c_k_e_t___m_e_m_o_r_y___a_g_g_r_e_g_a_t_o_r___d_e_v_i_c_e___s_t_r_u_c_t_u_r_e =
[
    [ "Header", "struct_e_f_i___a_c_p_i__6__2___p_m_m_t___s_o_c_k_e_t___m_e_m_o_r_y___a_g_g_r_e_g_a_t_o_r___d_e_v_i_c_e___s_t_r_u_c_t_u_r_e.html#afa75bcd665775f1274bf75618a0166f6", null ],
    [ "Reserved", "struct_e_f_i___a_c_p_i__6__2___p_m_m_t___s_o_c_k_e_t___m_e_m_o_r_y___a_g_g_r_e_g_a_t_o_r___d_e_v_i_c_e___s_t_r_u_c_t_u_r_e.html#adb91d93930532167e12156ad1fb711c9", null ],
    [ "SocketIdentifier", "struct_e_f_i___a_c_p_i__6__2___p_m_m_t___s_o_c_k_e_t___m_e_m_o_r_y___a_g_g_r_e_g_a_t_o_r___d_e_v_i_c_e___s_t_r_u_c_t_u_r_e.html#a63eb479bfb0e55b5100ee50ff47bceaf", null ]
];