var struct_e_f_i___b_l_u_e_t_o_o_t_h___g_a_t_t___c_h_a_r_a_c_t_e_r_i_s_t_i_c___d_e_s_c_r_i_p_t_o_r___i_n_f_o =
[
    [ "CharacteristicDescriptorUuid", "struct_e_f_i___b_l_u_e_t_o_o_t_h___g_a_t_t___c_h_a_r_a_c_t_e_r_i_s_t_i_c___d_e_s_c_r_i_p_t_o_r___i_n_f_o.html#a7a0e747357b6efd739d71ebf4b80585a", null ],
    [ "Header", "struct_e_f_i___b_l_u_e_t_o_o_t_h___g_a_t_t___c_h_a_r_a_c_t_e_r_i_s_t_i_c___d_e_s_c_r_i_p_t_o_r___i_n_f_o.html#ab53f952bc0b71836617aad799a426aa0", null ]
];