var struct_e_f_i___a_c_p_i__6__0___m_p_s_t___m_e_m_o_r_y___p_o_w_e_r___s_t_a_t_e___c_h_a_r_a_c_t_e_r_i_s_t_i_c_s___t_a_b_l_e =
[
    [ "MemoryPowerStateCharacteristicsCount", "struct_e_f_i___a_c_p_i__6__0___m_p_s_t___m_e_m_o_r_y___p_o_w_e_r___s_t_a_t_e___c_h_a_r_a_c_t_e_r_i_s_t_i_c_s___t_a_b_l_e.html#a8c74bbb3755eb880031938c1c8ddcddf", null ],
    [ "Reserved", "struct_e_f_i___a_c_p_i__6__0___m_p_s_t___m_e_m_o_r_y___p_o_w_e_r___s_t_a_t_e___c_h_a_r_a_c_t_e_r_i_s_t_i_c_s___t_a_b_l_e.html#a6899da616a067c515a30a0c277d1433f", null ]
];