var struct___e_f_i___i2_c___b_u_s___c_o_n_f_i_g_u_r_a_t_i_o_n___m_a_n_a_g_e_m_e_n_t___p_r_o_t_o_c_o_l =
[
    [ "EnableI2cBusConfiguration", "struct___e_f_i___i2_c___b_u_s___c_o_n_f_i_g_u_r_a_t_i_o_n___m_a_n_a_g_e_m_e_n_t___p_r_o_t_o_c_o_l.html#a320869d22d7bf878f8ccbdd6f19c251f", null ]
];