var struct_e_f_i___a_c_p_i__5__1___p_m_m_t___s_o_c_k_e_t___m_e_m_o_r_y___a_g_g_r_e_g_a_t_o_r___d_e_v_i_c_e___s_t_r_u_c_t_u_r_e =
[
    [ "Header", "struct_e_f_i___a_c_p_i__5__1___p_m_m_t___s_o_c_k_e_t___m_e_m_o_r_y___a_g_g_r_e_g_a_t_o_r___d_e_v_i_c_e___s_t_r_u_c_t_u_r_e.html#aee2738874beac5925b97cb8e67d60589", null ],
    [ "Reserved", "struct_e_f_i___a_c_p_i__5__1___p_m_m_t___s_o_c_k_e_t___m_e_m_o_r_y___a_g_g_r_e_g_a_t_o_r___d_e_v_i_c_e___s_t_r_u_c_t_u_r_e.html#ac5c349d6f3a380f8da62ff8c8ee88428", null ],
    [ "SocketIdentifier", "struct_e_f_i___a_c_p_i__5__1___p_m_m_t___s_o_c_k_e_t___m_e_m_o_r_y___a_g_g_r_e_g_a_t_o_r___d_e_v_i_c_e___s_t_r_u_c_t_u_r_e.html#aff09e27e8284e8a1bba7e8ed494c82f8", null ]
];