var struct_e_f_i___b_l_o_c_k___i_o___c_r_y_p_t_o___i_v___i_n_p_u_t___a_e_s___c_b_c___m_i_c_r_o_s_o_f_t___b_i_t_l_o_c_k_e_r =
[
    [ "CryptoBlockByteOffset", "struct_e_f_i___b_l_o_c_k___i_o___c_r_y_p_t_o___i_v___i_n_p_u_t___a_e_s___c_b_c___m_i_c_r_o_s_o_f_t___b_i_t_l_o_c_k_e_r.html#a4b1d2f55b2ac767b115292e4c4fb7f01", null ],
    [ "CryptoBlockByteSize", "struct_e_f_i___b_l_o_c_k___i_o___c_r_y_p_t_o___i_v___i_n_p_u_t___a_e_s___c_b_c___m_i_c_r_o_s_o_f_t___b_i_t_l_o_c_k_e_r.html#ab682511fc9965a05a99e015b72714803", null ],
    [ "Header", "struct_e_f_i___b_l_o_c_k___i_o___c_r_y_p_t_o___i_v___i_n_p_u_t___a_e_s___c_b_c___m_i_c_r_o_s_o_f_t___b_i_t_l_o_c_k_e_r.html#a77cfe28f384380f98347821e5f3e1c8d", null ]
];