var struct_e_f_i___a_c_p_i__6__1___n_f_i_t___s_m_b_i_o_s___m_a_n_a_g_e_m_e_n_t___i_n_f_o_r_m_a_t_i_o_n___s_t_r_u_c_t_u_r_e =
[
    [ "Length", "struct_e_f_i___a_c_p_i__6__1___n_f_i_t___s_m_b_i_o_s___m_a_n_a_g_e_m_e_n_t___i_n_f_o_r_m_a_t_i_o_n___s_t_r_u_c_t_u_r_e.html#af6e803c5341191d89790bd9d322c72fc", null ],
    [ "Reserved_4", "struct_e_f_i___a_c_p_i__6__1___n_f_i_t___s_m_b_i_o_s___m_a_n_a_g_e_m_e_n_t___i_n_f_o_r_m_a_t_i_o_n___s_t_r_u_c_t_u_r_e.html#a48adccb84db71ec5284a700f1b28cf63", null ],
    [ "Type", "struct_e_f_i___a_c_p_i__6__1___n_f_i_t___s_m_b_i_o_s___m_a_n_a_g_e_m_e_n_t___i_n_f_o_r_m_a_t_i_o_n___s_t_r_u_c_t_u_r_e.html#a53f08506babddadaf9b6fe3c4636b718", null ]
];