var struct_p_c_i___e_x_p_r_e_s_s___e_x_t_e_n_d_e_d___c_a_p_a_b_i_l_i_t_i_e_s___v_i_r_t_u_a_l___c_h_a_n_n_e_l___c_a_p_a_b_i_l_i_t_y =
[
    [ "Capability", "struct_p_c_i___e_x_p_r_e_s_s___e_x_t_e_n_d_e_d___c_a_p_a_b_i_l_i_t_i_e_s___v_i_r_t_u_a_l___c_h_a_n_n_e_l___c_a_p_a_b_i_l_i_t_y.html#a81b3a42e197e2c15640fda76afa1509a", null ],
    [ "ExtendedVcCount", "struct_p_c_i___e_x_p_r_e_s_s___e_x_t_e_n_d_e_d___c_a_p_a_b_i_l_i_t_i_e_s___v_i_r_t_u_a_l___c_h_a_n_n_e_l___c_a_p_a_b_i_l_i_t_y.html#a378b6843590ae253adde6c7fd865e03f", null ],
    [ "Header", "struct_p_c_i___e_x_p_r_e_s_s___e_x_t_e_n_d_e_d___c_a_p_a_b_i_l_i_t_i_e_s___v_i_r_t_u_a_l___c_h_a_n_n_e_l___c_a_p_a_b_i_l_i_t_y.html#a97fb6386497394224bad13a85e45713b", null ],
    [ "PortVcCapability1", "struct_p_c_i___e_x_p_r_e_s_s___e_x_t_e_n_d_e_d___c_a_p_a_b_i_l_i_t_i_e_s___v_i_r_t_u_a_l___c_h_a_n_n_e_l___c_a_p_a_b_i_l_i_t_y.html#abb36173e30f5f144f94fddf237507724", null ],
    [ "PortVcCapability2", "struct_p_c_i___e_x_p_r_e_s_s___e_x_t_e_n_d_e_d___c_a_p_a_b_i_l_i_t_i_e_s___v_i_r_t_u_a_l___c_h_a_n_n_e_l___c_a_p_a_b_i_l_i_t_y.html#ae5fa9ab7357d3df8adaac03dd1ab3367", null ],
    [ "PortVcControl", "struct_p_c_i___e_x_p_r_e_s_s___e_x_t_e_n_d_e_d___c_a_p_a_b_i_l_i_t_i_e_s___v_i_r_t_u_a_l___c_h_a_n_n_e_l___c_a_p_a_b_i_l_i_t_y.html#ad14ac1297f069adf14aa2e2166bb22c9", null ],
    [ "PortVcStatus", "struct_p_c_i___e_x_p_r_e_s_s___e_x_t_e_n_d_e_d___c_a_p_a_b_i_l_i_t_i_e_s___v_i_r_t_u_a_l___c_h_a_n_n_e_l___c_a_p_a_b_i_l_i_t_y.html#a822a3711cf3edd0c01ffa7b11bf74c72", null ],
    [ "VcArbTableOffset", "struct_p_c_i___e_x_p_r_e_s_s___e_x_t_e_n_d_e_d___c_a_p_a_b_i_l_i_t_i_e_s___v_i_r_t_u_a_l___c_h_a_n_n_e_l___c_a_p_a_b_i_l_i_t_y.html#aaf1dab321a9d96f7a9d6d7c597ea0345", null ]
];