var struct_e_f_i___a_c_p_i__6__0___f_p_d_t___b_o_o_t___p_e_r_f_o_r_m_a_n_c_e___t_a_b_l_e___p_o_i_n_t_e_r___r_e_c_o_r_d =
[
    [ "BootPerformanceTablePointer", "struct_e_f_i___a_c_p_i__6__0___f_p_d_t___b_o_o_t___p_e_r_f_o_r_m_a_n_c_e___t_a_b_l_e___p_o_i_n_t_e_r___r_e_c_o_r_d.html#a64ae2b0ebbcf1dc3e0e2fed1b0c82bfb", null ],
    [ "Header", "struct_e_f_i___a_c_p_i__6__0___f_p_d_t___b_o_o_t___p_e_r_f_o_r_m_a_n_c_e___t_a_b_l_e___p_o_i_n_t_e_r___r_e_c_o_r_d.html#a136c4a20a9f582651d96dbb7dd8da78c", null ],
    [ "Reserved", "struct_e_f_i___a_c_p_i__6__0___f_p_d_t___b_o_o_t___p_e_r_f_o_r_m_a_n_c_e___t_a_b_l_e___p_o_i_n_t_e_r___r_e_c_o_r_d.html#a0f5a8e167355db9ba38ba0ccfdbcdab9", null ]
];