var struct___e_f_i___i_n_c_o_m_p_a_t_i_b_l_e___p_c_i___d_e_v_i_c_e___s_u_p_p_o_r_t___p_r_o_t_o_c_o_l =
[
    [ "CheckDevice", "struct___e_f_i___i_n_c_o_m_p_a_t_i_b_l_e___p_c_i___d_e_v_i_c_e___s_u_p_p_o_r_t___p_r_o_t_o_c_o_l.html#aa89236756e2b2ffff3b540ef4b820a35", null ]
];