var struct_e_f_i___a_c_p_i__6__3___c_o_r_r_e_c_t_e_d___p_l_a_t_f_o_r_m___e_r_r_o_r___p_o_l_l_i_n_g___t_a_b_l_e___h_e_a_d_e_r =
[
    [ "Header", "struct_e_f_i___a_c_p_i__6__3___c_o_r_r_e_c_t_e_d___p_l_a_t_f_o_r_m___e_r_r_o_r___p_o_l_l_i_n_g___t_a_b_l_e___h_e_a_d_e_r.html#a5f8fd5facabb2615b4326ea3184ee924", null ],
    [ "Reserved", "struct_e_f_i___a_c_p_i__6__3___c_o_r_r_e_c_t_e_d___p_l_a_t_f_o_r_m___e_r_r_o_r___p_o_l_l_i_n_g___t_a_b_l_e___h_e_a_d_e_r.html#a5be177b19cb078e9ef7c57a29e564bc5", null ]
];