var union_c_p_u_i_d___i_n_t_e_l___r_d_t___a_l_l_o_c_a_t_i_o_n___m_e_m_o_r_y___b_a_n_d_w_i_d_t_h___s_u_b___l_e_a_f___e_d_x =
[
    [ "Bits", "union_c_p_u_i_d___i_n_t_e_l___r_d_t___a_l_l_o_c_a_t_i_o_n___m_e_m_o_r_y___b_a_n_d_w_i_d_t_h___s_u_b___l_e_a_f___e_d_x.html#a39f88d5cace585649aeee5d521e68dd0", null ],
    [ "HighestCosNumber", "union_c_p_u_i_d___i_n_t_e_l___r_d_t___a_l_l_o_c_a_t_i_o_n___m_e_m_o_r_y___b_a_n_d_w_i_d_t_h___s_u_b___l_e_a_f___e_d_x.html#ad97b37e96dfa692e329bebfe411d10ac", null ],
    [ "Reserved", "union_c_p_u_i_d___i_n_t_e_l___r_d_t___a_l_l_o_c_a_t_i_o_n___m_e_m_o_r_y___b_a_n_d_w_i_d_t_h___s_u_b___l_e_a_f___e_d_x.html#a45d2ee122e83ab1ca6a7ea4131773327", null ],
    [ "Uint32", "union_c_p_u_i_d___i_n_t_e_l___r_d_t___a_l_l_o_c_a_t_i_o_n___m_e_m_o_r_y___b_a_n_d_w_i_d_t_h___s_u_b___l_e_a_f___e_d_x.html#ae731ec9933e9ec030da9af5e8e56403a", null ]
];