var union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__16__0___l_a_n_e___e_q_u_a_l_i_z_a_t_i_o_n___c_o_n_t_r_o_l =
[
    [ "Bits", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__16__0___l_a_n_e___e_q_u_a_l_i_z_a_t_i_o_n___c_o_n_t_r_o_l.html#aa9516d277f71d74c881a5fcf0a9aedf2", null ],
    [ "DownstreamPortTransmitterPreset", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__16__0___l_a_n_e___e_q_u_a_l_i_z_a_t_i_o_n___c_o_n_t_r_o_l.html#a1bce674d3edba215402bda585ed8fe66", null ],
    [ "Uint8", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__16__0___l_a_n_e___e_q_u_a_l_i_z_a_t_i_o_n___c_o_n_t_r_o_l.html#a17fdf7521efb1991fd20d51ee9edace3", null ],
    [ "UpstreamPortTransmitterPreset", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__16__0___l_a_n_e___e_q_u_a_l_i_z_a_t_i_o_n___c_o_n_t_r_o_l.html#a4869b0b91474fe8d987acb7f950c786f", null ]
];