var union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___l_a_n_e___e_q_u_a_l_i_z_a_t_i_o_n___c_o_n_t_r_o_l =
[
    [ "Bits", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___l_a_n_e___e_q_u_a_l_i_z_a_t_i_o_n___c_o_n_t_r_o_l.html#a6748eeb2b19c03da3445164eda163096", null ],
    [ "DownstreamPortTransmitterPreset", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___l_a_n_e___e_q_u_a_l_i_z_a_t_i_o_n___c_o_n_t_r_o_l.html#a4ee124fa5cae2b64395425cf503f5dc6", null ],
    [ "Uint8", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___l_a_n_e___e_q_u_a_l_i_z_a_t_i_o_n___c_o_n_t_r_o_l.html#abf8d24e34ee41d2d712dbf3a5a8cbe32", null ],
    [ "UpstreamPortTransmitterPreset", "union_p_c_i___e_x_p_r_e_s_s___r_e_g___p_h_y_s_i_c_a_l___l_a_y_e_r__32__0___l_a_n_e___e_q_u_a_l_i_z_a_t_i_o_n___c_o_n_t_r_o_l.html#a3c10d7be2bbc76939e1013accbef6715", null ]
];