var annotated =
[
    [ "_EDKII_PEI_FIRMWARE_VOLUME_INFO_STORED_HASH_FV_PPI", "struct___e_d_k_i_i___p_e_i___f_i_r_m_w_a_r_e___v_o_l_u_m_e___i_n_f_o___s_t_o_r_e_d___h_a_s_h___f_v___p_p_i.html", "struct___e_d_k_i_i___p_e_i___f_i_r_m_w_a_r_e___v_o_l_u_m_e___i_n_f_o___s_t_o_r_e_d___h_a_s_h___f_v___p_p_i" ],
    [ "_EDKII_TCG_PPI", "struct___e_d_k_i_i___t_c_g___p_p_i.html", "struct___e_d_k_i_i___t_c_g___p_p_i" ],
    [ "_FV_HASH_INFO", "struct___f_v___h_a_s_h___i_n_f_o.html", "struct___f_v___h_a_s_h___i_n_f_o" ],
    [ "_HASH_INFO", "struct___h_a_s_h___i_n_f_o.html", "struct___h_a_s_h___i_n_f_o" ],
    [ "_HASHED_FV_INFO", "struct___h_a_s_h_e_d___f_v___i_n_f_o.html", "struct___h_a_s_h_e_d___f_v___i_n_f_o" ],
    [ "_PEI_LOCK_PHYSICAL_PRESENCE_PPI", "struct___p_e_i___l_o_c_k___p_h_y_s_i_c_a_l___p_r_e_s_e_n_c_e___p_p_i.html", "struct___p_e_i___l_o_c_k___p_h_y_s_i_c_a_l___p_r_e_s_e_n_c_e___p_p_i" ],
    [ "AML_OP_REGION_32_8", "struct_a_m_l___o_p___r_e_g_i_o_n__32__8.html", "struct_a_m_l___o_p___r_e_g_i_o_n__32__8" ],
    [ "EDKII_PEI_FIRMWARE_VOLUME_INFO_PREHASHED_FV_PPI", "struct_e_d_k_i_i___p_e_i___f_i_r_m_w_a_r_e___v_o_l_u_m_e___i_n_f_o___p_r_e_h_a_s_h_e_d___f_v___p_p_i.html", "struct_e_d_k_i_i___p_e_i___f_i_r_m_w_a_r_e___v_o_l_u_m_e___i_n_f_o___p_r_e_h_a_s_h_e_d___f_v___p_p_i" ],
    [ "EFI_PEI_FIRMWARE_VOLUME_INFO_MEASUREMENT_EXCLUDED_FV", "struct_e_f_i___p_e_i___f_i_r_m_w_a_r_e___v_o_l_u_m_e___i_n_f_o___m_e_a_s_u_r_e_m_e_n_t___e_x_c_l_u_d_e_d___f_v.html", "struct_e_f_i___p_e_i___f_i_r_m_w_a_r_e___v_o_l_u_m_e___i_n_f_o___m_e_a_s_u_r_e_m_e_n_t___e_x_c_l_u_d_e_d___f_v" ],
    [ "EFI_PEI_FIRMWARE_VOLUME_INFO_MEASUREMENT_EXCLUDED_PPI", "struct_e_f_i___p_e_i___f_i_r_m_w_a_r_e___v_o_l_u_m_e___i_n_f_o___m_e_a_s_u_r_e_m_e_n_t___e_x_c_l_u_d_e_d___p_p_i.html", "struct_e_f_i___p_e_i___f_i_r_m_w_a_r_e___v_o_l_u_m_e___i_n_f_o___m_e_a_s_u_r_e_m_e_n_t___e_x_c_l_u_d_e_d___p_p_i" ],
    [ "EFI_PHYSICAL_PRESENCE", "struct_e_f_i___p_h_y_s_i_c_a_l___p_r_e_s_e_n_c_e.html", "struct_e_f_i___p_h_y_s_i_c_a_l___p_r_e_s_e_n_c_e" ],
    [ "EFI_PHYSICAL_PRESENCE_FLAGS", "struct_e_f_i___p_h_y_s_i_c_a_l___p_r_e_s_e_n_c_e___f_l_a_g_s.html", "struct_e_f_i___p_h_y_s_i_c_a_l___p_r_e_s_e_n_c_e___f_l_a_g_s" ],
    [ "EFI_TCG2_PHYSICAL_PRESENCE", "struct_e_f_i___t_c_g2___p_h_y_s_i_c_a_l___p_r_e_s_e_n_c_e.html", "struct_e_f_i___t_c_g2___p_h_y_s_i_c_a_l___p_r_e_s_e_n_c_e" ],
    [ "EFI_TCG2_PHYSICAL_PRESENCE_FLAGS", "struct_e_f_i___t_c_g2___p_h_y_s_i_c_a_l___p_r_e_s_e_n_c_e___f_l_a_g_s.html", "struct_e_f_i___t_c_g2___p_h_y_s_i_c_a_l___p_r_e_s_e_n_c_e___f_l_a_g_s" ],
    [ "HANDOFF_TABLE_POINTERS2_STRUCT", "struct_h_a_n_d_o_f_f___t_a_b_l_e___p_o_i_n_t_e_r_s2___s_t_r_u_c_t.html", "struct_h_a_n_d_o_f_f___t_a_b_l_e___p_o_i_n_t_e_r_s2___s_t_r_u_c_t" ],
    [ "HASH_INTERFACE", "struct_h_a_s_h___i_n_t_e_r_f_a_c_e.html", "struct_h_a_s_h___i_n_t_e_r_f_a_c_e" ],
    [ "MEASURED_HOB_DATA", "struct_m_e_a_s_u_r_e_d___h_o_b___d_a_t_a.html", "struct_m_e_a_s_u_r_e_d___h_o_b___d_a_t_a" ],
    [ "MEMORY_CLEAR_NVS", "struct_m_e_m_o_r_y___c_l_e_a_r___n_v_s.html", "struct_m_e_m_o_r_y___c_l_e_a_r___n_v_s" ],
    [ "OPAL_DISK_SUPPORT_ATTRIBUTE", "struct_o_p_a_l___d_i_s_k___s_u_p_p_o_r_t___a_t_t_r_i_b_u_t_e.html", "struct_o_p_a_l___d_i_s_k___s_u_p_p_o_r_t___a_t_t_r_i_b_u_t_e" ],
    [ "OPAL_SESSION", "struct_o_p_a_l___s_e_s_s_i_o_n.html", "struct_o_p_a_l___s_e_s_s_i_o_n" ],
    [ "PHYSICAL_PRESENCE_NVS", "struct_p_h_y_s_i_c_a_l___p_r_e_s_e_n_c_e___n_v_s.html", "struct_p_h_y_s_i_c_a_l___p_r_e_s_e_n_c_e___n_v_s" ],
    [ "PLATFORM_FIRMWARE_BLOB2_STRUCT", "struct_p_l_a_t_f_o_r_m___f_i_r_m_w_a_r_e___b_l_o_b2___s_t_r_u_c_t.html", "struct_p_l_a_t_f_o_r_m___f_i_r_m_w_a_r_e___b_l_o_b2___s_t_r_u_c_t" ],
    [ "TCG_CREATE_STRUCT", "struct_t_c_g___c_r_e_a_t_e___s_t_r_u_c_t.html", "struct_t_c_g___c_r_e_a_t_e___s_t_r_u_c_t" ],
    [ "TCG_NVS", "struct_t_c_g___n_v_s.html", "struct_t_c_g___n_v_s" ],
    [ "TCG_PARSE_STRUCT", "struct_t_c_g___p_a_r_s_e___s_t_r_u_c_t.html", "struct_t_c_g___p_a_r_s_e___s_t_r_u_c_t" ],
    [ "TCG_TOKEN", "struct_t_c_g___t_o_k_e_n.html", "struct_t_c_g___t_o_k_e_n" ],
    [ "TIS_PC_REGISTERS", "struct_t_i_s___p_c___r_e_g_i_s_t_e_r_s.html", "struct_t_i_s___p_c___r_e_g_i_s_t_e_r_s" ],
    [ "TPM12_NV_DATA_PUBLIC", "struct_t_p_m12___n_v___d_a_t_a___p_u_b_l_i_c.html", "struct_t_p_m12___n_v___d_a_t_a___p_u_b_l_i_c" ],
    [ "TPM12_PCR_INFO_SHORT", "struct_t_p_m12___p_c_r___i_n_f_o___s_h_o_r_t.html", "struct_t_p_m12___p_c_r___i_n_f_o___s_h_o_r_t" ],
    [ "TPM12_PCR_SELECTION", "struct_t_p_m12___p_c_r___s_e_l_e_c_t_i_o_n.html", "struct_t_p_m12___p_c_r___s_e_l_e_c_t_i_o_n" ],
    [ "TPM2_DEVICE_INTERFACE", "struct_t_p_m2___d_e_v_i_c_e___i_n_t_e_r_f_a_c_e.html", "struct_t_p_m2___d_e_v_i_c_e___i_n_t_e_r_f_a_c_e" ],
    [ "TPM_NVS_MM_COMM_BUFFER", "struct_t_p_m___n_v_s___m_m___c_o_m_m___b_u_f_f_e_r.html", "struct_t_p_m___n_v_s___m_m___c_o_m_m___b_u_f_f_e_r" ]
];