## @file
# Composite action Installs Git submodules using stuart_setup with caching to
# avoid re-cloning on subsequent runs.
#
# Copyright (C) 2026 Intel Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

name: Install Git Submodules from stuart_setup
description: Use cache restore/save for git submodules installed by stuart_setup
inputs:
  stuart-ci-settings-file:
    description: Path to the stuart CI settings file (e.g. .pytool/CISettings.py)
    required: true
runs:
  using: 'composite'
  steps:
    - name: Restore submodules
      id: cache-submodules
      uses: actions/cache/restore@v5
      with:
        path: .git/modules
        key: ${{ runner.os }}-stuart-setup-submodules-${{ hashFiles('.gitmodules', inputs.stuart-ci-settings-file) }}
    - name: Clone Submodules
      shell: bash
      run: stuart_setup -c ${{ inputs.stuart-ci-settings-file }}
    - name: Save submodules
      if: ${{ steps.cache-submodules.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v5
      with:
        path: .git/modules
        key: ${{ steps.cache-submodules.outputs.cache-primary-key }}
