var searchData=
[
  ['fsp_5fglobal_5fdata',['FSP_GLOBAL_DATA',['../struct_f_s_p___g_l_o_b_a_l___d_a_t_a.html',1,'']]],
  ['fsp_5finfo_5fextended_5fheader',['FSP_INFO_EXTENDED_HEADER',['../struct_f_s_p___i_n_f_o___e_x_t_e_n_d_e_d___h_e_a_d_e_r.html',1,'']]],
  ['fsp_5finfo_5fheader',['FSP_INFO_HEADER',['../struct_f_s_p___i_n_f_o___h_e_a_d_e_r.html',1,'']]],
  ['fsp_5fmulti_5fphase_5fget_5fnumber_5fof_5fphases_5fparams',['FSP_MULTI_PHASE_GET_NUMBER_OF_PHASES_PARAMS',['../struct_f_s_p___m_u_l_t_i___p_h_a_s_e___g_e_t___n_u_m_b_e_r___o_f___p_h_a_s_e_s___p_a_r_a_m_s.html',1,'']]],
  ['fsp_5fmulti_5fphase_5fparams',['FSP_MULTI_PHASE_PARAMS',['../struct_f_s_p___m_u_l_t_i___p_h_a_s_e___p_a_r_a_m_s.html',1,'']]],
  ['fsp_5fnon_5fvolatile_5fstorage_5fhob2',['FSP_NON_VOLATILE_STORAGE_HOB2',['../struct_f_s_p___n_o_n___v_o_l_a_t_i_l_e___s_t_o_r_a_g_e___h_o_b2.html',1,'']]],
  ['fsp_5fpatch_5ftable',['FSP_PATCH_TABLE',['../struct_f_s_p___p_a_t_c_h___t_a_b_l_e.html',1,'']]],
  ['fsp_5fplat_5fdata',['FSP_PLAT_DATA',['../struct_f_s_p___p_l_a_t___d_a_t_a.html',1,'']]],
  ['fsp_5fupd_5fheader',['FSP_UPD_HEADER',['../struct_f_s_p___u_p_d___h_e_a_d_e_r.html',1,'']]],
  ['fspm_5farch_5fconfig_5fppi',['FSPM_ARCH_CONFIG_PPI',['../struct_f_s_p_m___a_r_c_h___c_o_n_f_i_g___p_p_i.html',1,'']]],
  ['fspm_5farch_5fupd',['FSPM_ARCH_UPD',['../struct_f_s_p_m___a_r_c_h___u_p_d.html',1,'']]],
  ['fspm_5fupd_5fcommon',['FSPM_UPD_COMMON',['../struct_f_s_p_m___u_p_d___c_o_m_m_o_n.html',1,'']]],
  ['fsps_5farch_5fupd',['FSPS_ARCH_UPD',['../struct_f_s_p_s___a_r_c_h___u_p_d.html',1,'']]],
  ['fsps_5fupd_5fcommon',['FSPS_UPD_COMMON',['../struct_f_s_p_s___u_p_d___c_o_m_m_o_n.html',1,'']]],
  ['fsps_5fupd_5fcommon_5ffsp22',['FSPS_UPD_COMMON_FSP22',['../struct_f_s_p_s___u_p_d___c_o_m_m_o_n___f_s_p22.html',1,'']]],
  ['fspt_5farch_5fupd',['FSPT_ARCH_UPD',['../struct_f_s_p_t___a_r_c_h___u_p_d.html',1,'']]],
  ['fspt_5fupd_5fcommon',['FSPT_UPD_COMMON',['../struct_f_s_p_t___u_p_d___c_o_m_m_o_n.html',1,'']]],
  ['fspt_5fupd_5fcommon_5ffsp22',['FSPT_UPD_COMMON_FSP22',['../struct_f_s_p_t___u_p_d___c_o_m_m_o_n___f_s_p22.html',1,'']]]
];
