var searchData=
[
  ['standalonemmpkg_20package_20document',['StandaloneMmPkg Package Document',['../index.html',1,'']]],
  ['standalonemmcoreentrypoint',['StandaloneMmCoreEntryPoint',['../lc__standalone_mm_core_entry_point.html',1,'lc_common']]],
  ['signature',['Signature',['../struct_m_m___c_o_r_e___p_r_i_v_a_t_e___d_a_t_a.html#a31552ee16d00ecd550fe223898fa25a5',1,'MM_CORE_PRIVATE_DATA']]],
  ['size',['Size',['../struct_e_f_i___p_a_r_a_m___h_e_a_d_e_r.html#a33fe0a74400f635dc33fc737ea505c13',1,'EFI_PARAM_HEADER::Size()'],['../struct_e_f_i___m_m___c_o_m_m_u_n_i_c_a_t_e___f_v___d_i_s_p_a_t_c_h___d_a_t_a.html#a82b6c7e6f9e3d0062a02d15b207e3314',1,'EFI_MM_COMMUNICATE_FV_DISPATCH_DATA::Size()']]],
  ['spheapbase',['SpHeapBase',['../struct_e_f_i___s_e_c_u_r_e___p_a_r_t_i_t_i_o_n___b_o_o_t___i_n_f_o.html#ace5d544bfcb9e4bd05b82cb2deab9528',1,'EFI_SECURE_PARTITION_BOOT_INFO']]],
  ['spheapsize',['SpHeapSize',['../struct_e_f_i___s_e_c_u_r_e___p_a_r_t_i_t_i_o_n___b_o_o_t___i_n_f_o.html#adf017df62db4174df700555b7b48a0e6',1,'EFI_SECURE_PARTITION_BOOT_INFO']]],
  ['spimagebase',['SpImageBase',['../struct_e_f_i___s_e_c_u_r_e___p_a_r_t_i_t_i_o_n___b_o_o_t___i_n_f_o.html#a88c718de3fbf8f7a656acb2753fabcd0',1,'EFI_SECURE_PARTITION_BOOT_INFO']]],
  ['spimagesize',['SpImageSize',['../struct_e_f_i___s_e_c_u_r_e___p_a_r_t_i_t_i_o_n___b_o_o_t___i_n_f_o.html#a6429757cf5796f66af72502d52b9f588',1,'EFI_SECURE_PARTITION_BOOT_INFO']]],
  ['spmembase',['SpMemBase',['../struct_e_f_i___s_e_c_u_r_e___p_a_r_t_i_t_i_o_n___b_o_o_t___i_n_f_o.html#a92943b5d7160c6bdf2bfec9b8b18e1d2',1,'EFI_SECURE_PARTITION_BOOT_INFO']]],
  ['spmemlimit',['SpMemLimit',['../struct_e_f_i___s_e_c_u_r_e___p_a_r_t_i_t_i_o_n___b_o_o_t___i_n_f_o.html#a2c3a58f5dfed4def681b8ce2a7e8be9d',1,'EFI_SECURE_PARTITION_BOOT_INFO']]],
  ['spnscommbufbase',['SpNsCommBufBase',['../struct_e_f_i___s_e_c_u_r_e___p_a_r_t_i_t_i_o_n___b_o_o_t___i_n_f_o.html#a83469efb047a43120da016f9a4ac604c',1,'EFI_SECURE_PARTITION_BOOT_INFO']]],
  ['spnscommbufsize',['SpNsCommBufSize',['../struct_e_f_i___s_e_c_u_r_e___p_a_r_t_i_t_i_o_n___b_o_o_t___i_n_f_o.html#a19db2f9bcd0fc8ac4717508dd52b9bfb',1,'EFI_SECURE_PARTITION_BOOT_INFO']]],
  ['sppcpusharedbufsize',['SpPcpuSharedBufSize',['../struct_e_f_i___s_e_c_u_r_e___p_a_r_t_i_t_i_o_n___b_o_o_t___i_n_f_o.html#a55f21aad760f130fe6b938700303a3e4',1,'EFI_SECURE_PARTITION_BOOT_INFO']]],
  ['sppcpustacksize',['SpPcpuStackSize',['../struct_e_f_i___s_e_c_u_r_e___p_a_r_t_i_t_i_o_n___b_o_o_t___i_n_f_o.html#a0afd695d3522d70739e372bba8795687',1,'EFI_SECURE_PARTITION_BOOT_INFO']]],
  ['spsharedbufbase',['SpSharedBufBase',['../struct_e_f_i___s_e_c_u_r_e___p_a_r_t_i_t_i_o_n___b_o_o_t___i_n_f_o.html#aa822f2b889d72ec74bcbd56010370f74',1,'EFI_SECURE_PARTITION_BOOT_INFO']]],
  ['spstackbase',['SpStackBase',['../struct_e_f_i___s_e_c_u_r_e___p_a_r_t_i_t_i_o_n___b_o_o_t___i_n_f_o.html#a3a8f47fb704cbe9535ecdc473c8cd6b0',1,'EFI_SECURE_PARTITION_BOOT_INFO']]],
  ['standalonebfvaddress',['StandaloneBfvAddress',['../struct_m_m___c_o_r_e___p_r_i_v_a_t_e___d_a_t_a.html#a0de5898e330688c043690f894546f2f1',1,'MM_CORE_PRIVATE_DATA']]],
  ['standalonemm_2eh',['StandaloneMm.h',['../_standalone_mm_8h.html',1,'']]],
  ['standalonemmcoreentrypoint_2eh',['StandaloneMmCoreEntryPoint.h',['../_standalone_mm_core_entry_point_8h.html',1,'']]],
  ['standalonemmcoreentrypoint_2eh',['StandaloneMmCoreEntryPoint.h',['../_arm_2_standalone_mm_core_entry_point_8h.html',1,'']]],
  ['standalonemmmemlib_2eh',['StandaloneMmMemLib.h',['../_standalone_mm_mem_lib_8h.html',1,'']]],
  ['standalonemmpkg_2edec_2edecdoxygen',['StandaloneMmPkg.dec.decdoxygen',['../_standalone_mm_pkg_8dec_8decdoxygen.html',1,'']]]
];
