var annotated =
[
    [ "DEBUG_DATA_BREAKPOINT_TYPE", "struct_d_e_b_u_g___d_a_t_a___b_r_e_a_k_p_o_i_n_t___t_y_p_e.html", "struct_d_e_b_u_g___d_a_t_a___b_r_e_a_k_p_o_i_n_t___t_y_p_e" ],
    [ "DEBUG_DATA_CLEAR_HW_BREAKPOINT", "struct_d_e_b_u_g___d_a_t_a___c_l_e_a_r___h_w___b_r_e_a_k_p_o_i_n_t.html", "struct_d_e_b_u_g___d_a_t_a___c_l_e_a_r___h_w___b_r_e_a_k_p_o_i_n_t" ],
    [ "DEBUG_DATA_CPUID", "struct_d_e_b_u_g___d_a_t_a___c_p_u_i_d.html", "struct_d_e_b_u_g___d_a_t_a___c_p_u_i_d" ],
    [ "DEBUG_DATA_IA32_FX_SAVE_STATE", "struct_d_e_b_u_g___d_a_t_a___i_a32___f_x___s_a_v_e___s_t_a_t_e.html", "struct_d_e_b_u_g___d_a_t_a___i_a32___f_x___s_a_v_e___s_t_a_t_e" ],
    [ "DEBUG_DATA_IA32_SYSTEM_CONTEXT", "struct_d_e_b_u_g___d_a_t_a___i_a32___s_y_s_t_e_m___c_o_n_t_e_x_t.html", "struct_d_e_b_u_g___d_a_t_a___i_a32___s_y_s_t_e_m___c_o_n_t_e_x_t" ],
    [ "DEBUG_DATA_READ_IO", "struct_d_e_b_u_g___d_a_t_a___r_e_a_d___i_o.html", "struct_d_e_b_u_g___d_a_t_a___r_e_a_d___i_o" ],
    [ "DEBUG_DATA_READ_MEMORY", "struct_d_e_b_u_g___d_a_t_a___r_e_a_d___m_e_m_o_r_y.html", "struct_d_e_b_u_g___d_a_t_a___r_e_a_d___m_e_m_o_r_y" ],
    [ "DEBUG_DATA_READ_MSR", "struct_d_e_b_u_g___d_a_t_a___r_e_a_d___m_s_r.html", "struct_d_e_b_u_g___d_a_t_a___r_e_a_d___m_s_r" ],
    [ "DEBUG_DATA_READ_REGISTER", "struct_d_e_b_u_g___d_a_t_a___r_e_a_d___r_e_g_i_s_t_e_r.html", "struct_d_e_b_u_g___d_a_t_a___r_e_a_d___r_e_g_i_s_t_e_r" ],
    [ "DEBUG_DATA_RESPONSE_ARCH_MODE", "struct_d_e_b_u_g___d_a_t_a___r_e_s_p_o_n_s_e___a_r_c_h___m_o_d_e.html", "struct_d_e_b_u_g___d_a_t_a___r_e_s_p_o_n_s_e___a_r_c_h___m_o_d_e" ],
    [ "DEBUG_DATA_RESPONSE_BREAK_CAUSE", "struct_d_e_b_u_g___d_a_t_a___r_e_s_p_o_n_s_e___b_r_e_a_k___c_a_u_s_e.html", "struct_d_e_b_u_g___d_a_t_a___r_e_s_p_o_n_s_e___b_r_e_a_k___c_a_u_s_e" ],
    [ "DEBUG_DATA_RESPONSE_CPUID", "struct_d_e_b_u_g___d_a_t_a___r_e_s_p_o_n_s_e___c_p_u_i_d.html", "struct_d_e_b_u_g___d_a_t_a___r_e_s_p_o_n_s_e___c_p_u_i_d" ],
    [ "DEBUG_DATA_RESPONSE_GET_EXCEPTION", "struct_d_e_b_u_g___d_a_t_a___r_e_s_p_o_n_s_e___g_e_t___e_x_c_e_p_t_i_o_n.html", "struct_d_e_b_u_g___d_a_t_a___r_e_s_p_o_n_s_e___g_e_t___e_x_c_e_p_t_i_o_n" ],
    [ "DEBUG_DATA_RESPONSE_GET_REVISION", "struct_d_e_b_u_g___d_a_t_a___r_e_s_p_o_n_s_e___g_e_t___r_e_v_i_s_i_o_n.html", "struct_d_e_b_u_g___d_a_t_a___r_e_s_p_o_n_s_e___g_e_t___r_e_v_i_s_i_o_n" ],
    [ "DEBUG_DATA_RESPONSE_GET_VIEWPOINT", "struct_d_e_b_u_g___d_a_t_a___r_e_s_p_o_n_s_e___g_e_t___v_i_e_w_p_o_i_n_t.html", "struct_d_e_b_u_g___d_a_t_a___r_e_s_p_o_n_s_e___g_e_t___v_i_e_w_p_o_i_n_t" ],
    [ "DEBUG_DATA_RESPONSE_READ_IO", "struct_d_e_b_u_g___d_a_t_a___r_e_s_p_o_n_s_e___r_e_a_d___i_o.html", "struct_d_e_b_u_g___d_a_t_a___r_e_s_p_o_n_s_e___r_e_a_d___i_o" ],
    [ "DEBUG_DATA_RESPONSE_READ_MSR", "struct_d_e_b_u_g___d_a_t_a___r_e_s_p_o_n_s_e___r_e_a_d___m_s_r.html", "struct_d_e_b_u_g___d_a_t_a___r_e_s_p_o_n_s_e___r_e_a_d___m_s_r" ],
    [ "DEBUG_DATA_RESPONSE_SEARCH_SIGNATURE", "struct_d_e_b_u_g___d_a_t_a___r_e_s_p_o_n_s_e___s_e_a_r_c_h___s_i_g_n_a_t_u_r_e.html", "struct_d_e_b_u_g___d_a_t_a___r_e_s_p_o_n_s_e___s_e_a_r_c_h___s_i_g_n_a_t_u_r_e" ],
    [ "DEBUG_DATA_RESPONSE_SET_SW_BREAKPOINT", "struct_d_e_b_u_g___d_a_t_a___r_e_s_p_o_n_s_e___s_e_t___s_w___b_r_e_a_k_p_o_i_n_t.html", "struct_d_e_b_u_g___d_a_t_a___r_e_s_p_o_n_s_e___s_e_t___s_w___b_r_e_a_k_p_o_i_n_t" ],
    [ "DEBUG_DATA_SEARCH_SIGNATURE", "struct_d_e_b_u_g___d_a_t_a___s_e_a_r_c_h___s_i_g_n_a_t_u_r_e.html", "struct_d_e_b_u_g___d_a_t_a___s_e_a_r_c_h___s_i_g_n_a_t_u_r_e" ],
    [ "DEBUG_DATA_SET_DEBUG_SETTING", "struct_d_e_b_u_g___d_a_t_a___s_e_t___d_e_b_u_g___s_e_t_t_i_n_g.html", "struct_d_e_b_u_g___d_a_t_a___s_e_t___d_e_b_u_g___s_e_t_t_i_n_g" ],
    [ "DEBUG_DATA_SET_HW_BREAKPOINT", "struct_d_e_b_u_g___d_a_t_a___s_e_t___h_w___b_r_e_a_k_p_o_i_n_t.html", "struct_d_e_b_u_g___d_a_t_a___s_e_t___h_w___b_r_e_a_k_p_o_i_n_t" ],
    [ "DEBUG_DATA_SET_SW_BREAKPOINT", "struct_d_e_b_u_g___d_a_t_a___s_e_t___s_w___b_r_e_a_k_p_o_i_n_t.html", "struct_d_e_b_u_g___d_a_t_a___s_e_t___s_w___b_r_e_a_k_p_o_i_n_t" ],
    [ "DEBUG_DATA_SET_VIEWPOINT", "struct_d_e_b_u_g___d_a_t_a___s_e_t___v_i_e_w_p_o_i_n_t.html", "struct_d_e_b_u_g___d_a_t_a___s_e_t___v_i_e_w_p_o_i_n_t" ],
    [ "DEBUG_DATA_WRITE_IO", "struct_d_e_b_u_g___d_a_t_a___w_r_i_t_e___i_o.html", "struct_d_e_b_u_g___d_a_t_a___w_r_i_t_e___i_o" ],
    [ "DEBUG_DATA_WRITE_MEMORY", "struct_d_e_b_u_g___d_a_t_a___w_r_i_t_e___m_e_m_o_r_y.html", "struct_d_e_b_u_g___d_a_t_a___w_r_i_t_e___m_e_m_o_r_y" ],
    [ "DEBUG_DATA_WRITE_MSR", "struct_d_e_b_u_g___d_a_t_a___w_r_i_t_e___m_s_r.html", "struct_d_e_b_u_g___d_a_t_a___w_r_i_t_e___m_s_r" ],
    [ "DEBUG_DATA_WRITE_REGISTER", "struct_d_e_b_u_g___d_a_t_a___w_r_i_t_e___r_e_g_i_s_t_e_r.html", "struct_d_e_b_u_g___d_a_t_a___w_r_i_t_e___r_e_g_i_s_t_e_r" ],
    [ "DEBUG_DATA_X64_FX_SAVE_STATE", "struct_d_e_b_u_g___d_a_t_a___x64___f_x___s_a_v_e___s_t_a_t_e.html", "struct_d_e_b_u_g___d_a_t_a___x64___f_x___s_a_v_e___s_t_a_t_e" ],
    [ "DEBUG_DATA_X64_SYSTEM_CONTEXT", "struct_d_e_b_u_g___d_a_t_a___x64___s_y_s_t_e_m___c_o_n_t_e_x_t.html", "struct_d_e_b_u_g___d_a_t_a___x64___s_y_s_t_e_m___c_o_n_t_e_x_t" ],
    [ "DEBUG_PACKET_HEADER", "struct_d_e_b_u_g___p_a_c_k_e_t___h_e_a_d_e_r.html", "struct_d_e_b_u_g___p_a_c_k_e_t___h_e_a_d_e_r" ]
];