## @file
# Composite action that sets sets up Stuart Tools, builds edk2 BaseTools, and
# sets NASM_PREFIX and IASL_PREFIX environment variables.
#
# Copyright (C) 2025 Intel Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

name: 'Windows Install Stuart Tools from stuart_update and build BaseTools'
description: 'Windows use stuart_update to download external dependencies and build BaseTools'
inputs:
  stuart-ci-settings-file:
    description: 'Path to the stuart CI settings file (e.g. .pytool/CISettings.py)'
    required: true
  edk2-tools-build-params:
    description: 'Command line parameters for Edk2ToolsBuild.py (e.g. -t VS2022)'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Download External Dependencies'
      shell: bash
      run: stuart_update -c ${{ inputs.stuart-ci-settings-file }}
    - name: 'Build BaseTools'
      shell: bash
      run: python BaseTools/Edk2ToolsBuild.py ${{ inputs.edk2-tools-build-params }}
    - name: Set NASM_PREFIX and IASL_PREFIX environment variables
      shell: cmd
      run: |
        echo NASM_PREFIX=%GITHUB_WORKSPACE%\BaseTools\Bin\mu_nasm_extdep\Windows-x86-64\>> %GITHUB_ENV%
        echo IASL_PREFIX=%GITHUB_WORKSPACE%\BaseTools\Bin\edk2-acpica-iasl_extdep\Windows-x86\>> %GITHUB_ENV%
