## @file
# Composite action that checks out a reference or a pull-request. If a reference
# is being checked out, then use fetch-depth of 1. If a pull-request is being
# checked out, then use fetch-depth of number of commits in the pull-request + 1
#
# Copyright (C) 2025 Intel Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

name: 'Checkout Reference or Pull Request'
description: 'Use checkout action to checkout a reference or pull request with appropriate fetch-depth'
runs:
  using: 'composite'
  steps:
    - name: Checkout Reference
      if: github.event_name != 'pull_request'
      #
      # If not PR, then use default checkout settings with fetch-depth of 1
      #
      uses: actions/checkout@v6
    - name: Get Number of Commits in Pull Request
      if: github.event_name == 'pull_request'
      run: |
        echo "PR_COMMIT_COUNT=$((${{ github.event.pull_request.commits }} + 1))" >> $GITHUB_ENV
    - name: Checkout Pull Request
      if: github.event_name == 'pull_request'
      #
      # Checkout PR with fetch-depth of number of commits in PR + 1
      # This allows patch check to evaluate all commits in the PR, and for
      # stuart_pr_eval to evaluate the files modified over the entire PR.
      #
      uses: actions/checkout@v6
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: ${{ env.PR_COMMIT_COUNT }}
    - name: Ensure safe directory for Git
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
