var _smm_variable_common_8h =
[
    [ "SMM_VARIABLE_COMMUNICATE_HEADER", "struct_s_m_m___v_a_r_i_a_b_l_e___c_o_m_m_u_n_i_c_a_t_e___h_e_a_d_e_r.html", "struct_s_m_m___v_a_r_i_a_b_l_e___c_o_m_m_u_n_i_c_a_t_e___h_e_a_d_e_r" ],
    [ "SMM_VARIABLE_COMMUNICATE_ACCESS_VARIABLE", "struct_s_m_m___v_a_r_i_a_b_l_e___c_o_m_m_u_n_i_c_a_t_e___a_c_c_e_s_s___v_a_r_i_a_b_l_e.html", "struct_s_m_m___v_a_r_i_a_b_l_e___c_o_m_m_u_n_i_c_a_t_e___a_c_c_e_s_s___v_a_r_i_a_b_l_e" ],
    [ "SMM_VARIABLE_COMMUNICATE_GET_NEXT_VARIABLE_NAME", "struct_s_m_m___v_a_r_i_a_b_l_e___c_o_m_m_u_n_i_c_a_t_e___g_e_t___n_e_x_t___v_a_r_i_a_b_l_e___n_a_m_e.html", "struct_s_m_m___v_a_r_i_a_b_l_e___c_o_m_m_u_n_i_c_a_t_e___g_e_t___n_e_x_t___v_a_r_i_a_b_l_e___n_a_m_e" ],
    [ "SMM_VARIABLE_COMMUNICATE_QUERY_VARIABLE_INFO", "struct_s_m_m___v_a_r_i_a_b_l_e___c_o_m_m_u_n_i_c_a_t_e___q_u_e_r_y___v_a_r_i_a_b_l_e___i_n_f_o.html", "struct_s_m_m___v_a_r_i_a_b_l_e___c_o_m_m_u_n_i_c_a_t_e___q_u_e_r_y___v_a_r_i_a_b_l_e___i_n_f_o" ],
    [ "SMM_VARIABLE_COMMUNICATE_VAR_CHECK_VARIABLE_PROPERTY", "struct_s_m_m___v_a_r_i_a_b_l_e___c_o_m_m_u_n_i_c_a_t_e___v_a_r___c_h_e_c_k___v_a_r_i_a_b_l_e___p_r_o_p_e_r_t_y.html", "struct_s_m_m___v_a_r_i_a_b_l_e___c_o_m_m_u_n_i_c_a_t_e___v_a_r___c_h_e_c_k___v_a_r_i_a_b_l_e___p_r_o_p_e_r_t_y" ],
    [ "SMM_VARIABLE_COMMUNICATE_GET_PAYLOAD_SIZE", "struct_s_m_m___v_a_r_i_a_b_l_e___c_o_m_m_u_n_i_c_a_t_e___g_e_t___p_a_y_l_o_a_d___s_i_z_e.html", "struct_s_m_m___v_a_r_i_a_b_l_e___c_o_m_m_u_n_i_c_a_t_e___g_e_t___p_a_y_l_o_a_d___s_i_z_e" ],
    [ "SMM_VARIABLE_COMMUNICATE_RUNTIME_VARIABLE_CACHE_CONTEXT", "struct_s_m_m___v_a_r_i_a_b_l_e___c_o_m_m_u_n_i_c_a_t_e___r_u_n_t_i_m_e___v_a_r_i_a_b_l_e___c_a_c_h_e___c_o_n_t_e_x_t.html", "struct_s_m_m___v_a_r_i_a_b_l_e___c_o_m_m_u_n_i_c_a_t_e___r_u_n_t_i_m_e___v_a_r_i_a_b_l_e___c_a_c_h_e___c_o_n_t_e_x_t" ],
    [ "SMM_VARIABLE_COMMUNICATE_GET_RUNTIME_CACHE_INFO", "struct_s_m_m___v_a_r_i_a_b_l_e___c_o_m_m_u_n_i_c_a_t_e___g_e_t___r_u_n_t_i_m_e___c_a_c_h_e___i_n_f_o.html", "struct_s_m_m___v_a_r_i_a_b_l_e___c_o_m_m_u_n_i_c_a_t_e___g_e_t___r_u_n_t_i_m_e___c_a_c_h_e___i_n_f_o" ],
    [ "EFI_SMM_VARIABLE_WRITE_GUID", "_smm_variable_common_8h.html#ae702e5882d3ada843dedb5f236e0a508", null ],
    [ "SMM_COMMUNICATE_HEADER_SIZE", "_smm_variable_common_8h.html#a300fb5b2ed0b806db7efc0770812c042", null ],
    [ "SMM_VARIABLE_COMMUNICATE_HEADER_SIZE", "_smm_variable_common_8h.html#aa7dd51a63d1465b124e3c527416eb789", null ],
    [ "SMM_VARIABLE_FUNCTION_EXIT_BOOT_SERVICE", "_smm_variable_common_8h.html#a737a8ea26ed5cf8e59b3a809f1cab377", null ],
    [ "SMM_VARIABLE_FUNCTION_GET_NEXT_VARIABLE_NAME", "_smm_variable_common_8h.html#add9644bba74a229d2947936f39b94de1", null ],
    [ "SMM_VARIABLE_FUNCTION_GET_PAYLOAD_SIZE", "_smm_variable_common_8h.html#aa0f62588829f6423139410d3a4043b2e", null ],
    [ "SMM_VARIABLE_FUNCTION_GET_RUNTIME_CACHE_INFO", "_smm_variable_common_8h.html#ad40eff242d74de750a9b3ed340e0a909", null ],
    [ "SMM_VARIABLE_FUNCTION_GET_STATISTICS", "_smm_variable_common_8h.html#af1fa2a9df2e6bf814fcf6e1b4d052cb7", null ],
    [ "SMM_VARIABLE_FUNCTION_GET_VARIABLE", "_smm_variable_common_8h.html#a10686b30f959684244ea261e8871cd0f", null ],
    [ "SMM_VARIABLE_FUNCTION_INIT_RUNTIME_VARIABLE_CACHE_CONTEXT", "_smm_variable_common_8h.html#a7a56b4503f72d89c6fdbf1926d7c396b", null ],
    [ "SMM_VARIABLE_FUNCTION_LOCK_VARIABLE", "_smm_variable_common_8h.html#ad50b03ac8508a9306635a387fa3f1b66", null ],
    [ "SMM_VARIABLE_FUNCTION_QUERY_VARIABLE_INFO", "_smm_variable_common_8h.html#a0e77fdb3dfa647f1bb89ce49fe9588d3", null ],
    [ "SMM_VARIABLE_FUNCTION_READY_TO_BOOT", "_smm_variable_common_8h.html#a4e4598b4daee979b065a9e1e8183b8a3", null ],
    [ "SMM_VARIABLE_FUNCTION_SET_VARIABLE", "_smm_variable_common_8h.html#add196e249d467d2c0133a28c1e1e3f37", null ],
    [ "SMM_VARIABLE_FUNCTION_SYNC_RUNTIME_CACHE", "_smm_variable_common_8h.html#aea17ef379dcfae450cc63cc70fc3759c", null ],
    [ "SMM_VARIABLE_FUNCTION_VAR_CHECK_VARIABLE_PROPERTY_GET", "_smm_variable_common_8h.html#a34b85daa29137c669ea465c9283477c7", null ],
    [ "SMM_VARIABLE_FUNCTION_VAR_CHECK_VARIABLE_PROPERTY_SET", "_smm_variable_common_8h.html#a7a4f399f97f1e0ecbff298eee538272e", null ],
    [ "SMM_VARIABLE_COMMUNICATE_LOCK_VARIABLE", "_smm_variable_common_8h.html#a09fb321967176e71f8ac0cfae22d3cc5", null ],
    [ "gSmmVariableWriteGuid", "_smm_variable_common_8h.html#a87c05f9550f9fdbb9a805a619bd7b7c2", null ]
];