var dir_45d5c40681f8263ca9a0c34d0246078d =
[
    [ "AtaAhciController.h", "_ata_ahci_controller_8h.html", "_ata_ahci_controller_8h" ],
    [ "AtaController.h", "_ata_controller_8h.html", "_ata_controller_8h" ],
    [ "AtaPassThru.h", "_ata_pass_thru_8h.html", "_ata_pass_thru_8h" ],
    [ "CapsuleOnDisk.h", "_capsule_on_disk_8h.html", "_capsule_on_disk_8h" ],
    [ "Debug.h", "_debug_8h.html", "_debug_8h" ],
    [ "IoMmu.h", "_ppi_2_io_mmu_8h.html", "_ppi_2_io_mmu_8h" ],
    [ "IpmiPpi.h", "_ipmi_ppi_8h.html", "_ipmi_ppi_8h" ],
    [ "NvmExpressHostController.h", "_nvm_express_host_controller_8h.html", "_nvm_express_host_controller_8h" ],
    [ "NvmExpressPassThru.h", "_nvm_express_pass_thru_8h.html", "_nvm_express_pass_thru_8h" ],
    [ "PlatformSpecificResetFilter.h", "_ppi_2_platform_specific_reset_filter_8h.html", "_ppi_2_platform_specific_reset_filter_8h" ],
    [ "PlatformSpecificResetHandler.h", "_ppi_2_platform_specific_reset_handler_8h.html", "_ppi_2_platform_specific_reset_handler_8h" ],
    [ "PlatformSpecificResetNotification.h", "_platform_specific_reset_notification_8h.html", "_platform_specific_reset_notification_8h" ],
    [ "PostBootScriptTable.h", "_post_boot_script_table_8h.html", "_post_boot_script_table_8h" ],
    [ "SdMmcHostController.h", "_sd_mmc_host_controller_8h.html", "_sd_mmc_host_controller_8h" ],
    [ "SecPerformance.h", "_sec_performance_8h.html", "_sec_performance_8h" ],
    [ "SerialPortPei.h", "_serial_port_pei_8h.html", "_serial_port_pei_8h" ],
    [ "SmmAccess.h", "_smm_access_8h.html", "_smm_access_8h" ],
    [ "SmmCommunication.h", "_smm_communication_8h.html", "_smm_communication_8h" ],
    [ "SmmControl.h", "_smm_control_8h.html", "_smm_control_8h" ],
    [ "StorageSecurityCommand.h", "_storage_security_command_8h.html", "_storage_security_command_8h" ],
    [ "UfsHostController.h", "_ppi_2_ufs_host_controller_8h.html", "_ppi_2_ufs_host_controller_8h" ],
    [ "Usb2HostController.h", "_usb2_host_controller_8h.html", "_usb2_host_controller_8h" ],
    [ "UsbController.h", "_usb_controller_8h.html", "_usb_controller_8h" ],
    [ "UsbHostController.h", "_usb_host_controller_8h.html", "_usb_host_controller_8h" ],
    [ "UsbIo.h", "_usb_io_8h.html", "_usb_io_8h" ]
];