## @file
# A workflow using Ubuntu CLANG tools that builds packages and uploads artifacts.
#
# Copyright (C) 2025 Intel Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: All CLANG 20.1.8 Build 2

on:
  workflow_dispatch:
  pull_request:
    branches:
      - sandbox/master
      - clang_ci_v5b

jobs:
  #
  # Stage 0: Set Package Lists and run patch check
  #
  set_package_lists:
    name: Set Package Lists
    uses: ./.github/workflows/ubuntu-set-package-lists-and-patch-check.yml
    with:
      run-patch-check: true
  stage0:
    name: Stage 0 Success
    runs-on: ubuntu-latest
    needs:
      - set_package_lists
    outputs:
      package-lists: ${{ needs.set_package_lists.outputs.package-lists }}
    steps:
      - name: Stage 0 Success
        run: echo "Stage 0 jobs completed successfully"

  #
  # Stage 1: Run basic acceptance tests and no-target tests
  #
  build_linux_clang_basic_acceptance_test:
    needs: stage0
    uses: ./.github/workflows/ubuntu-clang-20-basic-acceptance-test.yml
    with:
      python-version: '3.12'
      pip-requirements: 'pip-requirements.txt'
      stuart-ci-settings-file: '.pytool/CISettings.py'
      edk2-tools-build-params: '-t CLANGPDB'
  build_linux_clang_no_target_test:
    needs: stage0
    uses: ./.github/workflows/ubuntu-clang-20-package-build-test.yml
    with:
      python-version: '3.12'
      pip-requirements: 'pip-requirements.txt'
      stuart-ci-settings-file: '.pytool/CISettings.py'
      edk2-tools-build-params: '-t CLANGPDB'
      build_type_list: '["NO-TARGET"]'
      #
      # build_arch_list is ignored for NO-TARGET but set to arbitrary value to
      # satisfy workflow call input requirements.
      #
      build_arch_list: '["X64"]'
      tool_chain_tag_list: '["CLANGPDB"]'
      package-lists: ${{ needs.stage0.outputs.package-lists }}
  stage1:
    name: Stage 1 Success
    runs-on: ubuntu-latest
    needs:
      - stage0
      - build_linux_clang_basic_acceptance_test
      - build_linux_clang_no_target_test
    outputs:
      package-lists: ${{ needs.stage0.outputs.package-lists }}
    steps:
      - name: Stage 1 Success
        run: echo "Stage 1 jobs completed successfully"

  #
  # Stage 2: Run full tests for packages and platforms
  #
  ubuntu_clang_20_build:
    # Firmware Build Support:             CLANGPDB/CLANGDWARF - IA32/X64
    # Host-Based Unit Test Build Support: CLANGDWARF          - IA32/X64
    # EmulatorPkg Build Support:          CLANGDWARF          - IA32/X64
    needs: stage1
    uses: ./.github/workflows/ubuntu-clang-20-build.yml
    with:
      package-lists: ${{ needs.stage1.outputs.package-lists }}
  windows_mingw_llvm_20_clang_build:
    # Firmware Build Support:             CLANGDWARF - IA32/X64
    # Host-Based Unit Test Build Support: CLANGDWARF - IA32/X64
    # EmulatorPkg Build Support:          CLANGDWARF - IA32/X64
    needs: stage1
    uses: ./.github/workflows/windows-mingw-llvm-20-clang-build.yml
    with:
      package-lists: ${{ needs.stage1.outputs.package-lists }}
  windows_mingw_edk2_clang_20_build:
    # Firmware Build Support:             CLANGPDB/CLANGDWARF - IA32/X64
    # Host-Based Unit Test Build Support: CLANGDWARF          - X64
    # EmulatorPkg Build Support:          CLANGDWARF          - X64
    needs: stage1
    uses: ./.github/workflows/windows-mingw-edk2-clang-20-build.yml
    with:
      package-lists: ${{ needs.stage1.outputs.package-lists }}
  windows_vs_llvm_20_clang_build:
    # Firmware Build Support:             CLANGPDB - IA32/X64
    # Host-Based Unit Test Build Support: CLANGPDB - IA32/X64
    # EmulatorPkg Build Support:          CLANGPDB - IA32/X64
    needs: stage1
    uses: ./.github/workflows/windows-vs-llvm-20-clang-build.yml
    with:
      package-lists: ${{ needs.stage1.outputs.package-lists }}
  stage2:
    name: Stage 2 Success
    runs-on: ubuntu-latest
    needs:
      - stage1
      - ubuntu_clang_20_build
      - windows_mingw_llvm_20_clang_build
      - windows_mingw_edk2_clang_20_build
      - windows_vs_llvm_20_clang_build
    outputs:
      package-lists: ${{ needs.stage1.outputs.package-lists }}
    steps:
      - name: Stage 2 Success
        run: echo "Stage 2 jobs completed successfully"

