# @file
# A workflow that builds packages using clang and upload it's artifacts.
#
# Copyright (c) Intel Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: CLANG Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - sandbox/master

jobs:
  build_linux_clang_precheck:
    name: Build Linux CLANGPDB NO-TARGET PreCheck
    runs-on: ubuntu-latest
    container: ghcr.io/mdkinney/containers/fedora-43-build:latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - NO-TARGET
        build_arch:
          - X64
        build_package:
          - ArmPkg,ArmPlatformPkg,ArmVirtPkg,OvmfPkg,DynamicTablesPkg,EmbeddedPkg,FatPkg,FmpDevicePkg,NetworkPkg,RedfishPkg,PcAtChipsetPkg,MdeModulePkg,MdePkg,CryptoPkg
          - IntelFsp2Pkg,IntelFsp2WrapperPkg,UefiCpuPkg,PrmPkg,SecurityPkg,ShellPkg,SignedCapsulePkg,SourceLevelDebugPkg,UnitTestFrameworkPkg,StandaloneMmPkg,EmulatorPkg
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ensure safe directory for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Cache pip modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pip-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: 'Install/Upgrade pip modules'
        run: |
          pip install --upgrade pip
          pip install --upgrade -r pip-requirements.txt
      - name: PatchCheck PR
        if: github.event_name == 'pull_request'
        run: python BaseTools/Scripts/PatchCheck.py ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
      - name: 'Clone Submodules'
        run: stuart_setup -c ".pytool/CISettings.py" TOOL_CHAIN_TAG=CLANGPDB
      - name: 'Download External Dependencies'
        run: stuart_update -c ".pytool/CISettings.py" TOOL_CHAIN_TAG=CLANGPDB
      - name: 'Build BaseTools'
        env:
          CC: clang
          CXX: clang++
        run: python3 BaseTools/Edk2ToolsBuild.py -t GCC
      - name: 'Build Packages CLANGPDB NO-TARGET'
        run: stuart_ci_build -c ".pytool/CISettings.py" -a ${{ matrix.build_arch }} -t ${{ matrix.build_type }} TOOL_CHAIN_TAG=CLANGPDB -p "${{ matrix.build_package }}"
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Linux NO-TARGET Logs (${{ join(matrix.*, ' - ') }})"
          path: |
            Build/*.txt
            Build/*.log
        if: always()

  build_linux_clang_ovmf_precheck:
    name: Build Linux CLANG PreCheck
    runs-on: ubuntu-latest
    container: ghcr.io/mdkinney/containers/fedora-43-build:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ensure safe directory for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Cache pip modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pip-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: 'Install/Upgrade pip modules'
        run: |
          pip install --upgrade pip
          pip install --upgrade -r pip-requirements.txt
      - name: 'Clone Submodules'
        run: stuart_setup -c ".pytool/CISettings.py" TOOL_CHAIN_TAG=CLANGPDB
      - name: 'Download External Dependencies'
        run: stuart_update -c ".pytool/CISettings.py" TOOL_CHAIN_TAG=CLANGPDB
      - name: 'Build BaseTools'
        env:
          CC: clang
          CXX: clang++
        run: python3 BaseTools/Edk2ToolsBuild.py -t GCC
      - name: 'Build UnitTestFrameworkPkg Unit Tests'
        run: |
          stuart_ci_build -c ".pytool/CISettings.py" -a X64 -t NOOPT TOOL_CHAIN_TAG=CLANGDWARF -p UnitTestFrameworkPkg
      - name: 'Build EmulatorPkg X64 Platform'
        run: |
          . ./edksetup.sh
          build -a X64 -t CLANGDWARF -b DEBUG -p EmulatorPkg/EmulatorPkg.dsc -j Build/EmulatorX64Build.log >NUL
      - name: 'Build EmulatorPkg IA32 Platform'
        run: |
          . ./edksetup.sh
          build -a IA32 -t CLANGDWARF -b DEBUG -p EmulatorPkg/EmulatorPkg.dsc -j Build/EmulatorIA32Build.log >NUL
      - name: 'Build OVMF Platform'
        run: |
          . ./edksetup.sh
          build -a IA32 -a X64 -t CLANGPDB -b DEBUG -p OvmfPkg/OvmfPkgIa32X64.dsc -D SMM_REQUIRE -j Build/OvmfIa32X64Build.log >NUL
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Linux OVMF Precheck Logs"
          path: |
            Build/*.txt
            Build/*.log
        if: always()

  build_windows_clang:
    needs: [build_linux_clang_precheck, build_linux_clang_ovmf_precheck]
    name: Build Windows (${{ join(matrix.*, ' - ') }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - DEBUG
          - RELEASE
        build_arch:
          - IA32
          - X64
        build_package:
          - CryptoPkg,FatPkg,FmpDevicePkg,PcAtChipsetPkg,PrmPkg,SourceLevelDebugPkg,UnitTestFrameworkPkg,StandaloneMmPkg,SignedCapsulePkg
          - ArmPkg,ArmPlatformPkg,DynamicTablesPkg,EmbeddedPkg,NetworkPkg,RedfishPkg,MdeModulePkg,MdePkg,IntelFsp2Pkg,IntelFsp2WrapperPkg,UefiCpuPkg,SecurityPkg,ShellPkg
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ensure safe directory for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Cache CLANG 20.1.8
        id: cache-clang
        uses: actions/cache@v4
        with:
          path: C:\Program Files\LLVM
          key: LLVM-20.1.8-win64.exe-${{ runner.os }}
      - name: Install CLANG 20.1.8
        if: steps.cache-clang.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          curl -SL --output llvm_install.exe https://github.com/llvm/llvm-project/releases/download/llvmorg-20.1.8/LLVM-20.1.8-win64.exe
          llvm_install.exe /S
      - name: Cache LLVM-MinGW
        id: cache-llvm-mingw
        uses: actions/cache@v4
        with:
          path: C:\llvm-mingw-20250709-ucrt-x86_64
          key: llvm-mingw-20250709-ucrt-x86_64-${{ runner.os }}
      - name: Install LLVM-MinGW
        if: steps.cache-llvm-mingw.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          curl -L -o "llvm-mingw.zip" "https://github.com/mstorsjo/llvm-mingw/releases/download/20250709/llvm-mingw-20250709-ucrt-x86_64.zip"
          powershell -command "Expand-Archive -Path 'llvm-mingw.zip' -DestinationPath 'C:\' -Force"
          dir "C:\llvm-mingw-20250709-ucrt-x86_64\bin"
      - name: Cache TianoCore Mingw CLANG
        id: cache-edk2-clang
        uses: actions/cache@v4
        with:
          path: C:\edk2-clang
          key: edk2-clang-20.1.8-${{ runner.os }}
      - name: Install TianoCore Mingw CLANG 20.1.8
        if: steps.cache-edk2-clang.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          curl -L -o EdkClangSetup-20.1.8.0.exe https://github.com/tianocore/edk2-edkrepo/releases/download/edkclang-v20.1.8/EdkClangSetup-20.1.8.0.exe
          EdkClangSetup-20.1.8.0.exe /silent
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: 'pip-requirements.txt'
      - name: Cache pip modules
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('pip-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: 'Install/Upgrade pip modules'
        run: |
          pip install --upgrade pip
          pip install --upgrade -r pip-requirements.txt
      - name: 'Clone Submodules'
        run: stuart_setup -c ".pytool/CISettings.py" TOOL_CHAIN_TAG=CLANGPDB
      - name: 'Download External Dependencies'
        run: stuart_update -c ".pytool/CISettings.py" TOOL_CHAIN_TAG=CLANGPDB
      - name: 'Build BaseTools'
        run: python BaseTools/Edk2ToolsBuild.py -t VS2022
      - name: 'Stuart Packages CLANGPDB-Mingw'
        shell: cmd
        env:
          CLANG_BIN: "C:\\edk2-clang\\bin\\"
        run: |
          PATH=%CLANG_BIN%;%PATH%
          set
          stuart_ci_build -c ".pytool/CISettings.py" -a ${{ matrix.build_arch }} -t ${{ matrix.build_type }} TOOL_CHAIN_TAG=CLANGPDB -p "${{ matrix.build_package }}" -v
      - name: 'Build Packages CLANGPDB-Mingw'
        shell: cmd
        env:
          CLANG_BIN: "C:\\edk2-clang\\bin\\"
          BASETOOLS_MINGW_PATH: "C:\\edk2-clang\\bin\\"
        run: |
          PATH=%CLANG_BIN%;%PATH%
          edksetup.bat Mingw-w64
          build -a ${{ matrix.build_arch }} -b ${{ matrix.build_type }} -t CLANGPDB -p "${{ matrix.build_package }}"
        if: always()
      - name: Upload CLANGPDB-Mingw Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Windows CLANGPDB-Mingw Logs (${{ join(matrix.*, ' - ') }})"
          path: |
            Build/*.txt
            Build/*.log
        if: always()
      - name: Remove Build Directory CLANGPDB-Mingw
        shell: cmd
        run: rmdir /s /q Build
        if: always()
      - name: 'Build Packages CLANGDWARF-Mingw'
        shell: cmd
        env:
          CLANG_BIN: "C:\\llvm-mingw-20250709-ucrt-x86_64\\bin\\"
        run: |
          PATH=%CLANG_BIN%;%PATH%
          set
          stuart_ci_build -c ".pytool/CISettings.py" -a ${{ matrix.build_arch }} -t ${{ matrix.build_type }} TOOL_CHAIN_TAG=CLANGDWARF -p "${{ matrix.build_package }}" -v
        if: always()
      - name: Upload CLANGDWARF-Mingw Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Windows CLANGDWARF-Mingw Logs (${{ join(matrix.*, ' - ') }})"
          path: |
            Build/*.txt
            Build/*.log
        if: always()
      - name: Remove Build Directory CLANGDWARF-Mingw
        shell: cmd
        run: rmdir /s /q Build
        if: always()
      - name: 'Build Packages CLANGPDB-VS'
        shell: cmd
        env:
          CLANG_BIN: "C:\\Program Files\\LLVM\\bin\\"
        run: |
          PATH=%CLANG_BIN%;%PATH%
          set
          stuart_ci_build -c ".pytool/CISettings.py" -a ${{ matrix.build_arch }} -t ${{ matrix.build_type }} TOOL_CHAIN_TAG=CLANGPDB -p "${{ matrix.build_package }}" -v
        if: always()
      - name: Upload CLANGPDB-VS Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Windows CLANGPDB-VS Logs (${{ join(matrix.*, ' - ') }})"
          path: |
            Build/*.txt
            Build/*.log
        if: always()

  build_linux_clang:
    needs: [build_linux_clang_precheck, build_linux_clang_ovmf_precheck]
    name: Build Linux (${{ join(matrix.*, ' - ') }})
    runs-on: ubuntu-latest
    container: ghcr.io/mdkinney/containers/fedora-43-build:latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - DEBUG
          - RELEASE
        build_arch:
          - IA32
          - X64
        build_package:
          - CryptoPkg,ArmPkg,ArmPlatformPkg,DynamicTablesPkg,EmbeddedPkg,FatPkg,FmpDevicePkg,NetworkPkg,RedfishPkg,PcAtChipsetPkg,MdeModulePkg,MdePkg,IntelFsp2Pkg,IntelFsp2WrapperPkg,UefiCpuPkg,PrmPkg,SecurityPkg,ShellPkg,SignedCapsulePkg,SourceLevelDebugPkg,UnitTestFrameworkPkg,StandaloneMmPkg
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ensure safe directory for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Cache pip modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pip-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: 'Install/Upgrade pip modules'
        run: |
          pip install --upgrade pip
          pip install --upgrade -r pip-requirements.txt
      - name: 'Clone Submodules'
        run: stuart_setup -c ".pytool/CISettings.py" TOOL_CHAIN_TAG=CLANGPDB
      - name: 'Download External Dependencies'
        run: stuart_update -c ".pytool/CISettings.py" TOOL_CHAIN_TAG=CLANGPDB
      - name: 'Build BaseTools'
        env:
          CC: clang
          CXX: clang++
        run: python3 BaseTools/Edk2ToolsBuild.py -t GCC
      - name: 'Build Packages CLANGPDB'
        run: stuart_ci_build -c ".pytool/CISettings.py" -a ${{ matrix.build_arch }} -t ${{ matrix.build_type }} TOOL_CHAIN_TAG=CLANGPDB -p "${{ matrix.build_package }}"
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Linux Logs (${{ matrix.build_arch}} - ${{ matrix.build_type }})"
          path: |
            Build/*.txt
            Build/*.log
        if: always()

  build_linux_noopt_unit_tests:
    needs: [build_linux_clang_precheck, build_linux_clang_ovmf_precheck]
    name: Build Linux CLANGDWARF NOOPT unit tests
    runs-on: ubuntu-latest
    container: ghcr.io/mdkinney/containers/fedora-43-build:latest
    steps:
      - name: Install ASAN libs
        run: sudo dnf install compiler-rt -y
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ensure safe directory for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Cache pip modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pip-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: 'Install/Upgrade pip modules'
        run: |
          pip install --upgrade pip
          pip install --upgrade -r pip-requirements.txt
      - name: 'Clone Submodules'
        run: stuart_setup -c ".pytool/CISettings.py" TOOL_CHAIN_TAG=CLANGDWARF
      - name: 'Download External Dependencies'
        run: stuart_update -c ".pytool/CISettings.py" TOOL_CHAIN_TAG=CLANGDWARF
      - name: 'Build BaseTools'
        env:
          CC: clang
          CXX: clang++
        run: python3 BaseTools/Edk2ToolsBuild.py -t GCC
      - name: 'Build Packages CLANGDWARF NOOPT'
        run: stuart_ci_build -c ".pytool/CISettings.py" -a X64 -t NOOPT TOOL_CHAIN_TAG=CLANGDWARF
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Linux CLANGDWARF NOOPT Unit Test Logs"
          path: |
            Build/*.txt
            Build/*.log
        if: always()

  build_windows_noopt_unit_tests:
    needs: [build_linux_noopt_unit_tests]
    name: Build Windows (${{ join(matrix.*, ' - ') }})
    runs-on: windows-latest
    env:
      CLANG_BIN: "C:\\Program Files\\LLVM\\bin\\"
    strategy:
      fail-fast: false
      matrix:
        build_package:
          - CryptoPkg,FatPkg,FmpDevicePkg,PcAtChipsetPkg,PrmPkg,SourceLevelDebugPkg,UnitTestFrameworkPkg,StandaloneMmPkg
          - ArmPkg,ArmPlatformPkg,DynamicTablesPkg,EmbeddedPkg,NetworkPkg,RedfishPkg,MdeModulePkg,MdePkg,IntelFsp2Pkg,IntelFsp2WrapperPkg,UefiCpuPkg,SecurityPkg,ShellPkg,SignedCapsulePkg
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ensure safe directory for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install CLANG 20.1.8
        shell: cmd
        run: |
          curl -SL --output llvm_install.exe https://github.com/llvm/llvm-project/releases/download/llvmorg-20.1.8/LLVM-20.1.8-win64.exe
          llvm_install.exe /S
      - name: Install OpenCppCoverage
        shell: cmd
        run: |
          choco install -y OpenCppCoverage
      - name: Setup
        shell: powershell
        run: |
          "" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          "C:\Program Files\OpenCppCoverage" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: 'pip-requirements.txt'
      - name: Cache pip modules
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('pip-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: 'Install/Upgrade pip modules'
        run: |
          pip install --upgrade pip
          pip install --upgrade -r pip-requirements.txt
      - name: 'Clone Submodules'
        run: stuart_setup -c ".pytool/CISettings.py" TOOL_CHAIN_TAG=CLANGPDB
      - name: 'Download External Dependencies'
        run: stuart_update -c ".pytool/CISettings.py" TOOL_CHAIN_TAG=CLANGPDB
      - name: 'Build BaseTools'
        run: python BaseTools/Edk2ToolsBuild.py -t VS2022
      - name: 'Build Packages CLANGPDB'
        run: stuart_ci_build -c ".pytool/CISettings.py" -a X64 -t NOOPT TOOL_CHAIN_TAG=CLANGPDB -p "${{ matrix.build_package }}"
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Windows CLANGPDB Unit Test Logs (${{ join(matrix.*, ' - ') }})"
          path: |
            Build/*.txt
            Build/*.log
        if: always()
