# @file
# A workflow that builds packages using clang and upload it's artifacts.
#
# Copyright (c) Intel Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: CLANG Build

on:
  workflow_dispatch:

jobs:
  build_windows_clang:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ensure safe directory for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install CLANG 20.1.0
        shell: cmd
        run: |
          choco install llvm --version=20.1.0 -y
          refreshenv
      - name: Install make
        shell: cmd
        run: |
          choco install make -y
          refreshenv
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: 'Install/Upgrade pip modules'
        run: |
          pip install --upgrade pip
          pip install --upgrade -r pip-requirements.txt
      - name: 'Clone Submodules'
        run: stuart_setup -c ".pytool/CISettings.py" TOOL_CHAIN_TAG=CLANGPDB
      - name: 'Download External Dependencies'
        run: stuart_update -c ".pytool/CISettings.py" TOOL_CHAIN_TAG=CLANGPDB
      - name: 'Build BaseTools'
        run: python BaseTools/Edk2ToolsBuild.py -t VS2022
      - name: 'Build Packages CLANGDWARF'
        run: stuart_ci_build -c ".pytool/CISettings.py" -a X64 -t DEBUG TOOL_CHAIN_TAG=CLANGDWARF
        if: always()
      - name: 'Rename log file CLANGDWARF'
        run: mv Build/CI_BUILDLOG.txt Build/CI_BUILDLOG_WINDOWS_CLANGDWARF.txt
        if: always()
      - name: 'Build Packages CLANGPDB'
        run: stuart_ci_build -c ".pytool/CISettings.py" -a X64 -t DEBUG TOOL_CHAIN_TAG=CLANGPDB
        if: always()
      - name: 'Rename log file CLANGPDB'
        run: mv Build/CI_BUILDLOG.txt Build/CI_BUILDLOG_WINDOWS_CLANGPDB.txt
        if: always()
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Logs"
          path: |
            Build/*.txt
            BaseTools/BaseToolsBuild/*
        if: always()

  build_linux_clang:
    name: Build Linux
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tianocore/containers/ubuntu-24-dev:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ensure safe directory for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: 'Install/Upgrade pip modules'
        run: |
          pip install --upgrade pip
          pip install --upgrade -r pip-requirements.txt
      - name: 'Clone Submodules'
        run: stuart_setup -c ".pytool/CISettings.py" TOOL_CHAIN_TAG=CLANGDWARF
      - name: 'Download External Dependencies'
        run: stuart_update -c ".pytool/CISettings.py" TOOL_CHAIN_TAG=CLANGDWARF
      - name: 'Build BaseTools'
        run: python BaseTools/Edk2ToolsBuild.py -t GCC
      - name: 'Build Packages CLANGPDB'
        run: stuart_ci_build -c ".pytool/CISettings.py" -a X64 -t DEBUG TOOL_CHAIN_TAG=CLANGPDB
        if: always()
      - name: 'Rename build logCLANGPDB'
        run: mv Build/CI_BUILDLOG.txt Build/CI_BUILDLOG_LINUX_CLANGPDB.txt
        if: always()
      - name: 'Build Packages CLANGDWARF'
        run: stuart_ci_build -c ".pytool/CISettings.py" -a X64 -t DEBUG TOOL_CHAIN_TAG=CLANGDWARF
        if: always()
      - name: 'Rename build log CLANGDWARF'
        run: mv Build/CI_BUILDLOG.txt Build/CI_BUILDLOG_LINUX_CLANGDWARF.txt
        if: always()
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: Upload Logs
          path: |
            Build/*.txt
            BaseTools/BaseToolsBuild/*
        if: always()
