## @file
# Run PatchCheck on all commits in a pull request
#
# Copyright (c) 2024, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

name: PatchCheck

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - CiEnabled

jobs:
  patchcheck:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Install Python Dependencies
        run: pip install -r pip-requirements.txt
      - name: PatchCheck
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'ignore-multi-package') }}
        run: python BaseTools/Scripts/PatchCheck.py ${{ github.event.pull_request.base.sha }}..
      - name: PatchCheck --ignore-multi-package
        if: ${{ contains(github.event.pull_request.labels.*.name, 'ignore-multi-package') }}
        run: python BaseTools/Scripts/PatchCheck.py --ignore-multi-package ${{ github.event.pull_request.base.sha }}..
