## @file
# A workflow using Ubuntu to determine lists of packages to test based on files
# modified in a pull-request and optionally perform patch checks on the
# commits in a pull-request
#
# Copyright (C) 2025 Intel Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: Ubuntu Set Package Lists and Patch Check

on:
  workflow_call:
    inputs:
      default-package-lists:
        description: 'Default list of package lists to test.'
        required: false
        type: string
        default: '["ArmPkg,ArmPlatformPkg,ArmVirtPkg,OvmfPkg,DynamicTablesPkg,EmbeddedPkg,MdeModulePkg,MdePkg,CryptoPkg", "IntelFsp2Pkg,IntelFsp2WrapperPkg,UefiCpuPkg,PrmPkg,NetworkPkg,SecurityPkg,ShellPkg,FmpDevicePkg,FatPkg,RedfishPkg,PcAtChipsetPkg,SignedCapsulePkg,SourceLevelDebugPkg,UnitTestFrameworkPkg,StandaloneMmPkg,EmulatorPkg"]'
      run-patch-check:
        description: 'Whether to run PatchCheck on the PR.'
        required: false
        type: boolean
        default: false
    outputs:
      package-lists:
        description: 'List of package lists to test.'
        value: ${{ steps.set-package-lists.outputs.package-lists }}

jobs:
  set_package_lists:
    name: Set Package Lists
    runs-on: ubuntu-latest
    steps:
      - name: Use Default Package Lists
        if: github.event_name != 'pull_request'
        run: |
          echo "LOCAL_PACKAGE_LISTS=${{ toJSON(inputs.default-package-lists) }}" >> $GITHUB_ENV
      - name: Checkout Reference
        if: github.event_name != 'pull_request'
        #
        # If not PR, then use default checkout settings with fetch-depth of 1
        #
        uses: actions/checkout@v6
      - name: Get Number of Commit in PR
        if: github.event_name == 'pull_request'
        run: |
          echo "PR_COMMIT_COUNT=$((${{ github.event.pull_request.commits }} + 1))" >> $GITHUB_ENV
      - name: Checkout Pull Request
        if: github.event_name == 'pull_request'
        #
        # Checkout PR with fetch-depth of number of commits in PR + 1
        # This allows patch check to evaluate all commits in the PR, and for
        # stuart_pr_eval to evaluate the files modified over the entire PR.
        #
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ env.PR_COMMIT_COUNT }}
      - name: Ensure safe directory for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install Python in venv
        uses: ./.github/actions/linux-install-python-venv
        with:
          python-version: '3.12'
          pip-requirements: 'pip-requirements.txt'
          cache-name-suffix: '-set-package-lists'
      - name: Run stuart_pr_eval to generate Package List
        if: github.event_name == 'pull_request'
        run: |
          git log --oneline -n 10
          stuart_pr_eval -c .pytool/CISettings.py --pr-target HEAD~${{ github.event.pull_request.commits }} --output-csv-format-string {pkgcsv} -v
          PR_EVAL_LIST=$(stuart_pr_eval -c .pytool/CISettings.py --pr-target HEAD~${{ github.event.pull_request.commits }} --output-csv-format-string {pkgcsv})
          PR_EVAL_LIST=[\"$PR_EVAL_LIST\"]
          echo "PR_EVAL_LIST=$PR_EVAL_LIST" >> $GITHUB_ENV
      - name: Use stuart_pr_eval Package List
        if: github.event_name == 'pull_request'
        run: |
          echo "LOCAL_PACKAGE_LISTS=${{ toJSON(env.PR_EVAL_LIST) }}" >> $GITHUB_ENV
      - name: Set Package Lists
        id: set-package-lists
        run: |
          echo "package-lists=$LOCAL_PACKAGE_LISTS" >> $GITHUB_OUTPUT
      - name: PatchCheck PR
        if: github.event_name == 'pull_request' && inputs.run-patch-check
        run: |
          python BaseTools/Scripts/PatchCheck.py HEAD~${{ github.event.pull_request.commits }}..HEAD
