# @file
# A workflow that builds packages using clang and upload it's artifacts.
#
# Copyright (c) Intel Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: CLANG Cache Submodules Build No Apt

on:
  workflow_dispatch:
  pull_request:
    branches:
      - sandbox/master

jobs:
  build_linux_pr_precheck:
    name: Linux PR Precheck
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mdkinney/containers/ubuntu-24-build:latest
    steps:
      - name: Checkout PR depth $(( ${{ github.event.pull_request.commits }} + 1 ))
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          fetch-depth: $(( ${{ github.event.pull_request.commits }} + 1 ))
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checkout HEAD depth 1
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Ensure safe directory for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Restore cached venv
        uses: actions/cache/restore@v4
        id: cache-venv
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('pip-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Create and install venv if cache missed
        shell: bash
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r pip-requirements.txt
      - name: Save venv cache
        uses: actions/cache/save@v4
        if: steps.cache-venv.outputs.cache-hit != 'true'
        with:
          path: .venv
          key: ${{ steps.cache-venv.outputs.cache-primary-key }}
      - name: Set PATH to use venv
        shell: bash
        run: echo "PATH=$PWD/.venv/bin:$PATH" >> $GITHUB_ENV
      - name: PatchCheck PR
        if: github.event_name == 'pull_request'
        run: python BaseTools/Scripts/PatchCheck.py ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
      - name: 'Download External Dependencies'
        run: stuart_update -c ".pytool/CISettings.py"
      - name: 'Generate List of Packages to Evaluate'
        if: github.event_name == 'pull_request'
        run: echo "pkgs_to_build=$(stuart_pr_eval -c .pytool/CISettings.py --pr-target ${{ github.event.pull_request.head.sha }} --output-csv-format-string {pkgcsv})" >> $GITHUB_ENV
      - name: 'Evaluate Packages'
        if: github.event_name == 'pull_request'
        run: stuart_ci_build -c ".pytool/CISettings.py" -t NO-TARGET -p ${pkgs_to_build}
      - name: Upload Linux PR Precheck Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Linux PR Precheck Logs
          path: |
            BaseTools/BaseToolsBuild/*.txt
            Build/**/BUILDLOG*.txt
            Build/*.txt
            Build/*.log
        if: always()

  build_linux_clang_no_target_precheck:
    name: Linux ${{ matrix.tool_chain_tag }} ${{ matrix.build_type }} PreCheck
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mdkinney/containers/ubuntu-24-build:latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - NO-TARGET
        tool_chain_tag:
          - CLANGPDB
        build_package:
          - ArmPkg,ArmPlatformPkg,ArmVirtPkg,OvmfPkg,DynamicTablesPkg,EmbeddedPkg,MdeModulePkg,MdePkg,CryptoPkg
          - IntelFsp2Pkg,IntelFsp2WrapperPkg,UefiCpuPkg,PrmPkg,NetworkPkg,SecurityPkg,ShellPkg,FmpDevicePkg,FatPkg,RedfishPkg,PcAtChipsetPkg,SignedCapsulePkg,SourceLevelDebugPkg,UnitTestFrameworkPkg,StandaloneMmPkg,EmulatorPkg
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ensure safe directory for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Run ubuntu-cache-no-apt composite action
        uses: ./.github/actions/ubuntu-cache-no-apt
      - name: PatchCheck PR
        if: github.event_name == 'pull_request'
        run: python BaseTools/Scripts/PatchCheck.py ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
      - name: 'Clone Submodules'
        run: stuart_setup -c ".pytool/CISettings.py"
      - name: 'Download External Dependencies'
        run: stuart_update -c ".pytool/CISettings.py"
      - name: 'Build BaseTools'
        env:
          CC: clang
          CXX: clang++
        run: python3 BaseTools/Edk2ToolsBuild.py -t ${{ matrix.tool_chain_tag }}
      - name: 'Build Packages ${{ matrix.build_type }}'
        run: stuart_ci_build -c ".pytool/CISettings.py" -t ${{ matrix.build_type }} -p "${{ matrix.build_package }}"
      - name: Upload Linux ${{ matrix.tool_chain_tag }} ${{ matrix.build_type }} Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Linux ${{ matrix.tool_chain_tag }} ${{ matrix.build_type }} Logs (${{ strategy.job-index }})"
          path: |
            BaseTools/BaseToolsBuild/*.txt
            Build/**/BUILDLOG*.txt
            Build/*.txt
            Build/*.log
        if: always()

  build_linux_clang_ovmf_precheck:
    name: Linux CLANGPDB CLANGDWARF PreCheck
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mdkinney/containers/ubuntu-24-build:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ensure safe directory for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Run ubuntu-cache-no-apt composite action
        uses: ./.github/actions/ubuntu-cache-no-apt
      - name: 'Clone Submodules'
        run: stuart_setup -c ".pytool/CISettings.py" TOOL_CHAIN_TAG=CLANGPDB
      - name: 'Download External Dependencies'
        run: stuart_update -c ".pytool/CISettings.py" TOOL_CHAIN_TAG=CLANGPDB
      - name: 'Build BaseTools'
        env:
          CC: clang
          CXX: clang++
        run: python3 BaseTools/Edk2ToolsBuild.py -t GCC
      - name: 'Build HelloWorld CLANGPDB CLANGDWARF'
        env:
          NASM_PREFIX: "${{ github.workspace }}/BaseTools/Bin/mu_nasm_extdep/Linux-x86-64/"
          IASL_PREFIX: "${{ github.workspace }}/BaseTools/Bin/edk2-acpica-iasl_extdep/Linux-x86/"
        run: |
          . ./edksetup.sh
          build -a IA32 -a X64 -t CLANGPDB -b DEBUG -b RELEASE -b NOOPT -p MdeModulePkg/MdeModulePkg.dsc -m MdeModulePkg/Application/HelloWorld/HelloWorld.inf -j Build/HelloWorldClangPdbBuild.log >NUL
          build -a IA32 -a X64 -a AARCH64 -a RISCV64 -t CLANGDWARF -b DEBUG -b RELEASE -b NOOPT -p MdeModulePkg/MdeModulePkg.dsc -m MdeModulePkg/Application/HelloWorld/HelloWorld.inf -j Build/HelloWorldClangDwarfBuild.log >NUL
      - name: 'Build UnitTestFrameworkPkg X64 Unit Tests'
        run: |
          stuart_ci_build -c ".pytool/CISettings.py" -a X64 -t NOOPT TOOL_CHAIN_TAG=CLANGDWARF -p UnitTestFrameworkPkg
      - name: 'Build UnitTestFrameworkPkg IA32 Unit Tests'
        env:
          NASM_PREFIX: "${{ github.workspace }}/BaseTools/Bin/mu_nasm_extdep/Linux-x86-64/"
          IASL_PREFIX: "${{ github.workspace }}/BaseTools/Bin/edk2-acpica-iasl_extdep/Linux-x86/"
        run: |
          . ./edksetup.sh
          build -a IA32 -t CLANGDWARF -b NOOPT -p UnitTestFrameworkPkg/Test/UnitTestFrameworkPkgHostTest.dsc -j Build/UnitTestFrameworkPkgHostTestIA32.log >NUL
      - name: 'Build EmulatorPkg X64 Host Module'
        env:
          NASM_PREFIX: "${{ github.workspace }}/BaseTools/Bin/mu_nasm_extdep/Linux-x86-64/"
          IASL_PREFIX: "${{ github.workspace }}/BaseTools/Bin/edk2-acpica-iasl_extdep/Linux-x86/"
        run: |
          . ./edksetup.sh
          build -a X64 -t CLANGDWARF -b DEBUG -p EmulatorPkg/EmulatorPkg.dsc -m EmulatorPkg/Unix/Host/Host.inf -j Build/EmulatorX64Build.log >NUL
      - name: 'Build EmulatorPkg IA32 Host Module'
        env:
          NASM_PREFIX: "${{ github.workspace }}/BaseTools/Bin/mu_nasm_extdep/Linux-x86-64/"
          IASL_PREFIX: "${{ github.workspace }}/BaseTools/Bin/edk2-acpica-iasl_extdep/Linux-x86/"
        run: |
          . ./edksetup.sh
          build -a IA32 -t CLANGDWARF -b DEBUG -p EmulatorPkg/EmulatorPkg.dsc -m EmulatorPkg/Unix/Host/Host.inf -j Build/EmulatorIA32Build.log >NUL
      - name: 'Build OVMF Platform'
        env:
          NASM_PREFIX: "${{ github.workspace }}/BaseTools/Bin/mu_nasm_extdep/Linux-x86-64/"
          IASL_PREFIX: "${{ github.workspace }}/BaseTools/Bin/edk2-acpica-iasl_extdep/Linux-x86/"
        run: |
          . ./edksetup.sh
          build -a IA32 -a X64 -t CLANGPDB -b DEBUG -p OvmfPkg/OvmfPkgIa32X64.dsc -D SMM_REQUIRE -j Build/OvmfIa32X64Build.log >NUL
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Linux CLANGPDB CLANGDWARF Precheck Logs"
          path: |
            BaseTools/BaseToolsBuild/*.txt
            Build/**/BUILDLOG*.txt
            Build/*.txt
            Build/*.log
        if: always()

