## @file
# A workflow using Ubuntu CLANG tools that builds packages and uploads artifacts.
#
# Firmware Build Support:             CLANGPDB/CLANGDWARF - IA32/X64
# Host-Based Unit Test Build Support: CLANGDWARF          - IA32/X64
# EmulatorPkg Build Support:          CLANGDWARF          - IA32/X64
#
# Copyright (C) 2025 Intel Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: Ubuntu CLANG 20.1.8 Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - sandbox/master
      - clang_ci_v5b

env:
  #
  # Package array that has similar execution times across 2 jobs.
  #
  PACKAGE_LISTS: '["ArmPkg,ArmPlatformPkg,ArmVirtPkg,OvmfPkg,EmbeddedPkg,MdeModulePkg,MdePkg,CryptoPkg", "DynamicTablesPkg,IntelFsp2Pkg,IntelFsp2WrapperPkg,UefiCpuPkg,PrmPkg,NetworkPkg,SecurityPkg,ShellPkg,FmpDevicePkg,FatPkg,RedfishPkg,PcAtChipsetPkg,SignedCapsulePkg,SourceLevelDebugPkg,UnitTestFrameworkPkg,StandaloneMmPkg,EmulatorPkg"]'

jobs:
  set_package_lists:
    name: Set Package Lists
    runs-on: ubuntu-latest
    outputs:
      package-lists: ${{ steps.set-package-lists.outputs.package-lists }}
    steps:
      - name: Use Default Package Lists
        if: github.event_name != 'pull_request'
        run: |
          echo "LOCAL_PACKAGE_LISTS=${{ toJSON(env.PACKAGE_LISTS) }}" >> $GITHUB_ENV
      - name: Get Number of Commit in PR
        if: github.event_name == 'pull_request'
        run: |
          echo "PR_COMMIT_COUNT=$((${{ github.event.pull_request.commits }} + 1))" >> $GITHUB_ENV
      - name: Checkout
        if: github.event_name == 'pull_request'
        #
        # Checkout PR with fetch-depth of number of commits in PR + 1
        # This allows patch check to evaluate all commits in the PR, and for
        # stuart_pr_eval to evaluate the files modified over the entire PR.
        #
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ env.PR_COMMIT_COUNT }}
      - name: Ensure safe directory for Git
        if: github.event_name == 'pull_request'
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install Python in venv
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/linux-install-python-venv
        with:
          python-version: '3.12'
      - name: Run stuart_pr_eval to generate Package List
        if: github.event_name == 'pull_request'
        run: |
          git log --oneline -n 10
          stuart_pr_eval -c .pytool/CISettings.py --pr-target HEAD~${{ env.PR_COMMIT_COUNT }} --output-csv-format-string {pkgcsv} -v
          PR_EVAL_LIST=$(stuart_pr_eval -c .pytool/CISettings.py --pr-target HEAD~${{ env.PR_COMMIT_COUNT }} --output-csv-format-string {pkgcsv})
          PR_EVAL_LIST=[\"$PR_EVAL_LIST\"]
          echo "PR_EVAL_LIST=$PR_EVAL_LIST" >> $GITHUB_ENV
      - name: Use stuart_pr_eval Package List
        if: github.event_name == 'pull_request'
        run: |
          echo "LOCAL_PACKAGE_LISTS=${{ toJSON(env.PR_EVAL_LIST) }}" >> $GITHUB_ENV
      - name: Set Package Lists
        id: set-package-lists
        run: |
          echo "package-lists=$LOCAL_PACKAGE_LISTS" >> $GITHUB_OUTPUT

  build_linux_clang_basic_acceptance_test:
    needs: set_package_lists
    uses: ./.github/workflows/ubuntu-clang-20-basic-acceptance-test.yml
    with:
      python-version: '3.12'
      stuart-ci-settings-file: '.pytool/CISettings.py'
      edk2-tools-build-params: '-t CLANGPDB'

  build_linux_clang_no_target_test:
    needs: set_package_lists
    uses: ./.github/workflows/ubuntu-clang-20-no-target-test.yml
    with:
      python-version: '3.12'
      stuart-ci-settings-file: '.pytool/CISettings.py'
      edk2-tools-build-params: '-t CLANGPDB'
      package-lists: ${{ needs.set_package_lists.outputs.package-lists }}

  build_linux_clang_packages_ia32_x64:
    needs: [set_package_lists, build_linux_clang_basic_acceptance_test, build_linux_clang_no_target_test]
    uses: ./.github/workflows/ubuntu-clang-20-package-build-test.yml
    with:
      python-version: '3.12'
      stuart-ci-settings-file: '.pytool/CISettings.py'
      edk2-tools-build-params: '-t CLANGPDB'
      build_type_list: '["DEBUG", "RELEASE"]'
      build_arch_list: '["IA32", "X64"]'
      tool_chain_tag_list: '["CLANGPDB", "CLANGDWARF"]'
      package-lists: ${{ needs.set_package_lists.outputs.package-lists }}

  build_linux_clangdwarf_aarch64_riscv64_packages:
    needs: [set_package_lists, build_linux_clang_basic_acceptance_test, build_linux_clang_no_target_test]
    uses: ./.github/workflows/ubuntu-clang-20-package-build-test.yml
    with:
      python-version: '3.12'
      stuart-ci-settings-file: '.pytool/CISettings.py'
      edk2-tools-build-params: '-t CLANGDWARF'
      build_type_list: '["DEBUG", "RELEASE"]'
      build_arch_list: '["AARCH64", "RISCV64"]'
      tool_chain_tag_list: '["CLANGDWARF"]'
      package-lists: ${{ needs.set_package_lists.outputs.package-lists }}

  build_linux_clangdwarf_noopt_unit_tests:
    needs: [set_package_lists, build_linux_clang_basic_acceptance_test, build_linux_clang_no_target_test]
    uses: ./.github/workflows/ubuntu-clang-20-package-build-test.yml
    with:
      python-version: '3.12'
      stuart-ci-settings-file: '.pytool/CISettings.py'
      edk2-tools-build-params: '-t CLANGDWARF'
      build_type_list: '["NOOPT"]'
      build_arch_list: '["X64"]'
      tool_chain_tag_list: '["CLANGDWARF", "GCC", "GCC5", "GCCNOLTO"]'
      package-lists: ${{ needs.set_package_lists.outputs.package-lists }}

  build_linux_clangdwarf_emulatorpkg:
    name: Build Linux CLANGDWARF EmulatorPkg
    needs: [set_package_lists, build_linux_clang_basic_acceptance_test, build_linux_clang_no_target_test]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mdkinney/containers/ubuntu-24-build:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Ensure safe directory for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Setup Linux CLANG Job
        uses: ./.github/actions/linux-setup-clang-job
        with:
          python-version: '3.12'
          stuart-ci-settings-file: '.pytool/CISettings.py'
          edk2-tools-build-params: '-t CLANGDWARF'
      - name: Build Linux CLANGDWARF EmulatorPkg X64 DEBUG
        run: |
          . ./edksetup.sh
          build -a X64 -t CLANGDWARF -b DEBUG   -p EmulatorPkg/EmulatorPkg.dsc -D NETWORK_ENABLE=FALSE -j Build/EmulatorX64DebugBuild.log >NUL
      - name: Build Linux CLANGDWARF EmulatorPkg X64 RELEASE
        run: |
          . ./edksetup.sh
          build -a X64 -t CLANGDWARF -b RELEASE -p EmulatorPkg/EmulatorPkg.dsc                         -j Build/EmulatorX64ReleaseBuild.log >NUL
      - name: Build Linux CLANGDWARF EmulatorPkg X64 NOOPT
        run: |
          . ./edksetup.sh
          build -a X64 -t CLANGDWARF -b NOOPT   -p EmulatorPkg/EmulatorPkg.dsc -D SECURE_BOOT_ENABLE   -j Build/EmulatorX64NooptBuild.log >NUL
      - name: Build Linux CLANGDWARF EmulatorPkg IA32 DEBUG
        run: |
          . ./edksetup.sh
          build -a IA32 -t CLANGDWARF -b DEBUG   -p EmulatorPkg/EmulatorPkg.dsc -D NETWORK_ENABLE=FALSE -j Build/EmulatorIA32DebugBuild.log >NUL
      - name: Build Linux CLANGDWARF EmulatorPkg IA32 RELEASE
        run: |
          . ./edksetup.sh
          build -a IA32 -t CLANGDWARF -b RELEASE -p EmulatorPkg/EmulatorPkg.dsc                         -j Build/EmulatorIA32ReleaseBuild.log >NUL
      - name: Build Linux CLANGDWARF EmulatorPkg IA32 NOOPT
        run: |
          . ./edksetup.sh
          build -a IA32 -t CLANGDWARF -b NOOPT   -p EmulatorPkg/EmulatorPkg.dsc -D SECURE_BOOT_ENABLE   -j Build/EmulatorIA32NooptBuild.log >NUL
      - name: Upload Linux CLANGDWARF EmulatorPkg Logs
        uses: actions/upload-artifact@v6
        with:
          name: Upload Linux CLANGDWARF EmulatorPkg Logs
          path: |
            BaseTools/BaseToolsBuild/*.txt
            Build/**/BUILDLOG*.txt
            Build/*.txt
            Build/*.log
        if: always()
