# @file
# A workflow that builds packages using clang and upload it's artifacts.
#
# Copyright (c) Intel Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: Windows Mingw edk2-clang 20.1.8 Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - sandbox/master

jobs:
  build_windows_clang:
    name: Build Windows (${{ join(matrix.*, ' - ') }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - DEBUG
          - RELEASE
        build_arch:
          - IA32
          - X64
        tool_chain_tag:
          - CLANGPDB
          - CLANGDWARF
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ensure safe directory for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Restore TianoCore Mingw CLANG 20.1.8
        id: cache-edk2-clang
        uses: actions/cache/restore@v4
        with:
          path: C:\edk2-clang
          key: ${{ runner.os }}-edk2-clang-20.1.8
          restore-keys: |
            ${{ runner.os }}-edk2-clang-20.1.8
      - name: Install TianoCore Mingw CLANG 20.1.8
        if: steps.cache-edk2-clang.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          curl -L -o EdkClangSetup-20.1.8.0.exe https://github.com/tianocore/edk2-edkrepo/releases/download/edkclang-v20.1.8/EdkClangSetup-20.1.8.0.exe
          EdkClangSetup-20.1.8.0.exe /silent
      - name: Save TianoCore Mingw CLANG 20.1.8
        if: steps.cache-edk2-clang.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: C:\edk2-clang
          key: ${{ steps.cache-edk2-clang.outputs.cache-primary-key }}
      - name: Add TianoCore Mingw CLANG to PATH
        shell: cmd
        run: |
          PATH=C:\edk2-clang\bin;%PATH%
          echo PATH=%PATH% >> %GITHUB_ENV%
      - name: Restore cached venv
        uses: actions/cache/restore@v4
        id: cache-venv
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('pip-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Set up Python 3.12
        if: steps.cache-venv.outputs.cache-hit != 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Create and install venv if cache missed
        shell: cmd
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          PATH=%GITHUB_WORKSPACE%\.venv\Scripts;%PATH%
          python -m pip install --upgrade pip
          pip install -r pip-requirements.txt
      - name: Save venv cache
        uses: actions/cache/save@v4
        if: steps.cache-venv.outputs.cache-hit != 'true'
        with:
          path: .venv
          key: ${{ steps.cache-venv.outputs.cache-primary-key }}
      - name: Activate venv
        shell: cmd
        run: |
          PATH=%GITHUB_WORKSPACE%\.venv\Scripts;%PATH%
          echo PATH=%PATH% >> %GITHUB_ENV%
          pip list
      - name: Restore submodules
        id: cache-submodules
        uses: actions/cache/restore@v4
        with:
          path: .git/modules
          key: ${{ runner.os }}-submodules-${{ hashFiles('.gitmodules') }}
          restore-keys: |
            ${{ runner.os }}-submodules-
      - name: 'Clone Submodules'
        run: stuart_setup -c ".pytool/CISettings.py"
      - name: Save submodules
        if: steps.cache-submodules.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: .git/modules
          key: ${{ steps.cache-submodules.outputs.cache-primary-key }}
      - name: 'Download External Dependencies'
        run: stuart_update -c ".pytool/CISettings.py"
      - name: 'Build BaseTools'
        env:
          CC: "clang"
          CXX: "clang++"
        run: python BaseTools\Edk2ToolsBuild.py -t ${{ matrix.tool_chain_tag }}
      - name: 'Build Packages ${{ matrix.tool_chain_tag }}-Mingw'
        shell: cmd
        env:
          CLANG_BIN: "C:\\edk2-clang\\bin\\"
          NASM_PREFIX: "${{ github.workspace }}\\BaseTools\\Bin\\mu_nasm_extdep\\Windows-x86-64\\"
          IASL_PREFIX: "${{ github.workspace }}\\BaseTools\\Bin\\edk2-acpica-iasl_extdep\\Windows-x86\\"
        run: |
          stuart_ci_build -c ".pytool/CISettings.py" -a ${{ matrix.build_arch }} -t ${{ matrix.build_type }} TOOL_CHAIN_TAG=${{ matrix.tool_chain_tag }}
      - name: Upload ${{ matrix.tool_chain_tag }}-Mingw Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Windows Mingw edk2-clang Logs (${{ join(matrix.*, ' - ') }})"
          path: |
            Build/**/BUILDLOG*.txt
            Build/*.log
        if: always()
