# @file
# A workflow that builds packages using clang and upload it's artifacts.
#
# Copyright (c) Intel Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: Windows VS LLVM 20.1.8 CLANG Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - sandbox/master

env:
  CLANG_BIN: "C:\\Program Files\\LLVM\\bin\\"
  NASM_PREFIX: "${{ github.workspace }}\\BaseTools\\Bin\\mu_nasm_extdep\\Windows-x86-64\\"
  IASL_PREFIX: "${{ github.workspace }}\\BaseTools\\Bin\\edk2-acpica-iasl_extdep\\Windows-x86\\"

jobs:
  build_windows_clang_ovmf_precheck:
    name: Build Windows VS CLANGPDB Precheck
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install LLVM 20.1.8
        uses: ./.github/actions/windows-install-llvm
        with:
          llvm_version: '20.1.8'
      - name: Install Python in venv
        uses: ./.github/actions/windows-install-python-venv
        with:
          python-version: '3.12'
      - name: Install Git Submodules from stuart_setup
        uses: ./.github/actions/windows-install-git-submodules
        with:
          stuart-ci-settings-file: '.pytool/CISettings.py'
      - name: 'Download External Dependencies'
        run: stuart_update -c ".pytool/CISettings.py"
      - name: 'Build BaseTools'
        run: python BaseTools/Edk2ToolsBuild.py -t VS2022
      - name: 'Build HelloWorld CLANGPDB'
        shell: cmd
        run: |
          call edksetup.bat VS2022
          build -a IA32 -a X64 -t CLANGPDB -b DEBUG -b RELEASE -b NOOPT -p MdeModulePkg/MdeModulePkg.dsc -m MdeModulePkg/Application/HelloWorld/HelloWorld.inf -j Build/HelloWorldClangPdbBuild.log >NUL
      - name: 'Build UnitTestFrameworkPkg X64 Unit Tests'
        env:
          CLANG_BIN: "C:\\Program Files\\LLVM\\bin\\"
        run: |
          stuart_ci_build -c ".pytool/CISettings.py" -a X64 -t NOOPT TOOL_CHAIN_TAG=CLANGPDB -p UnitTestFrameworkPkg
      - name: 'Build UnitTestFrameworkPkg IA32 Unit Tests'
        shell: cmd
        run: |
          call edksetup.bat VS2022
          build -a IA32 -t CLANGPDB -b NOOPT -p UnitTestFrameworkPkg/Test/UnitTestFrameworkPkgHostTest.dsc -j Build/UnitTestFrameworkPkgHostTestIA32.log >NUL
      - name: 'Build EmulatorPkg X64 Host Module'
        shell: cmd
        run: |
          call edksetup.bat VS2022
          call build -a X64 -t CLANGPDB -b DEBUG   -p EmulatorPkg/EmulatorPkg.dsc -m EmulatorPkg/Win/Host/WinHost.inf -j Build/EmulatorX64DebugBuild.log >NUL
          call build -a X64 -t CLANGPDB -b RELEASE -p EmulatorPkg/EmulatorPkg.dsc -m EmulatorPkg/Win/Host/WinHost.inf -j Build/EmulatorX64ReleaseBuild.log >NUL
          call build -a X64 -t CLANGPDB -b NOOPT   -p EmulatorPkg/EmulatorPkg.dsc -m EmulatorPkg/Win/Host/WinHost.inf -j Build/EmulatorX64NooptBuild.log >NUL
      - name: 'Build EmulatorPkg IA32 Host Module'
        shell: cmd
        run: |
          call edksetup.bat VS2022
          call build -a IA32 -t CLANGPDB -b DEBUG   -p EmulatorPkg/EmulatorPkg.dsc -m EmulatorPkg/Win/Host/WinHost.inf -j Build/EmulatorIA32DebugBuild.log >NUL
          call build -a IA32 -t CLANGPDB -b RELEASE -p EmulatorPkg/EmulatorPkg.dsc -m EmulatorPkg/Win/Host/WinHost.inf -j Build/EmulatorIA32ReleaseBuild.log >NUL
          call build -a IA32 -t CLANGPDB -b NOOPT   -p EmulatorPkg/EmulatorPkg.dsc -m EmulatorPkg/Win/Host/WinHost.inf -j Build/EmulatorIA32NooptBuild.log >NUL
      - name: 'Build OVMF Platform'
        shell: cmd
        run: |
          call edksetup.bat VS2022
          build -a IA32 -a X64 -t CLANGPDB -b DEBUG -p OvmfPkg/OvmfPkgIa32X64.dsc -D SMM_REQUIRE -j Build/OvmfIa32X64Build.log >NUL
      - name: Upload Windows VS CLANGPDB Precheck Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Windows VS CLANGPDB Precheck Logs"
          path: |
            BaseTools/BaseToolsBuild/*.txt
            Build/**/BUILDLOG*.txt
            Build/*.txt
            Build/*.log
        if: always()

  build_windows_clang:
    name: Build Windows VS CLANGPDB Packages (${{ join(matrix.*, ' - ') }})
    needs: build_windows_clang_ovmf_precheck
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - DEBUG
          - RELEASE
        build_arch:
          - IA32
          - X64
        tool_chain_tag:
          - CLANGPDB
        build_package:
          - CryptoPkg,FatPkg,FmpDevicePkg,PcAtChipsetPkg,PrmPkg,SourceLevelDebugPkg,UnitTestFrameworkPkg,StandaloneMmPkg,SignedCapsulePkg
          - ArmPkg,ArmPlatformPkg,DynamicTablesPkg,EmbeddedPkg,NetworkPkg,RedfishPkg,MdeModulePkg,MdePkg,IntelFsp2Pkg,IntelFsp2WrapperPkg,UefiCpuPkg,SecurityPkg,ShellPkg
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install LLVM 20.1.8
        uses: ./.github/actions/windows-install-llvm
        with:
          llvm_version: '20.1.8'
      - name: Install Python in venv
        uses: ./.github/actions/windows-install-python-venv
        with:
          python-version: '3.12'
      - name: Install Git Submodules from stuart_setup
        uses: ./.github/actions/windows-install-git-submodules
        with:
          stuart-ci-settings-file: '.pytool/CISettings.py'
      - name: 'Download External Dependencies'
        run: stuart_update -c ".pytool/CISettings.py"
      - name: 'Build BaseTools'
        run: python BaseTools/Edk2ToolsBuild.py -t VS2022
      - name: 'Build Packages ${{ matrix.tool_chain_tag }}-VS'
        shell: cmd
        run: |
          stuart_ci_build -c ".pytool/CISettings.py" -a ${{ matrix.build_arch }} -t ${{ matrix.build_type }} TOOL_CHAIN_TAG=${{ matrix.tool_chain_tag }} -p "${{ matrix.build_package }}"
      - name: Upload Windows VS CLANGPDB Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Windows VS CLANGPDB Logs (${{ matrix.build_arch }}-${{ matrix.build_type }}-${{ matrix.tool_chain_tag }}-${{ strategy.job-index }})"
          path: |
            BaseTools/BaseToolsBuild/*.txt
            Build/**/BUILDLOG*.txt
            Build/*.txt
            Build/*.log
        if: always()

  build_windows_clang_noopt_unit_tests:
    name: Build Windows VS CLANGPDB Unit Test (${{ join(matrix.*, ' - ') }})
    needs: build_windows_clang_ovmf_precheck
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - NOOPT
        build_arch:
          - X64
        tool_chain_tag:
          - CLANGPDB
        build_package:
          - CryptoPkg,FatPkg,FmpDevicePkg,PcAtChipsetPkg,PrmPkg,SourceLevelDebugPkg,UnitTestFrameworkPkg,StandaloneMmPkg,SignedCapsulePkg
          - ArmPkg,ArmPlatformPkg,DynamicTablesPkg,EmbeddedPkg,NetworkPkg,RedfishPkg,MdeModulePkg,MdePkg,IntelFsp2Pkg,IntelFsp2WrapperPkg,UefiCpuPkg,SecurityPkg,ShellPkg
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install LLVM 20.1.8
        uses: ./.github/actions/windows-install-llvm
        with:
          llvm_version: '20.1.8'
      - name: Install Python in venv
        uses: ./.github/actions/windows-install-python-venv
        with:
          python-version: '3.12'
      - name: Install Git Submodules from stuart_setup
        uses: ./.github/actions/windows-install-git-submodules
        with:
          stuart-ci-settings-file: '.pytool/CISettings.py'
      - name: 'Download External Dependencies'
        run: stuart_update -c ".pytool/CISettings.py"
      - name: 'Build BaseTools'
        run: python BaseTools/Edk2ToolsBuild.py -t VS2022
      - name: 'Build Packages ${{ matrix.tool_chain_tag }}-VS'
        shell: cmd
        run: |
          stuart_ci_build -c ".pytool/CISettings.py" -a ${{ matrix.build_arch }} -t ${{ matrix.build_type }} TOOL_CHAIN_TAG=${{ matrix.tool_chain_tag }} -p "${{ matrix.build_package }}"
      - name: Upload Windows VS CLANGPDB Unit Test Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Windows VS CLANGPDB Unit Test Logs (${{ matrix.build_arch }}-${{ matrix.build_type }}-${{ matrix.tool_chain_tag }}-${{ strategy.job-index }})"
          path: |
            BaseTools/BaseToolsBuild/*.txt
            Build/**/BUILDLOG*.txt
            Build/*.txt
            Build/*.log
        if: always()

  build_windows_clang_emulatorpkg:
    name: Build Windows VS CLANGPDB EmulatorPkg
    needs: build_windows_clang_ovmf_precheck
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install LLVM 20.1.8
        uses: ./.github/actions/windows-install-llvm
        with:
          llvm_version: '20.1.8'
      - name: Install Python in venv
        uses: ./.github/actions/windows-install-python-venv
        with:
          python-version: '3.12'
      - name: Install Git Submodules from stuart_setup
        uses: ./.github/actions/windows-install-git-submodules
        with:
          stuart-ci-settings-file: '.pytool/CISettings.py'
      - name: 'Download External Dependencies'
        run: stuart_update -c ".pytool/CISettings.py"
      - name: 'Build BaseTools'
        run: python BaseTools/Edk2ToolsBuild.py -t VS2022
      - name: 'Build EmulatorPkg X64 Host Module'
        shell: cmd
        run: |
          call edksetup.bat VS2022
          call build -a X64 -t CLANGPDB -b NOOPT   -p EmulatorPkg/EmulatorPkg.dsc -D SECURE_BOOT_ENABLE -D REDFISH_ENABLE -j Build/EmulatorX64NooptBuild.log >NUL
          call build -a X64 -t CLANGPDB -b DEBUG   -p EmulatorPkg/EmulatorPkg.dsc -D NETWORK_ENABLE=FALSE                 -j Build/EmulatorX64DebugBuild.log >NUL
          call build -a X64 -t CLANGPDB -b RELEASE -p EmulatorPkg/EmulatorPkg.dsc                                         -j Build/EmulatorX64ReleaseBuild.log >NUL
      - name: 'Build EmulatorPkg IA32 Host Module'
        shell: cmd
        run: |
          call edksetup.bat VS2022
          call build -a IA32 -t CLANGPDB -b NOOPT   -p EmulatorPkg/EmulatorPkg.dsc -D SECURE_BOOT_ENABLE -D REDFISH_ENABLE -j Build/EmulatorIA32NooptBuild.log >NUL
          call build -a IA32 -t CLANGPDB -b DEBUG   -p EmulatorPkg/EmulatorPkg.dsc -D NETWORK_ENABLE=FALSE                 -j Build/EmulatorIA32DebugBuild.log >NUL
          call build -a IA32 -t CLANGPDB -b RELEASE -p EmulatorPkg/EmulatorPkg.dsc                                         -j Build/EmulatorIA32ReleaseBuild.log >NUL
      - name: Upload Windows VS CLANGPDB EmulatorPkg Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Windows VS CLANGPDB EmulatorPkg Logs"
          path: |
            BaseTools/BaseToolsBuild/*.txt
            Build/**/BUILDLOG*.txt
            Build/*.txt
            Build/*.log
        if: always()
