# @file
# A workflow that builds packages using clang and upload it's artifacts.
#
# Copyright (c) Intel Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: Windows Mingw edk2-clang 20.1.8 Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - sandbox/master

jobs:
  build_windows_clang:
    name: Build Windows (${{ join(matrix.*, ' - ') }})
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - DEBUG
        build_arch:
          - X64
        build_package:
          - FatPkg
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ensure safe directory for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Restore cached venv
        uses: actions/cache/restore@v4
        id: cache-venv
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('pip-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Set up Python 3.12
        if: steps.cache-venv.outputs.cache-hit != 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Create and install venv if cache missed
        shell: cmd
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          PATH=%GITHUB_WORKSPACE%\.venv\Scripts;%PATH%
          python -m pip install --upgrade pip
          pip install -r pip-requirements.txt
      - name: Save venv cache
        uses: actions/cache/save@v4
        if: steps.cache-venv.outputs.cache-hit != 'true'
        with:
          path: .venv
          key: ${{ steps.cache-venv.outputs.cache-primary-key }}
      - name: Activate venv
        shell: cmd
        run: |
          PATH=%GITHUB_WORKSPACE%\.venv\Scripts;%PATH%
          echo PATH=%PATH% >> %GITHUB_ENV%
          pip list
          where make
          where mingw32-make
          rename c:\mingw64\bin\make.exe donotuse-make.exe
          rename c:\mingw64\bin\mingw32-make.exe donotuse-mingw32-make.exe
          where make
          where mingw32-make
          dir c:\mingw64\bin
          fsutil fsinfo volumeinfo c:
          fsutil fsinfo volumeinfo d:
      - name: Restore TianoCore Mingw CLANG
        id: cache-edk2-clang
        uses: actions/cache/restore@v4
        with:
          path: C:\edk2-clang
          key: ${{ runner.os }}-edk2-clang-20.1.8
          restore-keys: |
            ${{ runner.os }}-edk2-clang-20.1.8
      - name: Install TianoCore Mingw CLANG 20.1.8
        if: steps.cache-edk2-clang.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          curl -L -o EdkClangSetup-20.1.8.0.exe https://github.com/tianocore/edk2-edkrepo/releases/download/edkclang-v20.1.8/EdkClangSetup-20.1.8.0.exe
          EdkClangSetup-20.1.8.0.exe /silent
      - name: Save TianoCore Mingw CLANG
        if: steps.cache-edk2-clang.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: C:\edk2-clang
          key: ${{ steps.cache-edk2-clang.outputs.cache-primary-key }}
      - name: Restore submodules
        id: cache-submodules
        uses: actions/cache/restore@v4
        with:
          path: .git/modules
          key: ${{ runner.os }}-submodules-${{ hashFiles('.gitmodules') }}
          restore-keys: |
            ${{ runner.os }}-submodules-
      - name: 'Clone Submodules'
        run: stuart_setup -c ".pytool/CISettings.py"
      - name: Save submodules
        if: steps.cache-submodules.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: .git/modules
          key: ${{ steps.cache-submodules.outputs.cache-primary-key }}
      - name: 'Download External Dependencies'
        run: stuart_update -c ".pytool/CISettings.py"
      - name: Build Edk2 BaseTools
        shell: cmd
        run: |
          dir C:\edk2-clang\bin
          PATH=C:\edk2-clang\bin;%PATH%
          set CLANG_BIN=C:\edk2-clang\bin\
          set BASETOOLS_MINGW_PATH=C:\edk2-clang
          set HOST_ARCH=X64
          set MSYS_NO_PATHCONV=1
          call edksetup.bat Mingw-w64 ForceRebuild
          set
          where mingw32-make
          call build -a X64 -t CLANGPDB -b DEBUG -p FatPkg\FatPkg.dsc GenMake
          mingw32-make -f Build\Fat\DEBUG_CLANGPDB\X64\FatPkg\EnhancedFatDxe\Fat\GNUmakefile -d
          call build -a X64 -t CLANGPDB -b DEBUG -p FatPkg\FatPkg.dsc -j Build\BuildFatPkg.log -v
      - name: 'Build BaseTools'
        run: python BaseTools/Edk2ToolsBuild.py -t VS2022
      - name: 'Build Packages CLANGPDB-Mingw'
        shell: cmd
        env:
          CLANG_BIN: "C:\\edk2-clang\\bin\\"
        run: |
          PATH=C:\edk2-clang\bin;%PATH%
          stuart_ci_build -c ".pytool/CISettings.py" -a ${{ matrix.build_arch }} -t ${{ matrix.build_type }} TOOL_CHAIN_TAG=CLANGPDB -p "${{ matrix.build_package }}" -v
      - name: Upload CLANGPDB-Mingw Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Windows CLANGPDB-Mingw Logs (${{ join(matrix.*, ' - ') }})"
          path: |
            Build/**/*
        if: always()
