## @file
# A workflow using Windows to show package lists.
#
# Copyright (C) 2025 Intel Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: Windows CLANG 20.1.8 Show Package Lists

on:
  workflow_call:
    inputs:
      build_type_list:
        description: 'List of build types to test.'
        required: true
        type: string
        default: '["DEBUG", "RELEASE"]'
      build_arch_list:
        description: 'List of build architectures to test.'
        required: true
        type: string
        default: '["IA32", "X64"]'
      tool_chain_tag_list:
        description: 'List of tool chain tags to test.'
        required: true
        type: string
        default: '["CLANGPDB", "CLANGDWARF"]'
      package-lists:
        description: 'List of package lists to test.'
        required: true
        type: string
        default: '["ArmPkg,ArmPlatformPkg,ArmVirtPkg,OvmfPkg,DynamicTablesPkg,EmbeddedPkg,MdeModulePkg,MdePkg,CryptoPkg", "IntelFsp2Pkg,IntelFsp2WrapperPkg,UefiCpuPkg,PrmPkg,NetworkPkg,SecurityPkg,ShellPkg,FmpDevicePkg,FatPkg,RedfishPkg,PcAtChipsetPkg,SignedCapsulePkg,SourceLevelDebugPkg,UnitTestFrameworkPkg,StandaloneMmPkg,EmulatorPkg"]'

jobs:
  windows_show_package_lists:
    name: Show Package Lists
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: ${{ fromJSON(inputs.build_type_list) }}
        build_arch: ${{ fromJSON(inputs.build_arch_list) }}
        tool_chain_tag: ${{ fromJSON(inputs.tool_chain_tag_list) }}
        build_package: ${{ fromJSON(inputs.package-lists) }}
    steps:
      - name: Show Matrix values
        run: |
          echo "Build Type:    ${{ matrix.build_type }}"
          echo "Build Arch:    ${{ matrix.build_arch }}"
          echo "Tool Chain:    ${{ matrix.tool_chain_tag }}"
          echo "Build Package: ${{ matrix.build_package }}"
