## @file
# A workflow using Windows LLVM MINGW CLANG tools that builds packages and
# uploads artifacts.
#
# Firmware Build Support:             CLANGDWARF - IA32/X64
# Host-Based Unit Test Build Support: CLANGDWARF - IA32/X64
# EmulatorPkg Build Support:          CLANGDWARF - IA32/X64
#
# Copyright (C) 2025 Intel Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

name: Windows LLVM MINGW CLANG 20.1.8 Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - sandbox/master

jobs:
  build_windows_llvm_mingw_clang_precheck:
    name: Build Windows LLVM MINGW CLANG Precheck
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Windows LLVM MINGW CLANG Job
        uses: ./.github/actions/windows-setup-mingw-llvm-clang-job
        with:
          llvm_version: '20250709'
          llvm_install_path: 'C:\llvm-mingw-20250709-ucrt-x86_64'
          python-version: '3.12'
          stuart-ci-settings-file: '.pytool/CISettings.py'
          edk2-tools-build-params: '-a X64 -t CLANGDWARF'
      - name: Build HelloWorld CLANGDWARF
        shell: cmd
        run: |
          call edksetup.bat Mingw-w64
          call build -a IA32 -a X64 -t CLANGDWARF -b DEBUG -b RELEASE -b NOOPT -p MdeModulePkg/MdeModulePkg.dsc -m MdeModulePkg/Application/HelloWorld/HelloWorld.inf -j Build/HelloWorldClangDwarfBuild.log >NUL
      - name: Build UnitTestFrameworkPkg X64 Unit Tests
        run: |
          stuart_ci_build -c ".pytool/CISettings.py" -a X64 -t NOOPT TOOL_CHAIN_TAG=CLANGDWARF -p UnitTestFrameworkPkg
      - name: Build UnitTestFrameworkPkg IA32 Unit Tests
        shell: cmd
        run: |
          call edksetup.bat Mingw-w64
          call build -a IA32 -t CLANGDWARF -b NOOPT -p UnitTestFrameworkPkg/Test/UnitTestFrameworkPkgHostTest.dsc -j Build/UnitTestFrameworkPkgHostTestIA32.log >NUL
      - name: Build EmulatorPkg X64 Host Module
        shell: cmd
        run: |
          call edksetup.bat Mingw-w64
          call build -a X64 -t CLANGDWARF -b DEBUG   -p EmulatorPkg/EmulatorPkg.dsc -m EmulatorPkg/Win/Host/WinHost.inf -j Build/EmulatorX64DebugBuild.log >NUL
          call build -a X64 -t CLANGDWARF -b RELEASE -p EmulatorPkg/EmulatorPkg.dsc -m EmulatorPkg/Win/Host/WinHost.inf -j Build/EmulatorX64ReleaseBuild.log >NUL
          call build -a X64 -t CLANGDWARF -b NOOPT   -p EmulatorPkg/EmulatorPkg.dsc -m EmulatorPkg/Win/Host/WinHost.inf -j Build/EmulatorX64NooptBuild.log >NUL
      - name: Build EmulatorPkg IA32 Host Module
        shell: cmd
        run: |
          call edksetup.bat Mingw-w64
          call build -a IA32 -t CLANGDWARF -b DEBUG   -p EmulatorPkg/EmulatorPkg.dsc -m EmulatorPkg/Win/Host/WinHost.inf -j Build/EmulatorIA32DebugBuild.log >NUL
          call build -a IA32 -t CLANGDWARF -b RELEASE -p EmulatorPkg/EmulatorPkg.dsc -m EmulatorPkg/Win/Host/WinHost.inf -j Build/EmulatorIA32ReleaseBuild.log >NUL
          call build -a IA32 -t CLANGDWARF -b NOOPT   -p EmulatorPkg/EmulatorPkg.dsc -m EmulatorPkg/Win/Host/WinHost.inf -j Build/EmulatorIA32NooptBuild.log >NUL
      - name: Build OVMF Platform
        shell: cmd
        run: |
          call edksetup.bat Mingw-w64
          call build -a IA32 -a X64 -t CLANGDWARF -b DEBUG -p OvmfPkg/OvmfPkgIa32X64.dsc -D SMM_REQUIRE -j Build/OvmfIa32X64Build.log >NUL
      - name: Upload Windows Mingw Precheck Logs
        uses: actions/upload-artifact@v4
        with:
          name: Upload Windows Mingw Precheck Logs
          path: |
            BaseTools/BaseToolsBuild/*.txt
            Build/**/BUILDLOG*.txt
            Build/*.txt
            Build/*.log
        if: always()

  build_windows_llvm_mingw_clang_packages:
    name: Build Windows LLVM MINGW CLANG Packages (${{ join(matrix.*, ' - ') }})
    needs: build_windows_llvm_mingw_clang_precheck
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - DEBUG
          - RELEASE
        build_arch:
          - IA32
          - X64
        tool_chain_tag:
          - CLANGDWARF
        build_package:
          - CryptoPkg,FatPkg,FmpDevicePkg,PcAtChipsetPkg,PrmPkg,SourceLevelDebugPkg,UnitTestFrameworkPkg,StandaloneMmPkg,SignedCapsulePkg
          - ArmPkg,ArmPlatformPkg,DynamicTablesPkg,EmbeddedPkg,NetworkPkg,RedfishPkg,MdeModulePkg,MdePkg,IntelFsp2Pkg,IntelFsp2WrapperPkg,UefiCpuPkg,SecurityPkg,ShellPkg
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Windows LLVM MINGW CLANG Job
        uses: ./.github/actions/windows-setup-mingw-llvm-clang-job
        with:
          llvm_version: '20250709'
          llvm_install_path: 'C:\llvm-mingw-20250709-ucrt-x86_64'
          python-version: '3.12'
          stuart-ci-settings-file: '.pytool/CISettings.py'
          edk2-tools-build-params: '-a X64 -t ${{ matrix.tool_chain_tag }}'
      - name: 'Build Packages ${{ matrix.tool_chain_tag }}-Mingw'
        shell: cmd
        run: |
          stuart_ci_build -c ".pytool/CISettings.py" -a ${{ matrix.build_arch }} -t ${{ matrix.build_type }} TOOL_CHAIN_TAG=${{ matrix.tool_chain_tag }} -p "${{ matrix.build_package }}"
      - name: Upload Windows Mingw Logs
        uses: actions/upload-artifact@v4
        with:
          name: Upload Windows Mingw Logs (${{ matrix.build_arch }}-${{ matrix.build_type }}-${{ matrix.tool_chain_tag }}-${{ strategy.job-index }})
          path: |
            BaseTools/BaseToolsBuild/*.txt
            Build/**/BUILDLOG*.txt
            Build/*.txt
            Build/*.log
        if: always()

  build_windows_llvm_mingw_clang_noopt_unit_tests:
    name: Build Windows LLVM MINGW CLANG Unit Tests (${{ join(matrix.*, ' - ') }})
    needs: build_windows_llvm_mingw_clang_precheck
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - NOOPT
        build_arch:
          - X64
        tool_chain_tag:
          - CLANGDWARF
        build_package:
          - CryptoPkg,FatPkg,FmpDevicePkg,PcAtChipsetPkg,PrmPkg,SourceLevelDebugPkg,UnitTestFrameworkPkg,StandaloneMmPkg,SignedCapsulePkg
          - ArmPkg,ArmPlatformPkg,DynamicTablesPkg,EmbeddedPkg,NetworkPkg,RedfishPkg,MdeModulePkg,MdePkg,IntelFsp2Pkg,IntelFsp2WrapperPkg,UefiCpuPkg,SecurityPkg,ShellPkg
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Windows LLVM MINGW CLANG Job
        uses: ./.github/actions/windows-setup-mingw-llvm-clang-job
        with:
          llvm_version: '20250709'
          llvm_install_path: 'C:\llvm-mingw-20250709-ucrt-x86_64'
          python-version: '3.12'
          stuart-ci-settings-file: '.pytool/CISettings.py'
          edk2-tools-build-params: '-a X64 -t ${{ matrix.tool_chain_tag }}'
      - name: 'Build Packages ${{ matrix.tool_chain_tag }}-Mingw'
        shell: cmd
        run: |
          stuart_ci_build -c ".pytool/CISettings.py" -a ${{ matrix.build_arch }} -t ${{ matrix.build_type }} TOOL_CHAIN_TAG=${{ matrix.tool_chain_tag }} -p "${{ matrix.build_package }}"
      - name: Upload Windows Mingw Unit Test Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Windows Mingw Unit TestLogs (${{ matrix.build_arch }}-${{ matrix.build_type }}-${{ matrix.tool_chain_tag }}-${{ strategy.job-index }})"
          path: |
            BaseTools/BaseToolsBuild/*.txt
            Build/**/BUILDLOG*.txt
            Build/*.txt
            Build/*.log
        if: always()

  build_windows_llvm_mingw_clang_emulatorpkg:
    name: Build Windows LLVM MINGW CLANG EmulatorPkg
    needs: build_windows_llvm_mingw_clang_precheck
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Windows LLVM MINGW CLANG Job
        uses: ./.github/actions/windows-setup-mingw-llvm-clang-job
        with:
          llvm_version: '20250709'
          llvm_install_path: 'C:\llvm-mingw-20250709-ucrt-x86_64'
          python-version: '3.12'
          stuart-ci-settings-file: '.pytool/CISettings.py'
          edk2-tools-build-params: '-a X64 -t CLANGDWARF'
      - name: Build EmulatorPkg X64 Host Module
        shell: cmd
        run: |
          call edksetup.bat Mingw-w64
          call build -a X64 -t CLANGDWARF -b NOOPT   -p EmulatorPkg/EmulatorPkg.dsc -D SECURE_BOOT_ENABLE -D REDFISH_ENABLE -j Build/EmulatorX64NooptBuild.log >NUL
          call build -a X64 -t CLANGDWARF -b DEBUG   -p EmulatorPkg/EmulatorPkg.dsc -D NETWORK_ENABLE=FALSE                 -j Build/EmulatorX64DebugBuild.log >NUL
          call build -a X64 -t CLANGDWARF -b RELEASE -p EmulatorPkg/EmulatorPkg.dsc                                         -j Build/EmulatorX64ReleaseBuild.log >NUL
      - name: Build EmulatorPkg IA32 Host Module
        shell: cmd
        run: |
          call edksetup.bat Mingw-w64
          call build -a IA32 -t CLANGDWARF -b NOOPT   -p EmulatorPkg/EmulatorPkg.dsc -D SECURE_BOOT_ENABLE -D REDFISH_ENABLE -j Build/EmulatorIA32NooptBuild.log >NUL
          call build -a IA32 -t CLANGDWARF -b DEBUG   -p EmulatorPkg/EmulatorPkg.dsc -D NETWORK_ENABLE=FALSE                 -j Build/EmulatorIA32DebugBuild.log >NUL
          call build -a IA32 -t CLANGDWARF -b RELEASE -p EmulatorPkg/EmulatorPkg.dsc                                         -j Build/EmulatorIA32ReleaseBuild.log >NUL
      - name: Upload Windows LLVM MINGW CLANG EmulatorPkg Logs
        uses: actions/upload-artifact@v4
        with:
          name: Upload Windows LLVM MINGW CLANG EmulatorPkg Logs
          path: |
            BaseTools/BaseToolsBuild/*.txt
            Build/**/BUILDLOG*.txt
            Build/*.txt
            Build/*.log
        if: always()
