## @file
# A workflow using Windows MINGW edk2-clang tools that builds packages and
# uploads artifacts.
#
# Firmware Build Support:             CLANGPDB/CLANGDWARF - IA32/X64
# Host-Based Unit Test Build Support: CLANGDWARF          - X64
# EmulatorPkg Build Support:          CLANGDWARF          - X64
#
# Copyright (C) 2025 Intel Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: Windows Mingw edk2-clang 20.1.8 Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - sandbox/master
      - clang_ci_v5b

jobs:
  set_package_lists:
    name: Set Package Lists
    uses: ./.github/workflows/ubuntu-set-package-lists-and-patch-check.yml

  show_package_lists_value:
    needs: set_package_lists
    name: Show Package Lists Value
    runs-on: windows-latest
    steps:
      - name: Show Package Lists Value
        run: |
          echo '${{ needs.set_package_lists.outputs.package-lists }}'
      - name: Contains EmulatorPkg
        if: contains(needs.set_package_lists.outputs.package-lists, 'EmulatorPkg')
        run: echo "EmulatorPkg is in the package list"
      - name: Contains FooPkg
        if: contains(needs.set_package_lists.outputs.package-lists, 'FooPkg')
        run: echo "FooPkg is in the package list"

  show_package_lists_workflow_call:
    needs: set_package_lists
    name: Show Package Lists Workflow Call
    uses: ./.github/workflows/windows-clang-20-show-package-lists.yml
    with:
      build_type_list: '["DEBUG", "RELEASE"]'
      build_arch_list: '["IA32", "X64"]'
      tool_chain_tag_list: '["CLANGPDB", "CLANGDWARF"]'
      package-lists: ${{ needs.set_package_lists.outputs.package-lists }}

  show_package_lists_inline:
    needs: set_package_lists
    name: Show Package Lists Inline
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - 'DEBUG'
          - 'RELEASE'
        build_arch:
          - 'IA32'
          - 'X64'
        tool_chain_tag:
          - 'CLANGPDB'
          - 'CLANGDWARF'
        build_package: ${{ fromJSON(needs.set_package_lists.outputs.package-lists) }}
    steps:
      - name: Show Matrix values
        run: |
          echo "Build Package: ${{ matrix.build_package }}"
          echo "Build Arch:    ${{ matrix.build_arch }}"
          echo "Build Type:    ${{ matrix.build_type }}"
          echo "Tool Chain:    ${{ matrix.tool_chain_tag }}"

  build_windows_mingw_edk2_clang_packages_basic_acceptance_test:
    needs: set_package_lists
    name: Build Windows Mingw edk2-clang Packages Basic Acceptance Test
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Windows Mingw edk2-clang Job
        uses: ./.github/actions/windows-setup-clang-job
        with:
          windows-clang-installer: 'edk2-clang'
          python-version: '3.12'
          pip-requirements: 'pip-requirements.txt'
          stuart-ci-settings-file: '.pytool/CISettings.py'
          edk2-tools-build-params: '-a X64 -t CLANGPDB'
      - name: Build HelloWorld CLANGPDB
        shell: cmd
        run: |
          call edksetup.bat Mingw-w64
          call build -a IA32 -a X64 -t CLANGPDB -b DEBUG -b RELEASE -b NOOPT -p MdeModulePkg/MdeModulePkg.dsc -m MdeModulePkg/Application/HelloWorld/HelloWorld.inf -j Build/HelloWorldClangPdbBuild.log >NUL
      - name: Build HelloWorld CLANGDWARF
        shell: cmd
        run: |
          call edksetup.bat Mingw-w64
          call build -a IA32 -a X64 -t CLANGDWARF -b DEBUG -b RELEASE -b NOOPT -p MdeModulePkg/MdeModulePkg.dsc -m MdeModulePkg/Application/HelloWorld/HelloWorld.inf -j Build/HelloWorldClangDwarfBuild.log >NUL
      - name: Build UnitTestFrameworkPkg X64 Unit Tests
        run: |
          stuart_ci_build -c ".pytool/CISettings.py" -a X64 -t NOOPT TOOL_CHAIN_TAG=CLANGDWARF -p UnitTestFrameworkPkg
      - name: Upload Windows Mingw edk2-clang Packages Basic Acceptance Test Logs
        uses: actions/upload-artifact@v6
        with:
          name: Upload Windows Mingw edk2-clang Packages Basic Acceptance Test Logs
          path: |
            BaseTools/BaseToolsBuild/*.txt
            Build/**/BUILDLOG*.txt
            Build/*.txt
            Build/*.log
        if: always()

  build_windows_mingw_edk2_clang_platforms_basic_acceptance_test:
    needs: set_package_lists
    name: Build Windows Mingw edk2-clang Platforms Basic Acceptance Test
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Windows Mingw edk2-clang Job
        uses: ./.github/actions/windows-setup-clang-job
        with:
          windows-clang-installer: 'edk2-clang'
          python-version: '3.12'
          pip-requirements: 'pip-requirements.txt'
          stuart-ci-settings-file: '.pytool/CISettings.py'
          edk2-tools-build-params: '-a X64 -t CLANGPDB'
      - name: Build EmulatorPkg X64 Host Module
        shell: cmd
        run: |
          call edksetup.bat Mingw-w64
          call build -a X64 -t CLANGDWARF -b DEBUG   -p EmulatorPkg/EmulatorPkg.dsc -m EmulatorPkg/Win/Host/WinHost.inf -j Build/EmulatorX64DebugBuild.log >NUL
      - name: Build OVMF Platform CLANGPDB
        shell: cmd
        run: |
          call edksetup.bat Mingw-w64
          call build -a IA32 -a X64 -t CLANGPDB -b DEBUG -p OvmfPkg/OvmfPkgIa32X64.dsc -D SMM_REQUIRE -j Build/OvmfIa32X64BuildClangPdb.log >NUL
      - name: Upload Windows Mingw edk2-clang Platforms Basic Acceptance Test Logs
        uses: actions/upload-artifact@v6
        with:
          name: Upload Windows Mingw edk2-clang Platforms Basic Acceptance Test Logs
          path: |
            BaseTools/BaseToolsBuild/*.txt
            Build/**/BUILDLOG*.txt
            Build/*.txt
            Build/*.log
        if: always()

  build_windows_mingw_edk2_clang_packages:
    needs:
      - set_package_lists
#      - build_windows_mingw_edk2_clang_packages_basic_acceptance_test
#      - build_windows_mingw_edk2_clang_platforms_basic_acceptance_test
    uses: ./.github/workflows/windows-clang-20-package-build-test.yml
    with:
      windows-clang-installer: 'edk2-clang'
      python-version: '3.12'
      pip-requirements: 'pip-requirements.txt'
      stuart-ci-settings-file: '.pytool/CISettings.py'
      edk2-tools-build-params: '-t CLANGPDB'
      build_type_list: '["DEBUG", "RELEASE"]'
      build_arch_list: '["IA32", "X64"]'
      tool_chain_tag_list: '["CLANGPDB", "CLANGDWARF"]'
      package-lists: ${{ needs.set_package_lists.outputs.package-lists }}

  build_windows_mingw_edk2_clang_noopt_unit_tests:
    needs:
      - set_package_lists
#      - build_windows_mingw_edk2_clang_packages_basic_acceptance_test
#      - build_windows_mingw_edk2_clang_platforms_basic_acceptance_test
    uses: ./.github/workflows/windows-clang-20-package-build-test.yml
    with:
      windows-clang-installer: 'edk2-clang'
      python-version: '3.12'
      pip-requirements: 'pip-requirements.txt'
      stuart-ci-settings-file: '.pytool/CISettings.py'
      edk2-tools-build-params: '-t CLANGPDB'
      build_type_list: '["NOOPT"]'
      build_arch_list: '["X64"]'
      tool_chain_tag_list: '["CLANGDWARF"]'
      package-lists: ${{ needs.set_package_lists.outputs.package-lists }}

  build_windows_mingw_edk2_clang_emulatorpkg:
    name: Build Windows Mingw edk2-clang EmulatorPkg
    needs:
      - set_package_lists
      - build_windows_mingw_edk2_clang_packages_basic_acceptance_test
      - build_windows_mingw_edk2_clang_platforms_basic_acceptance_test
    if: contains(needs.set_package_lists.outputs.package-lists, 'EmulatorPkg')
    uses: ./.github/workflows/windows-clang-20-emulator-build-test.yml
    with:
      windows-clang-installer: 'edk2-clang'
      python-version: '3.12'
      pip-requirements: 'pip-requirements.txt'
      stuart-ci-settings-file: '.pytool/CISettings.py'
      edk2-tools-build-params: '-a X64 -t CLANGDWARF'
      edk-setup-params: 'Mingw-w64'
      build_arch_list: '["X64"]'
      tool_chain_tag_list: '["CLANGDWARF"]'
