## @file
# A workflow using Windows to stress stuart_update
#
# Copyright (C) 2025 Intel Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: Windows Stress Test for stuart_update

on:
  workflow_dispatch:
    inputs:
      windows-runs-on:
        description: 'The runner label for Windows jobs.'
        required: true
        type: string
        default: 'windows-2025'
      python-version:
        description: 'The version of Python to use.'
        required: true
        type: string
        default: '3.12'
      pip-requirements:
        description: 'Path to pip requirements file'
        required: true
        type: string
        default: 'pip-requirements.txt'
      stuart-ci-settings-file:
        description: 'The path to the Stuart CI settings file.'
        required: true
        type: string
        default: '.pytool/CISettings.py'
      edk2-tools-build-params:
        description: 'The EDK2 Tools build parameters.'
        required: true
        type: string
        default: '-t VS2022'
      stuart-update-iterations:
        description: 'Number of stuart_update iterations to run in stress test.'
        required: false
        type: string
        default: '100'

jobs:
  build_windows_packages:
    name: Run stuart_update Stress Test on Windows ${{ matrix.item }}
    runs-on: ${{ inputs.windows-runs-on }}
    strategy:
      fail-fast: false
      matrix:
        item  : [0,1,2,3,4,5,6,7,8,9]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Ensure safe directory for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Setup Windows CLANG Job ${{ matrix.item }}
        uses: ./.github/actions/windows-setup-clang-job
        with:
          windows-clang-installer: 'none'
          python-version: ${{ inputs.python-version }}
          pip-requirements: ${{ inputs.pip-requirements }}
          stuart-ci-settings-file: ${{ inputs.stuart-ci-settings-file }}
          edk2-tools-build-params: ${{ inputs.edk2-tools-build-params }}
      - name: 'Run stuart_update Stress Test in a loop'
        shell: pwsh
        run: |
          for ($i = 1; $i -le ${{ inputs.stuart-update-iterations }}; $i++) {
          Write-Output "Iteration $i of stuart_update"
          stuart_update -c ${{ inputs.stuart-ci-settings-file }}
          }
