# @file
# A workflow that builds packages using clang and upload it's artifacts.
#
# Copyright (C) 2025 Intel Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: Windows CLANG Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - sandbox/master

jobs:
  build_windows_clang:
    name: Build Windows (${{ join(matrix.*, ' - ') }})
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - DEBUG
        build_arch:
          - X64
        build_package:
          - FatPkg
    steps:
      - name: Checkout Reference or Pull Request
        uses: ./.github/actions/checkout-reference-or-pull-request
      - name: Restore cached venv
        uses: actions/cache/restore@v4
        id: cache-venv
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('pip-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Set up Python 3.12
        if: steps.cache-venv.outputs.cache-hit != 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Create and install venv if cache missed
        shell: cmd
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          PATH=%GITHUB_WORKSPACE%\.venv\Scripts;%PATH%
          python -m pip install --upgrade pip
          pip install -r pip-requirements.txt
      - name: Save venv cache
        uses: actions/cache/save@v4
        if: steps.cache-venv.outputs.cache-hit != 'true'
        with:
          path: .venv
          key: ${{ steps.cache-venv.outputs.cache-primary-key }}
      - name: Activate venv
        shell: cmd
        run: |
          PATH=%GITHUB_WORKSPACE%\.venv\Scripts;%PATH%
          echo PATH=%PATH% >> %GITHUB_ENV%
          pip list
      - name: Restore CLANG 20.1.8
        id: cache-clang
        uses: actions/cache/restore@v4
        with:
          path: C:\Program Files\LLVM
          key: ${{ runner.os }}-LLVM-20.1.8-win64.exe
          restore-keys: |
            ${{ runner.os }}-LLVM-20.1.8-win64.exe
      - name: Install CLANG 20.1.8
        if: steps.cache-clang.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          curl -SL --output llvm_install.exe https://github.com/llvm/llvm-project/releases/download/llvmorg-20.1.8/LLVM-20.1.8-win64.exe
          llvm_install.exe /S
      - name: Save CLANG 20.1.8
        if: steps.cache-clang.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: C:\Program Files\LLVM
          key: ${{ steps.cache-clang.outputs.cache-primary-key }}
      - name: Restore LLVM-MinGW
        id: cache-llvm-mingw
        uses: actions/cache/restore@v4
        with:
          path: C:\llvm-mingw-20250709-ucrt-x86_64
          key: ${{ runner.os }}-llvm-mingw-20250709-ucrt-x86_64
          restore-keys: |
            ${{ runner.os }}-llvm-mingw-20250709-ucrt-x86_64
      - name: Install LLVM-MinGW
        if: steps.cache-llvm-mingw.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          curl -L -o "llvm-mingw.zip" "https://github.com/mstorsjo/llvm-mingw/releases/download/20250709/llvm-mingw-20250709-ucrt-x86_64.zip"
          powershell -command "Expand-Archive -Path 'llvm-mingw.zip' -DestinationPath 'C:\' -Force"
          dir "C:\llvm-mingw-20250709-ucrt-x86_64\bin"
      - name: Save LLVM-MinGW
        if: steps.cache-llvm-mingw.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: C:\llvm-mingw-20250709-ucrt-x86_64
          key: ${{ steps.cache-llvm-mingw.outputs.cache-primary-key }}
      - name: Restore TianoCore Mingw CLANG
        id: cache-edk2-clang
        uses: actions/cache/restore@v4
        with:
          path: C:\edk2-clang
          key: ${{ runner.os }}-edk2-clang-20.1.8
          restore-keys: |
            ${{ runner.os }}-edk2-clang-20.1.8
      - name: Install TianoCore Mingw CLANG 20.1.8
        if: steps.cache-edk2-clang.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          curl -L -o EdkClangSetup-20.1.8.0.exe https://github.com/tianocore/edk2-edkrepo/releases/download/edkclang-v20.1.8/EdkClangSetup-20.1.8.0.exe
          EdkClangSetup-20.1.8.0.exe /silent
      - name: Save TianoCore Mingw CLANG
        if: steps.cache-edk2-clang.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: C:\edk2-clang
          key: ${{ steps.cache-edk2-clang.outputs.cache-primary-key }}
      - name: Restore submodules
        id: cache-submodules
        uses: actions/cache/restore@v4
        with:
          path: .git/modules
          key: ${{ runner.os }}-submodules-${{ hashFiles('.gitmodules') }}
          restore-keys: |
            ${{ runner.os }}-submodules-
      - name: 'Clone Submodules'
        run: stuart_setup -c ".pytool/CISettings.py" TOOL_CHAIN_TAG=CLANGPDB
      - name: Save submodules
        if: steps.cache-submodules.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: .git/modules
          key: ${{ steps.cache-submodules.outputs.cache-primary-key }}
      - name: 'Download External Dependencies'
        run: stuart_update -c ".pytool/CISettings.py" TOOL_CHAIN_TAG=CLANGPDB
      - name: 'Build Packages CLANGPDB-Mingw'
        shell: cmd
        env:
          CLANG_BIN: "C:\\edk2-clang\\bin\\"
          BASETOOLS_MINGW_PATH: "C:\\edk2-clang"
          BASETOOLS_MINGW_BUILD: "TRUE"
          NASM_PREFIX: "${{ github.workspace }}\\BaseTools\\Bin\\mu_nasm_extdep\\Windows-x86-64\\"
          IASL_PREFIX: "${{ github.workspace }}\\BaseTools\\Bin\\edk2-acpica-iasl_extdep\\Windows-x86\\"
        run: |
          PATH=%CLANG_BIN%;%PATH%
          set
          call edksetup.bat ForceRebuild Mingw-w64
          build -a X64 -b DEBUG -t CLANGPDB -p FatPkg/PatPkg.dsc -j Build\FatPkgClangPdbMingwBuild.log -v >NUL
        if: always()
      - name: 'Build BaseTools'
        run: python BaseTools/Edk2ToolsBuild.py -t VS2022
      - name: 'Stuart Packages CLANGPDB-Mingw'
        shell: cmd
        env:
          CLANG_BIN: "C:\\edk2-clang\\bin\\"
        run: |
          PATH=C:\edk2-clang\bin;%PATH%
          set
          stuart_ci_build -c ".pytool/CISettings.py" -a ${{ matrix.build_arch }} -t ${{ matrix.build_type }} TOOL_CHAIN_TAG=CLANGPDB -p "${{ matrix.build_package }}" -v
        if: always()
      - name: Upload CLANGPDB-Mingw Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Windows CLANGPDB-Mingw Logs (${{ join(matrix.*, ' - ') }})"
          path: |
            Build/**/*
        if: always()
      - name: Remove Build Directory CLANGPDB-Mingw
        shell: cmd
        run: rmdir /s /q Build
        if: always()
      - name: 'Build Packages CLANGDWARF-Mingw'
        shell: cmd
        env:
          CLANG_BIN: "C:\\llvm-mingw-20250709-ucrt-x86_64\\bin\\"
        run: |
          PATH=C:\llvm-mingw-20250709-ucrt-x86_64\bin;%PATH%
          set
          stuart_ci_build -c ".pytool/CISettings.py" -a ${{ matrix.build_arch }} -t ${{ matrix.build_type }} TOOL_CHAIN_TAG=CLANGDWARF -p "${{ matrix.build_package }}" -v
        if: always()
      - name: Upload CLANGDWARF-Mingw Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Windows CLANGDWARF-Mingw Logs (${{ join(matrix.*, ' - ') }})"
          path: |
            Build/**/*
        if: always()
      - name: Remove Build Directory CLANGDWARF-Mingw
        shell: cmd
        run: rmdir /s /q Build
        if: always()
      - name: 'Build Packages CLANGPDB-VS'
        shell: cmd
        env:
          CLANG_BIN: "C:\\Program Files\\LLVM\\bin\\"
        run: |
          PATH=C:\Program Files\LLVM\bin;%PATH%
          set
          stuart_ci_build -c ".pytool/CISettings.py" -a ${{ matrix.build_arch }} -t ${{ matrix.build_type }} TOOL_CHAIN_TAG=CLANGPDB -p "${{ matrix.build_package }}" -v
        if: always()
      - name: Upload CLANGPDB-VS Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Windows CLANGPDB-VS Logs (${{ join(matrix.*, ' - ') }})"
          path: |
            Build/**/*
        if: always()
