# @file
# A workflow that builds packages using clang and upload it's artifacts.
#
# Copyright (c) Intel Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: Windows Mingw LLVM 20.1.8 CLANG Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - sandbox/master

jobs:
  build_windows_clang:
    name: Build Windows (${{ join(matrix.*, ' - ') }})
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        build_type:
          - DEBUG
          - RELEASE
        build_arch:
          - IA32
          - X64
        tool_chain_tag:
          - CLANGDWARF
        build_package:
          - CryptoPkg,FatPkg,FmpDevicePkg,PcAtChipsetPkg,PrmPkg,SourceLevelDebugPkg,UnitTestFrameworkPkg,StandaloneMmPkg,SignedCapsulePkg
          - ArmPkg,ArmPlatformPkg,DynamicTablesPkg,EmbeddedPkg,NetworkPkg,RedfishPkg,MdeModulePkg,MdePkg,IntelFsp2Pkg,IntelFsp2WrapperPkg,UefiCpuPkg,SecurityPkg,ShellPkg
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ensure safe directory for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Restore LLVM-MinGW
        id: cache-llvm-mingw
        uses: actions/cache/restore@v4
        with:
          path: C:\llvm-mingw-20250709-ucrt-x86_64
          key: ${{ runner.os }}-llvm-mingw-20250709-ucrt-x86_64
          restore-keys: |
            ${{ runner.os }}-llvm-mingw-20250709-ucrt-x86_64
      - name: Install LLVM-MinGW
        if: steps.cache-llvm-mingw.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          curl -L -o "llvm-mingw.zip" "https://github.com/mstorsjo/llvm-mingw/releases/download/20250709/llvm-mingw-20250709-ucrt-x86_64.zip"
          powershell -command "Expand-Archive -Path 'llvm-mingw.zip' -DestinationPath 'C:\' -Force"
          dir "C:\llvm-mingw-20250709-ucrt-x86_64\bin"
      - name: Save LLVM-MinGW
        if: steps.cache-llvm-mingw.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: C:\llvm-mingw-20250709-ucrt-x86_64
          key: ${{ steps.cache-llvm-mingw.outputs.cache-primary-key }}
      - name: Add CLANG 20.1.8 to PATH
        shell: cmd
        run: |
          PATH=C:\llvm-mingw-20250709-ucrt-x86_64\bin;%PATH%
          echo PATH=%PATH% >> %GITHUB_ENV%
      - name: Restore cached venv
        uses: actions/cache/restore@v4
        id: cache-venv
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('pip-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: Set up Python 3.12
        if: steps.cache-venv.outputs.cache-hit != 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Create and install venv if cache missed
        shell: cmd
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          PATH=%GITHUB_WORKSPACE%\.venv\Scripts;%PATH%
          python -m pip install --upgrade pip
          pip install -r pip-requirements.txt
      - name: Save venv cache
        uses: actions/cache/save@v4
        if: steps.cache-venv.outputs.cache-hit != 'true'
        with:
          path: .venv
          key: ${{ steps.cache-venv.outputs.cache-primary-key }}
      - name: Activate venv
        shell: cmd
        run: |
          PATH=%GITHUB_WORKSPACE%\.venv\Scripts;%PATH%
          echo PATH=%PATH% >> %GITHUB_ENV%
      - name: Restore submodules
        id: cache-submodules
        uses: actions/cache/restore@v4
        with:
          path: .git/modules
          key: ${{ runner.os }}-submodules-${{ hashFiles('.gitmodules') }}
          restore-keys: |
            ${{ runner.os }}-submodules-
      - name: 'Clone Submodules'
        run: stuart_setup -c ".pytool/CISettings.py"
      - name: Save submodules
        if: steps.cache-submodules.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: .git/modules
          key: ${{ steps.cache-submodules.outputs.cache-primary-key }}
      - name: 'Download External Dependencies'
        run: stuart_update -c ".pytool/CISettings.py"
      - name: 'Build BaseTools'
        env:
          CC: "clang"
          CXX: "clang++"
        run: python BaseTools/Edk2ToolsBuild.py -a X64 -t ${{ matrix.tool_chain_tag }}
      - name: 'Build Packages ${{ matrix.tool_chain_tag }}-Mingw'
        shell: cmd
        env:
          CLANG_BIN: "C:\\llvm-mingw-20250709-ucrt-x86_64\\bin\\"
          NASM_PREFIX: "${{ github.workspace }}\\BaseTools\\Bin\\mu_nasm_extdep\\Windows-x86-64\\"
          IASL_PREFIX: "${{ github.workspace }}\\BaseTools\\Bin\\edk2-acpica-iasl_extdep\\Windows-x86\\"
        run: |
          stuart_ci_build -c ".pytool/CISettings.py" -a ${{ matrix.build_arch }} -t ${{ matrix.build_type }} TOOL_CHAIN_TAG=${{ matrix.tool_chain_tag }} -p "${{ matrix.build_package }}"
      - name: Upload Windows Mingw Logs
        uses: actions/upload-artifact@v4
        with:
          name: "Upload Windows Mingw Logs (${{ matrix.build_arch }}-${{ matrix.build_type }}-${{ matrix.tool_chain_tag }}-${{ strategy.job-index }})"
          path: |
            BaseTools/BaseToolsBuild/*.txt
            Build/**/BUILDLOG*.txt
            Build/*.txt
            Build/*.log
        if: always()
